<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/sabredav_framework/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 01/22/2015 08:12:49
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'SabreDAV Framework';
$labels['plugindescription'] = 'Pomocný doplněk pro distribuci SabreDAV Frameworku přizpůsobeného pro doplňky MyRoundcube.';

?>