<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/sabredav_framework/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 18:17:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'SabreDAV Framework';
$labels['plugindescription'] = 'Complemento auxiliar para distribuir SabreDAV Framework personalizado para complementos MyRoundcube.';

?>