<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/myrc_branch/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 05/08/2013 03:47:20
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'MyRoundcube branch';
$labels['plugindescription'] = 'A helper plugin to indicate other plugins the MyRoundcube branch.';

?>