<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 01/22/2015 08:09:44
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Plánovač';
$labels['pluginname'] = 'Plánovač';
$labels['plugindescription'] = 'Jde o hybrid mezi jednoduchým kalendářem a seznamem úkolů';
$labels['incompatiblebrowser'] = 'Pro přístup k Plánovači použijte Internet Explorer 9 nebo alternativní prohlížeč.';
$labels['plan'] = 'Povolit';
$labels['view'] = 'Zobrazit';
$labels['select_view'] = 'Vybrat pohled';
$labels['flags'] = 'Příznaky';
$labels['preview'] = 'Náhled';
$labels['new'] = 'Přidat nový plán';
$labels['done'] = 'Hotovo';
$labels['done_plan'] = 'Označit plán jako hotový';
$labels['star'] = 'Hvězda';
$labels['edit'] = 'Změnit plán';
$labels['delete'] = 'Smazat plán';
$labels['remove'] = 'Odstranit plán';
$labels['remove_flag'] = 'Odstranit příznak';
$labels['remove_date'] = 'Odstranit ';
$labels['toggle'] = 'Přepnout příznak';
$labels['expunge'] = 'Smazat položky';
$labels['expunge_deleted'] = 'Odstranit trvale smazané položky';
$labels['help'] = 'Nápověda';
$labels['cancel'] = 'Zrušit';
$labels['search'] = 'Hledat';
$labels['searchresult'] = 'Výsledek hledání pro';
$labels['matches'] = 'odpovídá';
$labels['matches_plural'] = 'odpovídá';
$labels['all'] = 'Vše';
$labels['show_all'] = 'Zobrazit všechny plány';
$labels['starred'] = 'Zvýrazněné';
$labels['star_plan'] = 'Zvýraznit položku';
$labels['unstar_plan'] = 'Zrušit zvýraznění položky';
$labels['today'] = 'Dnes';
$labels['show_today'] = 'Zobrazit dnešní plány';
$labels['tomorrow'] = 'Zítra';
$labels['show_tomorrow'] = 'Zobrazit zítřejší plány';
$labels['week'] = 'Týden';
$labels['deleted'] = 'Smazané';
$labels['overdue'] = 'Zpožděné';
$labels['show_overdue'] = 'Zobrazit zpožděné plány ';
$labels['birthdays'] = 'Narozeniny';
$labels['birthdays_singular'] = 'Narozeniny';
$labels['filter'] = 'Filtr';
$labels['nofilter'] = 'žádný';
$labels['removefilter'] = 'Odstranit filtr';
$labels['plans'] = 'Plány';
$labels['todos'] = 'Seznam úkolů';
$labels['birthdays_yes'] = 'Zobrazit narozeniny';
$labels['birthdays_no'] = 'Nezobrazovat narozeniny';
$labels['timeText'] = 'Čas';
$labels['hourText'] = 'Hodiny';
$labels['minuteText'] = 'Minuty';
$labels['datetimehints'] = 'Formáty data a času (příklady)';
$labels['errorsaving'] = 'Při ukládání nastala chyba';
$labels['happybirthday'] = 'Upozornit na přání k narozeninám!';

?>