<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['planner'] = 'Planlægning';
$labels['pluginname'] = 'Planlægning';
$labels['plugindescription'] = 'Dette er en mellemting mellem en simpel kalender og en Todo liste';
$labels['incompatiblebrowser'] = 'For at anvende dette planlægningsmodul, anvend venligst Internet Explorer 9 eller en alternativ Browser.';
$labels['view'] = 'Vis';
$labels['select_view'] = 'Vælg vis';
$labels['flags'] = 'Flag';
$labels['preview'] = 'Eksempel';
$labels['new'] = 'Tilføj ny opgave';
$labels['done'] = 'Afsluttet';
$labels['done_plan'] = 'Marker opgaven som afsluttet';
$labels['star'] = 'Stjerne';
$labels['edit'] = 'Rediger opgave';
$labels['delete'] = 'Slet opgave';
$labels['remove'] = 'Fjern opgave';
$labels['remove_flag'] = 'Fjern flag';
$labels['remove_date'] = 'Fjern dato med højre klik';
$labels['toggle'] = 'Vælg flag';
$labels['expunge'] = 'Slet emne';
$labels['expunge_deleted'] = 'Fjern slettet emne permanent';
$labels['help'] = 'Hjælp';
$labels['cancel'] = 'Afbryd';
$labels['search'] = 'Søg';
$labels['searchresult'] = 'Søgeresultat for';
$labels['matches'] = 'sammenfald';
$labels['matches_plural'] = 'sammenfalder';
$labels['all'] = 'Alle';
$labels['show_all'] = 'Vis alle opgaver';
$labels['starred'] = 'stjernemarkerede';
$labels['star_plan'] = 'Stjerne enme';
$labels['unstar_plan'] = 'Fjern stjerne emne';
$labels['today'] = 'I dag';
$labels['show_today'] = 'Vis dagens opgaver';
$labels['tomorrow'] = 'I morgen';
$labels['show_tomorrow'] = 'Vis morgendagens opgaver';
$labels['week'] = 'Uge';
$labels['deleted'] = 'Slettet';
$labels['overdue'] = 'Overskredet';
$labels['show_overdue'] = 'Vis overskredet opgaver';
$labels['birthdays'] = 'Fødselsdage';
$labels['birthdays_singular'] = 'Fødselsdag';
$labels['filter'] = 'Filter';
$labels['nofilter'] = 'Ingen';
$labels['removefilter'] = 'Fjern Filter';
$labels['plans'] = 'Opgaver';
$labels['todos'] = 'ToDo\'s';
$labels['birthdays_yes'] = 'Vis Fødselsdage';
$labels['birthdays_no'] = 'Vis ikke Fødselsdage';
$labels['timeText'] = 'Tid';
$labels['hourText'] = 'Time';
$labels['minuteText'] = 'Minut';
$labels['datetimehints'] = 'Dato og tidsformat (eksempler)';
$labels['errorsaving'] = 'Der er opstået en fejl under gemningen';
$labels['happybirthday'] = 'Tillykke med Fødselsdagen!';

?>