<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/03/2012 07:19:59
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Planner';
$labels['pluginname'] = 'Planner';
$labels['plugindescription'] = 'This is a hybrid between a simple calendar and a Todo-List.';
$labels['incompatiblebrowser'] = 'To access the Planner, please use Internet Explorer 9 or an alternate browser.';
$labels['plan'] = 'Acccept';
$labels['view'] = 'View';
$labels['select_view'] = 'Select view';
$labels['flags'] = 'Flags';
$labels['preview'] = 'Preview';
$labels['new'] = 'Add new plan';
$labels['done'] = 'Done';
$labels['done_plan'] = 'Mark plan as done';
$labels['star'] = 'Star';
$labels['edit'] = 'Edit plan';
$labels['delete'] = 'Delete plan';
$labels['remove'] = 'Remove plan';
$labels['remove_flag'] = 'Remove flag';
$labels['remove_date'] = 'Remove date on right click';
$labels['toggle'] = 'Toggle flag';
$labels['expunge'] = 'Delete items';
$labels['expunge_deleted'] = 'Remove deleted items permanently';
$labels['help'] = 'Help';
$labels['cancel'] = 'Cancel';
$labels['search'] = 'Search';
$labels['searchresult'] = 'Search Result for';
$labels['matches'] = 'match';
$labels['matches_plural'] = 'matches';
$labels['all'] = 'All';
$labels['show_all'] = 'Show all plans';
$labels['starred'] = 'Starred';
$labels['star_plan'] = 'Star item';
$labels['unstar_plan'] = 'Unstar item';
$labels['today'] = 'Today';
$labels['show_today'] = 'Show today\'s plans';
$labels['tomorrow'] = 'Tomorrow';
$labels['show_tomorrow'] = 'Show tomorrow\'s plans';
$labels['week'] = 'Week';
$labels['deleted'] = 'Deleted';
$labels['overdue'] = 'Overdue';
$labels['show_overdue'] = 'Show overdue plans';
$labels['birthdays'] = 'Birthdays';
$labels['birthdays_singular'] = 'Birthday';
$labels['filter'] = 'Filter';
$labels['nofilter'] = 'None';
$labels['removefilter'] = 'Remove Filter';
$labels['plans'] = 'Plans';
$labels['todos'] = 'ToDo\'s';
$labels['birthdays_yes'] = 'Show Birthdays';
$labels['birthdays_no'] = 'Don\'t show Birthdays';
$labels['timeText'] = 'Time';
$labels['hourText'] = 'Hours';
$labels['minuteText'] = 'Minutes';
$labels['datetimehints'] = 'Date and Time Formats (Examples)';
$labels['errorsaving'] = 'An Error occurred while saving';
$labels['happybirthday'] = 'Happy Birthday Greetings!';

?>