<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                              |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['planner'] = 'Planner';
$labels['pluginname'] = 'Planner';
$labels['plugindescription'] = 'Este é um híbrido entre um calendário simples e uma lista de tarefas.';
$labels['incompatiblebrowser'] = 'Para acessar o Planner, por favor, use Internet Explorer 9 ou um navegador alternativo.';
$labels['view'] = 'Exibir';
$labels['select_view'] = 'Selecione visão';
$labels['flags'] = 'Marcadores';
$labels['preview'] = 'Visualizar';
$labels['new'] = 'Adicionar um novo plano';
$labels['done'] = 'Feito';
$labels['done_plan'] = 'Marcar plano como pronto';
$labels['star'] = 'Estrela';
$labels['edit'] = 'Editar plano';
$labels['delete'] = 'Excluir plano';
$labels['remove'] = 'Remover plano';
$labels['remove_flag'] = 'Remover marcador';
$labels['remove_date'] = 'Remover data com clique direito';
$labels['toggle'] = 'Alternar marcador';
$labels['expunge'] = 'Excluir itens';
$labels['expunge_deleted'] = 'Remover itens excluídos permanentemente';
$labels['help'] = 'Ajuda';
$labels['cancel'] = 'Cancelar';
$labels['search'] = 'Pesquisar';
$labels['searchresult'] = 'Procurar por';
$labels['matches'] = 'combina';
$labels['matches_plural'] = 'combinam';
$labels['all'] = 'Todos';
$labels['show_all'] = 'Mostrar todos os planos';
$labels['starred'] = 'Marcado com estrela';
$labels['star_plan'] = 'Marcar item';
$labels['unstar_plan'] = 'Desmarcar item';
$labels['today'] = 'Hoje';
$labels['show_today'] = 'Mostrar planos de hoje';
$labels['tomorrow'] = 'Amanhã';
$labels['show_tomorrow'] = 'Mostrar planos de amanhã';
$labels['week'] = 'Semana';
$labels['deleted'] = 'Excluído';
$labels['overdue'] = 'Atrasado';
$labels['show_overdue'] = 'Mostrar planos atrasados';
$labels['birthdays'] = 'Aniversários';
$labels['birthdays_singular'] = 'Data de nascimento';
$labels['filter'] = 'Filtro';
$labels['nofilter'] = 'Nenhum';
$labels['removefilter'] = 'Remover filtro';
$labels['plans'] = 'Planos';
$labels['todos'] = 'Lista de tarefas';
$labels['birthdays_yes'] = 'Mostrar aniversários';
$labels['birthdays_no'] = 'Não mostrar aniversários';
$labels['timeText'] = 'Hora';
$labels['hourText'] = 'Horas';
$labels['minuteText'] = 'Minutos';
$labels['datetimehints'] = 'Formatos de data e hora (exemplos)';
$labels['errorsaving'] = 'Um erro ocorreu ao salvar';
$labels['happybirthday'] = 'Feliz aniversário!';

