<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/tasklist/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/10/2015 10:28:55
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['navtitle'] = 'Tareas';
$labels['lists'] = 'Listas de tareas';
$labels['list'] = 'Lista de tarea';
$labels['tags'] = 'Etiquetas';
$labels['newtask'] = 'Nueva Tarea';
$labels['createnewtask'] = 'Crear nueva Tarea (e.j. Sábado, Cortar el césped)';
$labels['createfrommail'] = 'Guardar como tarea';
$labels['mark'] = 'Marcar';
$labels['unmark'] = 'Desmarcar';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Eliminar';
$labels['title'] = 'Título';
$labels['description'] = 'Descripción';
$labels['datetime'] = 'Debido el';
$labels['start'] = 'Iniciar';
$labels['alarms'] = 'Aviso';
$labels['repeat'] = 'Repetir';
$labels['status'] = 'Estado';
$labels['status-needs-action'] = 'Necesita acción';
$labels['status-in-process'] = 'En proceso';
$labels['status-completed'] = 'Terminado';
$labels['status-cancelled'] = 'Cancelado';
$labels['all'] = 'Todos';
$labels['flagged'] = 'Resaltado';
$labels['complete'] = 'Completado';
$labels['overdue'] = 'Atrasado';
$labels['today'] = 'Hoy';
$labels['tomorrow'] = 'Mañana';
$labels['next7days'] = 'Próximos 7 días';
$labels['later'] = 'Más tarde';
$labels['nodate'] = 'sin fecha';
$labels['removetag'] = 'Eliminar';
$labels['taskdetails'] = 'Detalles';
$labels['edittask'] = 'Editar Tarea';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['addsubtask'] = 'Añadir subtarea';
$labels['deletetask'] = 'Eliminar tarea';
$labels['deletethisonly'] = 'Eliminar sólo esta tarea';
$labels['deletewithchilds'] = 'Eliminar con todas las subtareas';
$labels['tabsummary'] = 'Sumario';
$labels['tabrecurrence'] = 'Recurrencia';
$labels['tabattachments'] = 'Adjuntos';
$labels['tabsharing'] = 'Compartir';
$labels['editlist'] = 'Editar lista';
$labels['createlist'] = 'Añadir lista';
$labels['listactions'] = 'Opciones de lista...';
$labels['listname'] = 'Nombre';
$labels['showalarms'] = 'Mostrar alarmas';
$labels['import'] = 'Importar';
$labels['viewoptions'] = 'Opciones de vista';
$labels['focusview'] = 'Ver sólo esta lista';
$labels['on'] = 'en';
$labels['at'] = 'a';
$labels['this'] = 'este';
$labels['next'] = 'siguiente';
$labels['savingdata'] = 'Guardando datos...';
$labels['errorsaving'] = 'Error al guardar datos.';
$labels['notasksfound'] = 'No se encontraron tareas para los criterios dados';
$labels['subscribe'] = 'Por favor, suscribirse a lista de tarea para poder crear tarea.';
$labels['invalidstartduedates'] = 'Fecha de inicio no debe ser mayor que la fecha de vencimiento.';
$labels['deletetasktconfirm'] = '¿Realmente quiere eliminar esta tarea?';
$labels['deleteparenttasktconfirm'] = '¿Realmente quiere eliminar esta tarea y todas sus subtareas?';
$labels['deletelistconfirm'] = '¿Realmente quiere eliminar esta lista con todas sus tareas?';
$labels['deletelistconfirmrecursive'] = '¿Realmente quiere borrar este lista con todas sus sublistas y tareas?';

?>