<?php

/*
+-----------------------------------------------------------------------+
| language/fi_FI/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['navtitle'] = 'Tehtävät';
$labels['lists'] = 'Tehtävälistat';
$labels['list'] = 'Tehtävälista';
$labels['tags'] = 'Tagit';
$labels['newtask'] = 'Uusi tehtävä';
$labels['createnewtask'] = 'Luo uusi tehtävä (esim. Lauantai, leikkaa nurmikko)';
$labels['createfrommail'] = 'Tallenna tehtävänä';
$labels['mark'] = 'Merkitse';
$labels['unmark'] = 'Poista merkintä';
$labels['edit'] = 'Muokkaa';
$labels['delete'] = 'Poista';
$labels['title'] = 'Otsikko';
$labels['description'] = 'Kuvaus';
$labels['datetime'] = 'Valmistuu';
$labels['start'] = 'Alku';
$labels['alarms'] = 'Muistutus';
$labels['repeat'] = 'Toista';
$labels['status'] = 'Tila';
$labels['status-needs-action'] = 'Tarvitsee toimia';
$labels['status-in-process'] = 'Käynnissä';
$labels['status-completed'] = 'Valmistunut';
$labels['status-cancelled'] = 'Peruutettu';
$labels['all'] = 'Kaikki';
$labels['flagged'] = 'Merkityt';
$labels['complete'] = 'Valmis';
$labels['overdue'] = 'Myöhässä';
$labels['today'] = 'Tänään';
$labels['tomorrow'] = 'Huomenna';
$labels['next7days'] = 'Seuraavat 7 päivää';
$labels['later'] = 'Myöhemmin';
$labels['nodate'] = 'ei päivämäärää';
$labels['removetag'] = 'Poista';
$labels['taskdetails'] = 'Tiedot';
$labels['edittask'] = 'Muokkaa tehtävää';
$labels['save'] = 'Tallenna';
$labels['cancel'] = 'Peruuta';
$labels['addsubtask'] = 'Lisää alatehtävä';
$labels['deletetask'] = 'Poista tehtävä';
$labels['deletethisonly'] = 'Poista vain tämä tehtävä';
$labels['deletewithchilds'] = 'Poista kaikki alitehtävineen';
$labels['tabsummary'] = 'Yhteenveto';
$labels['tabrecurrence'] = 'Toistuminen';
$labels['tabattachments'] = 'Liitteet';
$labels['tabsharing'] = 'Jakaminen';
$labels['editlist'] = 'Muokkaa listaa';
$labels['createlist'] = 'Lisää lista';
$labels['listactions'] = 'Listan vaihtoehdot...';
$labels['listname'] = 'Nimi';
$labels['showalarms'] = 'Näytä hälytykset';
$labels['import'] = 'Tuonti';
$labels['viewoptions'] = 'Näytä vaihtoehdot';
$labels['focusview'] = 'Näytä vain tämä lista';
$labels['this'] = 'tämä';
$labels['next'] = 'seuraava';
$labels['savingdata'] = 'Tallennetaan...';
$labels['errorsaving'] = 'Tallennus epäonnistui.';
$labels['notasksfound'] = 'Tehtäviä ei löytynyt hakukriterialla';
$labels['subscribe'] = 'Tilaa tehtävälista luodaksesi tehtävän.';
$labels['invalidstartduedates'] = 'Alkupäivä ei saa olla suurempi kuin valmistumispäivä.';
$labels['deletetasktconfirm'] = 'Haluatko varmasti poistaa tämän tehtävän?';
$labels['deleteparenttasktconfirm'] = 'Haluatko varmasti poistaa tämän tehtävän alitehtävineen?';
$labels['deletelistconfirm'] = 'Haluatko varmasti poistaa tämän listan tehtävineen?';
$labels['deletelistconfirmrecursive'] = 'Haluatko varmasti poistaa tämän listan, sen alilistat ja tehtävät?';

?>