<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/tasklist/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: intio.nl (info@intio.nl) - 02/19/2015 13:09:46
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['navtitle'] = 'Taken';
$labels['lists'] = 'Takenlijsten';
$labels['list'] = 'Takenlijst';
$labels['tags'] = 'Tags';
$labels['newtask'] = 'Nieuwe Taak';
$labels['createnewtask'] = 'Creer een nieuwe Taak (bijv. Zaterdag, gras maaien)';
$labels['createfrommail'] = 'Als taak opslaan';
$labels['mark'] = 'Markeren';
$labels['unmark'] = 'Demarkeren';
$labels['edit'] = 'Wijzigen';
$labels['delete'] = 'Verwijderen';
$labels['title'] = 'Titel';
$labels['description'] = 'Beschrijving';
$labels['datetime'] = 'Datum/Tijd';
$labels['start'] = 'Begin';
$labels['alarms'] = 'Herinnering';
$labels['repeat'] = 'Herhaal';
$labels['status'] = 'Status';
$labels['status-in-process'] = 'In behandeling';
$labels['status-completed'] = 'Voltooid';
$labels['status-cancelled'] = 'Geannuleerd';
$labels['all'] = 'Alle';
$labels['flagged'] = 'Gemarkeerd';
$labels['complete'] = 'Compleet';
$labels['overdue'] = 'Achterstallig';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['next7days'] = 'Deze week';
$labels['later'] = 'Later';
$labels['nodate'] = 'geen datum';
$labels['removetag'] = 'Verwijder';
$labels['taskdetails'] = 'Details';
$labels['edittask'] = 'Taak Wijzigen';
$labels['save'] = 'Opslaan';
$labels['cancel'] = 'Annuleren';
$labels['addsubtask'] = 'Voeg subtaak toe';
$labels['deletetask'] = 'Verwijder taak';
$labels['deletethisonly'] = 'Verwijder alleen deze taak';
$labels['deletewithchilds'] = 'Verwijder inclusief subtaken';
$labels['tabsummary'] = 'Samenvatting';
$labels['tabrecurrence'] = 'Herhaling';
$labels['tabattachments'] = 'Toebehoren';
$labels['tabsharing'] = 'Delen';
$labels['editlist'] = 'Lijst wijzigen';
$labels['createlist'] = 'Lijst toevoegen';
$labels['listactions'] = 'Lijst opties...';
$labels['listname'] = 'Naam';
$labels['showalarms'] = 'Alarmen tonen';
$labels['import'] = 'Importeren';
$labels['viewoptions'] = 'Bekijk opties';
$labels['focusview'] = 'Bekijk alleen deze lijst';
$labels['on'] = 'op';
$labels['at'] = 'om';
$labels['this'] = 'deze';
$labels['next'] = 'volgende';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['errorsaving'] = 'Fout in opslaan van data.';
$labels['notasksfound'] = 'Geen taken gevonden voor de gegeven criteria';
$labels['invalidstartduedates'] = 'Begin datum kan niet later zijn dan vervaldag.';
$labels['deletetasktconfirm'] = 'Wilt u deze taak echt verwijderen?';
$labels['deleteparenttasktconfirm'] = 'Wilt u deze taak en alle subtaken echt verwijderen?';
$labels['deletelistconfirm'] = 'Wilt u deze lijst met alle taken echt verwijderen?';

?>