<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 07/18/2014 09:59:43
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Vložený Jappix Chat.';
$labels['jappixUsername'] = 'Uživatel';
$labels['usernameinvalid'] = 'Uživatelské jméno obsahuje neplatné znaky';
$labels['domaininvalid'] = 'Doména obsahuje neplatné znaky';
$labels['useminijappix'] = 'Použít Mini Chat';
$labels['usefulljappix'] = 'Použít plnohodnotný Chat';
$labels['minijappixautologon'] = 'Automatizované přihlášení do Mini Chat';
$labels['jappixDomain'] = 'Doména';
$labels['jappixPassword'] = 'Heslo';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Spravovat Chat';
$labels['passwordisset'] = 'Heslo je nastaveno';
$labels['pleaseenterpassword'] = 'Zadejte prosím heslo';
$labels['success'] = 'Úspěšné přihlášení do vašeho účtu Chat... %s přátel online.';
$labels['failure'] = 'Chat je v současnosti nedostupný.';
$labels['requirement'] = 'Potřebujete Chat účet pro připojení k chatu.';
$labels['clickhere'] = 'Klikněte zde';
$labels['registeraccount'] = 'pro registraci vašeho Chat účtu';

?>