<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/10/2014 09:34:05
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Vložený Jappix Chat.';
$labels['jappixUsername'] = 'Uživatel (ponechte prázdné pro zakázání)';
$labels['usernameinvalid'] = 'Uživatelské jméno obsahuje neplatné znaky';
$labels['domaininvalid'] = 'Doména obsahuje neplatné znaky';
$labels['useminijappix'] = 'Použít Mini Jappix';
$labels['minijappixautologon'] = 'Automatizované přihlášení do Mini Jappixu';
$labels['jappixDomain'] = 'Doména';
$labels['jappixPassword'] = 'Heslo';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Spravovat Jappix';
$labels['passwordisset'] = 'Heslo je nastaveno';
$labels['pleaseenterpassword'] = 'Zadejte prosím heslo';
$labels['success'] = 'Úspěšné přihlášení do vašeho účtu XMPP... %s přátel online.';
$labels['failure'] = 'Jappix je v současnosti nedostupný.';

?>