<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 11/25/2013 10:05:15
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Jappix Chat einbinden.';
$labels['jappixUsername'] = 'Benutzer (leer lassen um Jappix zu deaktivieren)';
$labels['usernameinvalid'] = 'Der Benutzername ist ungültig';
$labels['domaininvalid'] = 'Die Domäne ist ungültig';
$labels['useminijappix'] = 'Mini-Jappix benutzen';
$labels['minijappixautologon'] = 'Mini-Jappix automatische Anmeldung';
$labels['jappixDomain'] = 'Domain';
$labels['jappixPassword'] = 'Passwort';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Jappix konfigurieren';
$labels['passwordisset'] = 'Passwort ist gespeichert';
$labels['pleaseenterpassword'] = 'Bitte Passwort eingeben';
$labels['success'] = 'Erfolgreiche Jappix-Anmeldung ... %s Freund(e) online.';
$labels['failure'] = 'Jappix steht zur Zeit nicht zur Verfügung';

?>