<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 09/15/2013 15:34:53
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Embed Jappix Chat.';
$labels['jappixUsername'] = 'User (leave empty to disable)';
$labels['usernameinvalid'] = 'Username contains invalid characters';
$labels['domaininvalid'] = 'Domain contains invalid characters';
$labels['useminijappix'] = 'Use Mini Jappix';
$labels['minijappixautologon'] = 'Mini Jappix automated login';
$labels['jappixDomain'] = 'Domain';
$labels['jappixPassword'] = 'Password';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Manage Jappix';
$labels['passwordisset'] = 'Password is set';
$labels['pleaseenterpassword'] = 'Please enter password';
$labels['success'] = 'Successful login into your XMPP account... %s friend(s) online.';
$labels['failure'] = 'Jappix is currently not available';

?>