<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 07/12/2014 11:02:13
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Jappix Chat Integrado.';
$labels['jappixUsername'] = 'Usuario (dejar en blanco para desactivar)';
$labels['usernameinvalid'] = 'El nombre de usuario contiene caracteres inválidos';
$labels['domaininvalid'] = 'Dominio contiene caracteres inválidos';
$labels['useminijappix'] = 'Usar el Mini Chat minimizado';
$labels['minijappixautologon'] = 'Iniciar sesión de Mini Chat automáticamente';
$labels['jappixDomain'] = 'Dominio';
$labels['jappixPassword'] = 'Contraseña';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Administrar Chat';
$labels['passwordisset'] = 'Contraseña establecida';
$labels['pleaseenterpassword'] = 'Por favor, introduzca la contraseña';
$labels['success'] = 'Conexión exitosa a su cuenta Chat... %s amigo(s) en línea.';
$labels['failure'] = 'Chat no está actualmente disponible';

?>