<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 17:47:39
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Jappix Chat Integrado.';
$labels['jappixUsername'] = 'Usuario';
$labels['usernameinvalid'] = 'El nombre de usuario contiene caracteres inválidos';
$labels['domaininvalid'] = 'Dominio contiene caracteres inválidos';
$labels['useminijappix'] = 'Usar el Mini Chat minimizado';
$labels['usefulljappix'] = 'Utilizar el chat con todas las funciones';
$labels['minijappixautologon'] = 'Iniciar sesión de Mini Chat automáticamente';
$labels['jappixDomain'] = 'Dominio';
$labels['jappixPassword'] = 'Contraseña';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Administrar Chat';
$labels['passwordisset'] = 'Contraseña establecida';
$labels['pleaseenterpassword'] = 'Por favor, introduzca la contraseña';
$labels['success'] = 'Conexión exitosa a su cuenta Chat... %s amigo(s) en línea.';
$labels['failure'] = 'Chat no está actualmente disponible';
$labels['requirement'] = 'Necesita una cuenta de chat para conectarse a una charla.';
$labels['clickhere'] = 'Haga clic aquí';
$labels['registeraccount'] = 'para registrar su cuenta de Chat';

?>