<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 09/20/2013 17:36:29
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Intégrer Jappix Chat';
$labels['jappixUsername'] = 'Utilisateur (laisser vide pour d&eacute;sactiver)';
$labels['useminijappix'] = 'Utiliser Mini Jappix';
$labels['minijappixautologon'] = 'Login automatique Mini Jappix ';
$labels['jappixDomain'] = 'Domaine';
$labels['jappixPassword'] = 'Mot de passe';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Configuration de Jappix';
$labels['passwordisset'] = 'Le mot de passe est défini';
$labels['pleaseenterpassword'] = 'Veuillez introduire un mot de passe';
$labels['success'] = 'Vous êtes correctement connecté à votre compte XMPP.... %s ami(s) sont en ligne';
$labels['failure'] = 'Jappix n\'est actuellement pas disponible';

?>