<?php

/*
+-----------------------------------------------------------------------+
| language/fr_FR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Olivier Zolli - 01/11/2015                                    |
+-----------------------------------------------------------------------+

*/

$labels['alarmemail'] = 'Envoyer un email';
$labels['until'] = 'jusqu\'à';
$labels['at'] = 'à';
$labels['alarmemail'] = 'Envoyer un email';
$labels['alarmdisplay'] = 'Voir le message';
$labels['alarmaudio'] = 'Lire son';
$labels['alarmdisplayoption'] = 'Message';
$labels['alarmemailoption'] = 'Email';
$labels['alarmaudiooption'] = 'Son';
$labels['alarmat'] = 'à $datetime';
$labels['trigger@'] = 'à la date';
$labels['trigger-M'] = 'minutes avant';
$labels['trigger-H'] = 'heures avant';
$labels['trigger-D'] = 'jours avant';
$labels['trigger+M'] = 'minutes après';
$labels['trigger+H'] = 'heures après';
$labels['trigger+D'] = 'jours après';
$labels['triggerattime'] = 'à l\'heure';
$labels['addalarm'] = 'Ajouter alarme';
$labels['removealarm'] = 'Supprimer alarme';
$labels['alarmtitle'] = 'Evénements à venir';
$labels['dismissall'] = 'Tout supprimer';
$labels['dismiss'] = 'Abandonner';
$labels['snooze'] = 'En pause';
$labels['repeatinmin'] = 'Répéter dans $min minutes';
$labels['repeatinhr'] = 'Répéter dans 1 heure';
$labels['repeatinhrs'] = 'Répéter dans $hrs heures';
$labels['repeattomorrow'] = 'Répéter demain';
$labels['repeatinweek'] = 'Répéter dans une semaine';
$labels['showmore'] = 'Afficher plus...';
$labels['frequency'] = 'Répéter';
$labels['never'] = 'Jamais';
$labels['daily'] = 'Quotidienne';
$labels['weekly'] = 'Hebdomadaire';
$labels['monthly'] = 'Mensuelle';
$labels['yearly'] = 'Annuelle';
$labels['rdate'] = 'Dates spécifiées';
$labels['every'] = 'Tous les';
$labels['days'] = 'jour(s)';
$labels['weeks'] = 'semaine(s)';
$labels['months'] = 'mois';
$labels['years'] = 'année(s) en :';
$labels['bydays'] = 'Le';
$labels['untildate'] = 'le';
$labels['each'] = 'Chaque';
$labels['onevery'] = 'Tous les';
$labels['onsamedate'] = 'à la même date';
$labels['forever'] = 'Pour toujours';
$labels['recurrencend'] = 'Jusqu\'à';
$labels['untilenddate'] = 'jusqu\'à cette date';
$labels['forntimes'] = '$nr fois';
$labels['first'] = 'premier';
$labels['second'] = 'deuxième';
$labels['third'] = 'troisième';
$labels['fourth'] = 'quatrième';
$labels['last'] = 'dernier';
$labels['dayofmonth'] = 'Jour du mois';
$labels['addrdate'] = 'Ajouter date';
$labels['itipinvitation'] = 'Invitation à';
$labels['itipupdate'] = 'Mise à jour de';
$labels['itipcancellation'] = 'Annulation:';
$labels['itipreply'] = 'Répondre à';
$labels['itipaccepted'] = 'Accepter';
$labels['itiptentative'] = 'Peut-être';
$labels['itipdeclined'] = 'Refuser';
$labels['itipdelegated'] = 'Déléguer';
$labels['itipneeds-action'] = 'Reporter';
$labels['itipcomment'] = 'Votre réponse';
$labels['itipeditresponse'] = 'Entrez un texte de réponse';
$labels['itipsendercomment'] = 'Commentaire de l\'expéditeur';
$labels['itipsuppressreply'] = 'Ne pas envoyer de réponse';
$labels['itipobjectnotfound'] = 'L\'objet référencé par ce message n\'a pas été trouvé dans votre compte.';
$labels['itipsubjectaccepted'] = '"$title" a été accepté par $name';
$labels['itipsubjecttentative'] = '"$title" a été accepté sans certitude par $name';
$labels['itipsubjectdeclined'] = '"$title" a été décliné par $name';
$labels['itipsubjectcancel'] = 'Votre participation à "$title" a été annulée';
$labels['itipnewattendee'] = 'C\'est la réponse d\'un nouveau participant';
$labels['updateattendeestatus'] = 'Modifier le statut des participants';
$labels['acceptinvitation'] = 'Acceptez-vous cette invitation?';
$labels['acceptattendee'] = 'Accepter le participant';
$labels['declineattendee'] = 'Décliner le participant';
$labels['declineattendeeconfirm'] = 'Entrer un message pour le participant décliné (optionnel) :';
$labels['youhaveaccepted'] = 'Vous avez accepté cette invitation';
$labels['youhavetentative'] = 'Vous avez accepté cette invitation sans certitude';
$labels['youhavedeclined'] = 'Vous avez refusé cette invitation';
$labels['youhavedelegated'] = 'Vous avez délégué cette invitation';
$labels['youhaveneeds-action'] = 'Vous n\'avez toujours pas répondu à cette invitation';
$labels['youhavepreviouslyaccepted'] = 'Vous avez précédemment accepté cette invitation';
$labels['youhavepreviouslytentative'] = 'Vous avez précédemment accepté cette invitation sans certitude';
$labels['youhavepreviouslydeclined'] = 'Vous avez précédemment décliné cette invitation';
$labels['youhavepreviouslydelegated'] = 'Vous avez précédemment délégué cette invitation';
$labels['youhavepreviouslyneeds-action'] = 'Vous n\'avez toujours pas répondu à cette invitation';
$labels['attendeeaccepted'] = 'Le participant a accepté';
$labels['attendeetentative'] = 'Le participant a accepté sans certitude';
$labels['attendeedeclined'] = 'Le participant a décliné';
$labels['attendeedelegated'] = 'Le participant a délégué $delegatedto';
$labels['notanattendee'] = 'Vous n\'êtes pas dans la liste des participants à cet évènement';
$labels['outdatedinvitation'] = 'Cette invitation a été remplacée par une nouvelle version';
$labels['importtocalendar'] = 'Enregistrer dans mon agenda';
$labels['removefromcalendar'] = 'Supprimer de mon agenda';
$labels['updatemycopy'] = 'Mettre à jour ma copie';
$labels['deleteobjectconfirm'] = 'Voulez-vous vraiment supprimer cet objet ?';
$labels['declinedeleteconfirm'] = 'Voulez-vous également supprimer cet objet décliné dans votre agenda ?';
$labels['savingdata'] = 'Enregistrement en cours...';
$labels['event'] = 'évènement';
$labels['task'] = 'tâche';
$labels['changeobjectconfirm'] = 'Modifier %s';
$labels['removeobjectconfirm'] = 'Supprimer %s';
$labels['changerecurringobjectwarning'] = 'Objet %s récurrent. Voulez-vous seulement éditer l\'objet %s courant, celui-ci et toutes les occurrences futures ou toutes les occurrences ?';
$labels['removerecurringobjectwarning'] = 'Objet %s récurrent. Voulez-vous seulement supprimer l\'objet %s courant, celui-ci et toutes les occurrences futures ou toutes les occurrences ?';
$labels['removerecurringtaskwarning'] = 'Tâche réccurrente. Voulez-vous supprimer la tâche courante ou toutes les occurrences ?';
$labels['currentobject'] = 'Courant';
$labels['futureobjects'] = 'Futur';
$labels['allobjects'] = 'Tous';
$labels['deletealltasks'] = 'Supprimer toutes les occurrences';
$labels['deletealltaskswithchilds'] = 'Supprimer toutes les occurrences et toutes les sous-tâches';
$labels['saveasnew'] = 'Sauvegarder comme nouveau';

?>