<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/imap_hooks/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 07/06/2014 16:26:22
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Hilfserweiterung zur Implementierung weiterer Hooks';
$labels['plugindescription'] = 'Hilfserweiterung zur Implementierung weiterer Hooks.';

?>