<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/imap_hooks/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 07/06/2014 16:26:31
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Helper plugin to implement additional hooks';
$labels['plugindescription'] = 'A helper plugin to implement additional hooks.';

?>