<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/imap_hooks/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 17:45:59
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Complemento Auxiliar para implementar ganchos adicionales';
$labels['plugindescription'] = 'Un complemento auxiliar para implementar códigos adicionales para características específicas.';

?>