rmdir trunk\plugins\compressor\skins\litecube-f /s/q
rmdir trunk\plugins\compressor\skins\meh /s/q
rmdir trunk\plugins\compressor\skins\groupvice4 /s/q
rmdir trunk\plugins\message_highlight\skins\groupvice4 /s/q
rmdir trunk\plugins\message_highlight\skins\meh /s/q
rmdir trunk\plugins\webmail_notifier\skins\litecube-f /s/q
rmdir trunk\plugins\compose_newwindow\skins\meh /s/q
rmdir trunk\plugins\impressum\skins\meh /s/q
rmdir trunk\plugins\rss_feeds\skins\meh /s/q
rmdir trunk\plugins\wrapper\skins\meh /s/q
rmdir trunk\plugins\plugin_manager\skins\meh /s/q
rmdir trunk\plugins\accounts\skins\meh /s/q
rmdir trunk\plugins\archivefolder\skins\meh /s/q
rmdir trunk\plugins\moreuserinfo\skins\meh /s/q
rmdir trunk\plugins\plugin_manager\skins\meh /s/q
rmdir trunk\plugins\calendar\skins\meh /s/q
rmdir trunk\plugins\captcha\skins\meh /s/q
rmdir trunk\plugins\google_ads\skins\meh /s/q
rmdir trunk\plugins\listcontrols\skins\meh /s/q
rmdir trunk\plugins\nabble\skins\meh /s/q
rmdir trunk\plugins\planner\skins\meh /s/q
rmdir trunk\plugins\pwtools\skins\meh /s/q
rmdir trunk\plugins\register\skins\meh /s/q
rmdir trunk\plugins\compose_in_taskbar\skins\meh /s/q
rmdir trunk\plugins\compose_newwindow\skins\litecube-f /s/q
rmdir trunk\plugins\impressum\skins\litecube-f /s/q
rmdir trunk\plugins\rss_feeds\skins\litecube-f /s/q
rmdir trunk\plugins\wrapper\skins\litecube-f /s/q
rmdir trunk\plugins\contactus\skins\meh /s/q
rmdir trunk\plugins\scheduled_sending\skins\meh /s/q
rmdir trunk\plugins\settings\skins\meh /s/q
rmdir trunk\plugins\taskbar\skins\meh /s/q
rmdir trunk\plugins\sticky_notes\skins\meh /s/q
rmdir trunk\plugins\summary\skins\meh /s/q
rmdir trunk\plugins\template_objects\skins\meh /s/q
rmdir trunk\plugins\terms\skins\meh /s/q
rmdir trunk\plugins\vkeyboard\skins\meh /s/q
rmdir trunk\plugins\compose_newwindow\skins\groupvice4 /s/q
rmdir trunk\plugins\impressum\skins\groupvice4 /s/q
rmdir trunk\plugins\rss_feeds\skins\groupvice4 /s/q
rmdir trunk\plugins\wrapper\skins\groupvice4 /s/q
rmdir trunk\plugins\plugin_manager\skins\groupvice4 /s/q
rmdir trunk\plugins\accounts\skins\groupvice4 /s/q
rmdir trunk\plugins\archivefolder\skins\groupvice4 /s/q
rmdir trunk\plugins\moreuserinfo\skins\groupvice4 /s/q
rmdir trunk\plugins\plugin_manager\skins\groupvice4 /s/q
rmdir trunk\plugins\calendar\skins\groupvice4 /s/q
rmdir trunk\plugins\captcha\skins\groupvice4 /s/q
rmdir trunk\plugins\google_ads\skins\groupvice4 /s/q
rmdir trunk\plugins\listcontrols\skins\groupvice4 /s/q
rmdir trunk\plugins\nabble\skins\groupvice4 /s/q
rmdir trunk\plugins\planner\skins\groupvice4 /s/q
rmdir trunk\plugins\pwtools\skins\groupvice4 /s/q
rmdir trunk\plugins\register\skins\groupvice4 /s/q
rmdir trunk\plugins\compose_in_taskbar\skins\groupvice4 /s/q
rmdir trunk\plugins\contactus\skins\groupvice4 /s/q
rmdir trunk\plugins\scheduled_sending\skins\groupvice4 /s/q
rmdir trunk\plugins\settings\skins\groupvice4 /s/q
rmdir trunk\plugins\taskbar\skins\groupvice4 /s/q
rmdir trunk\plugins\sticky_notes\skins\groupvice4 /s/q
rmdir trunk\plugins\summary\skins\groupvice4 /s/q
rmdir trunk\plugins\template_objects\skins\groupvice4 /s/q
rmdir trunk\plugins\terms\skins\groupvice4 /s/q
rmdir trunk\plugins\vkeyboard\skins\groupvice4 /s/q
rmdir trunk\plugins\impressum\skins\litecube-f /s/q
rmdir trunk\plugins\plugin_manager\skins\litecube-f /s/q
rmdir trunk\plugins\accounts\skins\litecube-f /s/q
rmdir trunk\plugins\archivefolder\skins\litecube-f /s/q
rmdir trunk\plugins\moreuserinfo\skins\litecube-f /s/q
rmdir trunk\plugins\plugin_manager\skins\litecube-f /s/q
rmdir trunk\plugins\calendar\skins\litecube-f /s/q
rmdir trunk\plugins\captcha\skins\litecube-f /s/q
rmdir trunk\plugins\google_ads\skins\litecube-f /s/q
rmdir trunk\plugins\listcontrols\skins\litecube-f /s/q
rmdir trunk\plugins\nabble\skins\litecube-f /s/q
rmdir trunk\plugins\planner\skins\litecube-f /s/q
rmdir trunk\plugins\pwtools\skins\litecube-f /s/q
rmdir trunk\plugins\register\skins\litecube-f /s/q
rmdir trunk\plugins\compose_in_taskbar\skins\litecube-f /s/q
rmdir trunk\plugins\contactus\skins\litecube-f /s/q
rmdir trunk\plugins\scheduled_sending\skins\litecube-f /s/q
rmdir trunk\plugins\settings\skins\litecube-f /s/q
rmdir trunk\plugins\taskbar\skins\litecube-f /s/q
rmdir trunk\plugins\sticky_notes\skins\litecube-f /s/q
rmdir trunk\plugins\summary\skins\litecube-f /s/q
rmdir trunk\plugins\template_objects\skins\litecube-f /s/q
rmdir trunk\plugins\terms\skins\litecube-f /s/q
rmdir trunk\plugins\vkeyboard\skins\litecube-f /s/q
rmdir trunk\plugins\webmail_notfier\skins\litecube-f /s/q
rmdir trunk\plugins\idle_timeout\skins\litecube-f /s/q