del trunk\plugins\UPDATE
rmdir trunk\plugins\limit_skins /s/q
rmdir trunk\plugins\login_info /s/q
rmdir trunk\plugins\custom_login_logout /s/q
rmdir trunk\plugins\sabredav_migrate /s/q
rmdir trunk\plugins\hmail_roundcube_sync /s/q
rmdir trunk\plugins\hmail_sabredav_sync /s/q
rmdir trunk\plugins\dkimstatus /s/q
rmdir trunk\plugins\hmail_search /s/q
rmdir trunk\plugins\imap_threads /s/q
rmdir trunk\plugins\cookie_config /s/q
rmdir trunk\plugins\remove_attachments /s/q
rmdir trunk\plugins\attachment_reminder /s/q
rmdir trunk\plugins\identity_select /s/q
rmdir trunk\plugins\mysqladmin /s/q
rmdir trunk\plugins\hmail_publicfolder /s/q
rmdir trunk\plugins\google_oauth2 /s/q
rmdir trunk\plugins\vcard_send /s/q
rmdir trunk\plugins\helpui /s/q
rmdir trunk\plugins\tabbed /s/q
rmdir trunk\plugins\jsdialogs /s/q
rmdir trunk\plugins\filters /s/q
rmdir trunk\plugins\companyaddressbook /s/q
rmdir trunk\plugins\compose_myroundcube /s/q
rmdir trunk\plugins\db_config /s/q
rmdir trunk\plugins\tasklist /s/q
rmdir trunk\plugins\libcalendaring /s/q
rmdir trunk\plugins\rc_identity /s/q
rmdir trunk\plugins\regkey /s/q
rmdir trunk\plugins\package_xml /s/q
rmdir trunk\plugins\save_in_same_folder /s/q
rmdir trunk\plugins\load_splitter /s/q
rmdir trunk\plugins\db_version /s/q
rmdir trunk\plugins\identities_smtp /s/q
rmdir trunk\plugins\identities_imap /s/q
rmdir trunk\plugins\compose_extwin /s/q
rmdir trunk\plugins\disclaimer /s/q
rmdir trunk\plugins\checkbox /s/q
rmdir trunk\plugins\hmail_pop3 /s/q
rmdir trunk\plugins\hmail_rules /s/q
rmdir trunk\plugins\plugin_manager /s/q
rmdir trunk\plugins\msglistcols /s/q
rmdir trunk\plugins\listcontrols /s/q
rmdir trunk\plugins\calendar_plus /s/q
rmdir trunk\plugins\carddav_plus /s/q
rmdir trunk\plugins\global_config /s/q
rmdir trunk\plugins\google_ads /s/q
rmdir trunk\plugins\summary /s/q
rmdir trunk\plugins\compose_in_taskbar /s/q
rmdir trunk\plugins\detach_attachments /s/q
rmdir trunk\plugins\scheduled_sending /s/q
rmdir trunk\plugins\vcard_attach /s/q
rmdir trunk\plugins\hmail_autoresponder /s/q
rmdir trunk\plugins\hmail_forwarding /s/q
rmdir trunk\plugins\hmail_signature /s/q
rmdir trunk\plugins\accounts /s/q
rmdir trunk\plugins\plaxo_contacts /s/q
rmdir trunk\plugins\sticky_notes /s/q
rmdir trunk\plugins\embed_images /s/q
rmdir trunk\plugins\hmail_password /s/q
rmdir trunk\plugins\hmail_spamfilter /s/q
rmdir trunk\plugins\pwtools /s/q
rmdir trunk\plugins\idle_timeout /s/q
rmdir trunk\plugins\nabble /s/q
rmdir trunk\plugins\rss_feeds /s/q
rmdir trunk\plugins\wrapper /s/q
rmdir trunk\plugins\sabredav /s/q
rmdir trunk\plugins\demologin /s/q
rmdir trunk\plugins\terms /s/q
rmdir trunk\plugins\register /s/q
rmdir trunk\plugins\lang_sel /s/q
rmdir trunk\plugins\placeholder /s/q
rmdir trunk\plugins\domain_check /s/q
rmdir trunk\plugins\newuser /s/q
rmdir trunk\plugins\dnsbl /s/q
rmdir trunk\plugins\taskbar /s/q
rmdir trunk\plugins\impressum /s/q
rmdir trunk\plugins\contactus /s/q
rmdir trunk\plugins\crawler /s/q
rmdir trunk\plugins\checked_identities /s/q
rmdir trunk\plugins\impersonate /s/q
rmdir trunk\plugins\hmail_login /s/q
rmdir trunk\plugins\hmail_autoban /s/q
rmdir trunk\plugins\blockspamsending /s/q
rmdir trunk\plugins\global_alias /s/q
rmdir trunk\plugins\dblog /s/q
rmdir trunk\plugins\hide_blockquote /s/q
rmdir trunk\plugins\skin_sel /s/q
rmdir trunk\plugins\template_objects /s/q
rmdir trunk\plugins\fixTHEAD /s/q
rmdir trunk\plugins\joomla /s/q
rmdir trunk\plugins\limit_recipients /s/q
rmdir trunk\plugins\login_redirect /s/q
rmdir trunk\plugins\logout_redirect /s/q
rmdir trunk\plugins\mobile_skin_selector /s/q
rmdir trunk\plugins\billing /s/q
rmdir trunk\plugins\correo /s/q
rmdir trunk\plugins\tinymce_backend /s/q
rmdir trunk\plugins\tinymce\cache /s/q
mkdir trunk\plugins\tinymce\cache
rmdir trunk\plugins\compressor /s/q
rmdir trunk\plugins\remember_skin /s/q
rmdir trunk\plugins\remember_splitter /s/q
rmdir trunk\plugins\browser_info /s/q
rmdir trunk\plugins\drag_upload /s/q
rmdir trunk\plugins\plugin_server /s/q
rmdir trunk\plugins\forwardattachment /s/q
rmdir trunk\plugins\session_timeout /s/q
rmdir trunk\plugins\remember_me /s/q
rmdir trunk\plugins\prototype /s/q
rmdir trunk\plugins\message_sent /s/q
rmdir trunk\plugins\jqueryui /s/q
rmdir trunk\plugins\google_contacts /s/q
rmdir trunk\plugins\markbuttons /s/q
rmdir trunk\plugins\redundant_attachments /s/q
rmdir trunk\plugins\dirtyfixes /s/q
rmdir trunk\plugins\acl /s/q
rmdir trunk\plugins\newmail_notifier /s/q
rmdir trunk\plugins\sound_notifier /s/q
rmdir trunk\plugins\vlogin /s/q
rmdir trunk\plugins\select_text_to_quote /s/q
rmdir trunk\plugins\flags /s/q
rmdir trunk\plugins\problem /s/q
rmdir trunk\plugins\hmail_fixes /s/q
rmdir trunk\plugins\saveinsamefolder /s/q
rmdir trunk\plugins\automatic_addressbook /s/q
rmdir trunk\plugins\recipient_to_contact /s/q
rmdir trunk\plugins\chbox /s/q
rmdir trunk\plugins\kolab_core /s/q
rmdir trunk\plugins\help_ui /s/q
rmdir trunk\plugins\kolab_addressbook /s/q
rmdir trunk\plugins\abook_sync /s/q
rmdir trunk\plugins\calendar_sav /s/q
rmdir trunk\plugins\rcguard /s/q
rmdir trunk\plugins\enigma /s/q
rmdir trunk\plugins\importmessages /s/q
rmdir trunk\plugins\google_analytics /s/q
#rmdir trunk\plugins\message_highlight /s/q
rmdir trunk\plugins\sendmessage /s/q
rmdir trunk\plugins\keyboard_shortcuts /s/q
rmdir trunk\plugins\additional_message_headers /s/q
rmdir trunk\plugins\globaladdressbook /s/q
rmdir trunk\plugins\copymessage /s/q
rmdir trunk\plugins\archive /s/q
rmdir trunk\plugins\autologon /s/q
rmdir trunk\plugins\zipdownload /s/q
rmdir trunk\plugins\virtuser_query /s/q
rmdir trunk\plugins\virtuser_file /s/q
rmdir trunk\plugins\listcommands /s/q
rmdir trunk\plugins\contextmenu /s/q
rmdir trunk\plugins\admin_api /s/q
rmdir trunk\plugins\admin_inspect /s/q
rmdir trunk\plugins\admin_logs /s/q
rmdir trunk\plugins\markasjunk2 /s/q
rmdir trunk\plugins\searchbox /s/q
rmdir trunk\plugins\compose_addressbook /s/q
rmdir trunk\plugins\force_https /s/q 
rmdir trunk\plugins\additional_message_headers /s/q 
rmdir trunk\plugins\autologon /s/q 
rmdir trunk\plugins\database_attachments /s/q 
rmdir trunk\plugins\debug_logger /s/q 
rmdir trunk\plugins\emoticons /s/q 
rmdir trunk\plugins\example_addressbook /s/q 
rmdir trunk\plugins\filesystem_attachments /s/q 
rmdir trunk\plugins\help /s/q 
rmdir trunk\plugins\http_authentication /s/q 
rmdir trunk\plugins\managesieve /s/q 
rmdir trunk\plugins\markasjunk /s/q 
rmdir trunk\plugins\new_user_dialog /s/q 
rmdir trunk\plugins\new_user_identity /s/q 
rmdir trunk\plugins\password /s/q 
rmdir trunk\plugins\show_additional_headers /s/q 
rmdir trunk\plugins\squirrelmail_usercopy /s/q 
rmdir trunk\plugins\subscriptions_option /s/q 
rmdir trunk\plugins\userinfo /s/q 
rmdir trunk\vcard_attachments /s/q
rmdir trunk\plugins\captcha\temp /s/q
mkdir trunk\plugins\captcha\temp
rmdir trunk\plugins\compose_attach /s/q
rmdir trunk\plugins\vcard_attachments /s/q
rmdir trunk\plugins\detach_attachments\dl /s/q
del trunk\plugins\.htaccess
del trunk\plugins\robots.txt
del trunk\plugins\dblog\config.inc.php
del trunk\plugins\request_saver\config\mode.php
del trunk\plugins\terms\localization\en_US_terms.html
del trunk\plugins\register\drivers\hmail_sql_db_5320\config.inc.php
del trunk\plugins\register\drivers\hmail_sql_db_5310\config.inc.php
del trunk\plugins\register\drivers\hmail_sql_db_5201\config.inc.php
del trunk\plugins\register\drivers\hmail_sql_db_5400\config.inc.php
del trunk\plugins\register\drivers\cpanel\config.inc.php
del trunk\plugins\register\drivers\cpanel-xmlapi\config.inc.php
del trunk\plugins\global_config\config.inc.php