<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/jappix4roundcube/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 07/12/2014 11:02:29
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Jappix Chat';
$labels['plugindescription'] = 'Embed Jappix Chat.';
$labels['jappixUsername'] = 'User (leave empty to disable)';
$labels['usernameinvalid'] = 'Username contains invalid characters';
$labels['domaininvalid'] = 'Domain contains invalid characters';
$labels['useminijappix'] = 'Use Mini Chat minimized';
$labels['usefulljappix'] = 'Use full featured Chat';
$labels['minijappixautologon'] = 'Mini Chat automatic login';
$labels['jappixDomain'] = 'Domain';
$labels['jappixPassword'] = 'Password';
$labels['jappixSection'] = 'Chat';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Manage Chat';
$labels['passwordisset'] = 'Password is set';
$labels['pleaseenterpassword'] = 'Please enter password';
$labels['success'] = 'Successful login into your Chat account... %s friend(s) online.';
$labels['failure'] = 'Chat is currently not available';
$labels['requirement'] = 'You need a Chat account to connect to a chat.';
$labels['clickhere'] = 'Click here';
$labels['registeraccount'] = 'to register your Chat account';

?>