<?php

/*
+-----------------------------------------------------------------------+
| language/_NEW_/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Меню';
$labels['managefolders'] = 'Управление на папки';
$labels['account'] = 'Администриране на профила';
$labels['classic'] = 'По подразбиране';
$labels['remotefolders'] = 'Специални папки';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Преглед на изгледа';

?>