<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/09/2014 10:03:53
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Nastavení';
$labels['plugindescription'] = 'Toto je pomocný doplněk. Je využíván několika dalšími doplňky (např. všemi  hmail_* doplňky).';
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Správa složek';
$labels['account'] = 'Administrace účtu';
$labels['classic'] = 'Výchozí';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Speciální složky';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Náhled vzhledu';

?>