<?php

$labels=array();
$labels['pluginname']='Indstilling';
$labels['menu']='Menu';
$labels['managefolders']='Håndtere foldere';
$labels['account']='Administration af konto';
$labels['classic']='Standard';
$labels['groupvice4']='Gruppemæssig';
$labels['remotefolders']='Specielle foldere';
$labels['myroundcube']='Min RoundCube Webmail';
$labels['skin_preview']='Forhåndsvisning af brugerflade';
$labels['meh']='MEH';
$labels['litecube-f']='Simpel brugerflade (gratis)';
$labels['litecube']='Simpel brugerflade';
$labels['litecube_mobile']='Mobil brugerflade';
$labels['larry']='Larry';

?>