<?php

$labels=array();
$labels['pluginname']='Indstilling';
$labels['menu']='Menu';
$labels['managefolders']='Håndtere foldere';
$labels['account']='Administration af konto';
$labels['classic']='Standard';
$labels['remotefolders']='Specielle foldere';
$labels['myroundcube']='Min RoundCube Webmail';
$labels['skin_preview']='Forhåndsvisning af brugerflade';
$labels['larry']='Larry';

?>