<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:06:21
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['menu'] = 'Menue';
$labels['managefolders'] = 'Ordner verwalten';
$labels['account'] = 'Konto-Einstellungen';
$labels['classic'] = 'Standard';
$labels['remotefolders'] = 'Spezialordner';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Vorschau Benutzerobfläche';

?>