<?php

$labels = array();
$labels['pluginname'] = 'Einstellungen';
$labels['plugindescription'] = 'Diese Hilfserweiterung wird von einigen anderen Erweiterungen benötigt (z.B. alle hmail_* Erweiterungen).';
$labels['menu'] = 'Menü';
$labels['managefolders'] = 'Ordner verwalten';
$labels['account'] = 'Konto-Einstellungen';
$labels['classic'] = 'Standard';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Spezialordner';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Vorschau Benutzerobfläche';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite';

?>