<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:35:29
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Manage Folders';
$labels['account'] = 'Account Administration';
$labels['classic'] = 'Default';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Special Folders';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Skin Preview';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite';

?>