<?php

$labels = array();
$labels['pluginname'] = 'Settings';
$labels['plugindescription'] = 'This is a helper plugin. It is required of several other plugins (f.e. all hmail_* plugins).';
$labels['menu']  = 'Menu';
$labels['managefolders']  = 'Manage Folders';
$labels['account'] = 'Account Administration';
$labels['classic'] = 'Default';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Special Folders';
$labels['myroundcube'] = 'MyRoundCube';

?>