<?php

$labels = array();
$labels['pluginname'] = 'Settings';
$labels['plugindescription'] = 'This is a helper plugin. It is required of several other plugins (f.e. all hmail_* plugins).';
$labels['menu']  = 'Menu';
$labels['managefolders']  = 'Manage Folders';
$labels['account'] = 'Account Administration';
$labels['classic'] = 'Default';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Special Folders';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Skin Preview';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite (free)';
$labels['litecube'] = 'Lite';
$labels['litecube_mobile'] = 'Mobile';
$labels['larry'] = 'Larry';

?>