<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 11/27/2012 05:52:07
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Configuración';
$labels['plugindescription'] = 'Este es un complemento de ayuda. Es requerido por otros complemento (p.e. todos los complementos hmail_* ).';
$labels['menu'] = 'Menú';
$labels['managefolders'] = 'Administrar carpetas';
$labels['account'] = 'Administrar cuentas';
$labels['classic'] = 'Por defecto';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Carpetas especiales';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Previsualizar tema';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite';
$labels['litecube'] = 'Lite';
$labels['litecube_mobile'] = 'Mobil';
$labels['larry'] = 'Larry';

?>