<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/22/2013 04:36:16
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Configuración';
$labels['plugindescription'] = 'Este es un complemento de ayuda. Es requerido por otros complemento (p.e. todos los complementos hmail_* ).';
$labels['menu'] = 'Menú';
$labels['managefolders'] = 'Administrar carpetas';
$labels['account'] = 'Administrar cuentas';
$labels['classic'] = 'Por defecto';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Carpetas especiales';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Previsualizar tema';

?>