<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 12/11/2012 12:10:07
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Paramètres';
$labels['plugindescription'] = 'Ce plugin est nécessaire pour le bon fonctionnement d\'autres plugin (par exmple tous les hmail* plugins)';
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Gestion des dossiers';
$labels['account'] = 'Administration du compte';
$labels['classic'] = 'Default';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Dossiers spéciaux';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Prévisualisation de l\'apparence';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite';
$labels['litecube'] = 'Lite';
$labels['litecube_mobile'] = 'Mobile';
$labels['larry'] = 'Larry';

?>