<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: hugues@mail4us.net - 08/09/2012 22:49:06
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Gestion des dossiers';
$labels['account'] = 'Administration du compte';
$labels['classic'] = 'Default';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Dossiers spéciaux';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Prévisualisation de l\'apparence';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite';
$labels['litecube'] = 'Lite';
$labels['litecube_mobile'] = 'Mobile';
$labels['larry'] = 'Larry';

?>