<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/hu_HU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Mihaly Vukovics - 09/18/2013 13:29:57
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Beállítás';
$labels['plugindescription'] = 'Ez egy segés beépűlő, Több egyéb beépülőmodul  igényelheti';
$labels['menu'] = 'Menü';
$labels['managefolders'] = 'Mappák kezelése';
$labels['account'] = 'Fiók kezelése';
$labels['classic'] = 'Alapértelmezett';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Speciális mappák';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Téma előnézet';

?>