<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Menü';
$labels['managefolders'] = 'Mappák kezelése';
$labels['account'] = 'Fiók kezelése';
$labels['classic'] = 'Alapértelmezett';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Speciális mappák';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Téma előnézet';

?>