<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Matteo Bonora <develop@matteobonora.it>                       |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Menù';
$labels['managefolders'] = 'Gestisci Cartelle';
$labels['account'] = 'Amministrazione Account';
$labels['classic'] = 'Predefinito';
$labels['remotefolders'] = 'Cartelle Speciali';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Anteprima Skin';

?>