<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: HiJack! - 10/22/2012 20:03:26
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Mappen beheren';
$labels['account'] = 'Accountbeheer';
$labels['classic'] = 'Standaard';
$labels['groupvice4'] = 'Groupvice';
$labels['remotefolders'] = 'Speciale mappen';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Themavoorbeeld';
$labels['meh'] = 'MEH';
$labels['litecube-f'] = 'Lite (gratis)';
$labels['litecube'] = 'Lite';
$labels['litecube_mobile'] = 'Mobile';
$labels['larry'] = 'Larry';
$labels['pluginname'] = 'Instellingen';
$labels['plugindescription'] = 'Dit is een ondersteunende plugin die vereist wordt door diverse andere plugins (o.a. alle hmail_* plugins).';

?>