<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Zarządzanie folderami';
$labels['account'] = 'Administracja kontem';
$labels['classic'] = 'Domyślnie';
$labels['remotefolders'] = 'Foldery specjalne';
$labels['myroundcube'] = 'MyRoundCube';

?>
