<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/pt_BR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: filhocf - 08/24/2012 16:38:59
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Gerenciar pastas';
$labels['account'] = 'Administração da Conta';
$labels['classic'] = 'Padrão';
$labels['remotefolders'] = 'Pastas Especiais';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Visualizar Tema';
$labels['larry'] = 'Larry';

?>