<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Ling Fude - 03/19/2012 15:19:25
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Gerir pastas';
$labels['account'] = 'Administração da conta';
$labels['classic'] = 'Predefinido';
$labels['remotefolders'] = 'Pastas especiais';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Pré-visualização da Skin';

?>