<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/ru_RU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Pavel - 01/26/2013 15:03:49
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Настройки';
$labels['plugindescription'] = 'Это плагин подсказки. Он требует наличия некоторых других плагинов';
$labels['menu'] = 'Меню';
$labels['managefolders'] = 'Управление папками';
$labels['account'] = 'Управление аккаунтом';
$labels['classic'] = 'Настройки по умолчанию';
$labels['remotefolders'] = 'Особые папки';
$labels['myroundcube'] = 'Мой Roundcube';
$labels['skin_preview'] = 'Предпросмотр Скина';
$labels['larry'] = 'Ларри';

?>