<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['menu'] = 'Меню';
$labels['managefolders'] = 'Управление папками';
$labels['account'] = 'Управление аккаунтом';
$labels['classic'] = 'Настройки по умолчанию';
$labels['groupvice4'] = 'ГруппВайс';
$labels['remotefolders'] = 'Особые папки';
$labels['myroundcube'] = 'МойКруглоКуб';
$labels['skin_preview'] = 'Предпросмотр Скина';
$labels['meh'] = 'МЕХ';
$labels['litecube-f'] = 'Легкий';
$labels['larry'] = 'Ларри';

?>