<?php

/*
+-----------------------------------------------------------------------+
| language/sk_SK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Nastavenia';
$labels['plugindescription'] = 'Toto je pomocný plugin. Je požadovaný viacerými inými pluginmi (napr. všetky hmail_* pluginy).)';
$labels['menu'] = 'Ponuka';
$labels['managefolders'] = 'Spravuj priecinky';
$labels['account'] = 'Administrácia úctu';
$labels['classic'] = 'Predvolené';
$labels['remotefolders'] = 'Špeciálne adresáre';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Náhlad vzhladu';
$labels['larry'] = 'Larry';

?>