$(document).ready(function(){"larry"==rcmail.env.skin&&$("#calendar_button").children().attr("style","color: #3CF; background-color: #2c2c2c;");rcmail.addEventListener("plugin.reloadCalendar",function(a){$("#calendar").fullCalendar("removeEvents");$("#calendar").fullCalendar("refetchEvents");rcmail.set_busy(!1,"loading",a);$("#calendaroverlay").hide()});rcmail.addEventListener("plugin.calendar_unlockGUI",function(a){rcmail.set_busy(!1,"loading",a);$("#calendaroverlay").hide();calendar_commands.triggerSearch()});
rcmail.addEventListener("plugin.calendar_errorGUI",function(a){rcmail.set_busy(!1,"loading",a);$("#calendaroverlay").hide();rcmail.display_message(rcmail.gettext("calendar.errorsaving"),"error");$("#calendar").fullCalendar("refetchEvents")});rcmail.addEventListener("plugin.calendar_searchEvents",function(a){if(0!=a.rows){rcmail.env.cal_search_results=a.rows;$("#calsearch_table").html(a.rows);$("#calsearchdialog").dialog("open");var b=-1;if(a.events)$("#calsearch_table tr td").each(function(){b++;
a.events[b].start*=1E3;a.events[b].end&&(a.events[b].end*=1E3);elem=calendar_callbacks.qtip(a.events[b],$(this),"search")});else for(;-1<$("#calsearchfilter").val().indexOf(" ");){$("#calsearchfilter").val($("#calsearchfilter").val().replace(" ","*"));calendar_commands.triggerSearch();break}var e=$("#prefs-box").height()-5,d=$("#calsearch_table tr").height(),c=55;"larry"==rcmail.env.skin&&(c=85);d=Math.max(50+(b+1)*d,c);$("#calsearchdialog").dialog("option","height",Math.min(e,d));0<a.filters.length&&
$("#cal_search_field_categories").attr("checked",!1);$("#calsearchfilter").focus()}});rcmail.addEventListener("plugin.calendar_triggerSearch",function(){calendar_commands.triggerSearch()});rcmail.addEventListener("plugin.calendar_refresh",function(a){$("#calendar").fullCalendar("removeEvents");$("#calendar").fullCalendar("refetchEvents");$("#calendaroverlay").hide();$("#cal_boxtitle").html(a[0].content)});rcmail.addEventListener("plugin.getSettings",function(a){rcmail.env.calsettings=a;if("caldav"==
a.settings.backend){var b=1E3;rcmail.env.noreplication&&(b=100);window.setTimeout("calendar_replicate.init(rcmail.env.calsettings, 'calendar');",b)}$("#cal_boxtitle").html(a.settings.boxtitle.content);$("#calusers").html(a.settings.usersselector.content);$("#calfilterscontainer").html(a.settings.filtersselector.content);$("#categories_html").html(a.settings.categorieshtml);calendar_gui.initNavDatepicker(a);calendar_gui.initClockPickers(a);calendar_commands.init();b=a.settings.first_hour;-1==b&&(b=
(new Date).getHours()-1);$("#calendar").fullCalendar({readyState:function(){"caldav"!=a.settings.backend&&(rcmail.env.cal_env="calendar",calendar_replicate.done("_"+Math.round((new Date).getTime()/1E3)));calendar_gui.init(a);$("#toolbar").show();$("#jqdatepicker").datepicker("setDate",$("#calendar").fullCalendar("getDate"));$("#upcoming").fullCalendar("addEventSource",$("#calendar").fullCalendar("clientEvents"));$("#upcoming").fullCalendar("gotoDate",$("#calendar").fullCalendar("getDate"))},header:{left:"",
center:"",right:""},titleFormat:{month:a.settings.titleFormatMonth,week:a.settings.titleFormatWeek,day:a.settings.titleFormatDay},columnFormat:{month:a.settings.columnFormatMonth,week:a.settings.columnFormatWeek,day:a.settings.columnFormatDay},theme:a.settings.ui_theme_main,selectable:!0,unselectAuto:!1,height:$("#prefs-box").height(),lazyFetching:!1,editable:!0,ignoreTimezone:!1,eventSources:calendar_common.eSources(a,!0),monthNames:a.settings.months,monthNamesShort:a.settings.months_short,dayNames:a.settings.days,
dayNamesShort:a.settings.days_short,firstDay:a.settings.first_day,firstHour:b,slotMinutes:60/a.settings.timeslots,timeFormat:js_time_formats[rcmail.env.rc_time_format],axisFormat:js_time_formats[rcmail.env.rc_time_format],defaultView:calendar_gui.getView(a),allDayText:rcmail.gettext("all-day","calendar"),height:$("#calendar-container").height()-20,viewDisplay:function(e){calendar_callbacks.viewDisplay(e,a)},loading:function(a){rcmail.env.calendar_msgid=calendar_callbacks.loading(a,rcmail.env.calendar_msgid);
calendar_callbacks.loading(a,rcmail.env.calendar_msgid)},eventRender:function(e,d,b){rcmail.env.calreadonly&&(e.editable=!1);calendar_callbacks.eventRender(e,d,b,a)},eventDragStart:function(e,b,c,f){calendar_callbacks.eventDragStart(e,b,c,f,a)},eventDrop:function(e,b,c,f,g){calendar_callbacks.eventDrop(e,b,c,f,g,a)},eventResize:function(b,d){calendar_callbacks.eventResize(b,d,a)},eventResizeStop:function(a,b,c,f){calendar_callbacks.eventResizeStop(a,b,c,f)},select:function(b,d,c,f,g){rcmail.env.calreadonly||
calendar_callbacks.select(b,d,c,f,g,a)},dayClick:function(b,d,c,f){rcmail.env.calreadonly||calendar_callbacks.dayClick(b,d,c,f,a)},eventClick:function(b){rcmail.env.calreadonly||calendar_callbacks.eventClick(b,a)}});a.settings.date&&calendar_commands.gotoDate(a.settings.date)});var g=jzTimezoneDetector.determine_timezone();response_text=g.key;response_text="undefined"==typeof g.timezone?"undefined":g.timezone.olson_tz;rcmail.http_post("plugin.getSettings","_tzname="+response_text+"&_init=1");$("#calendar_button").attr("href",
"#")});