var default_starttime="08:00",planner_items=0,js_time_formats=[],js_date_formats=[],planner_request=[],blink_timer;(function(a){a.fn.blink=function(b){b=a.extend({delay:500},b||{});return this.each(function(){var c=a(this);blink_timer=setInterval(function(){"visible"==a(c).css("visibility")?a(c).css("visibility","hidden"):a(c).css("visibility","visible")},b.delay)})}})(jQuery);
function planner_overlay_toggle(a){$("#planner_help").hide();a?(window.clearTimeout(rcmail.env.planner_timeout),rcmail.env.planner_timeout=window.setTimeout("planner_timeout()",5E3),0<planner_items&&$("#overlay").show()):($("#overlay").hide(),window.clearTimeout(rcmail.env.planner_timeout))}
function planner_timeout(){$("#overlay").is(":visible")&&(rcmail.display_message(rcmail.gettext("planner.errorsaving"),"error"),planner_overlay_toggle(!1),rcmail.http_post("plugin.planner_retrieve","_p="+rcmail.env.planner_items))}
function planner_init(a){planner_sort();$("#planner_items_list").hide();rcmail.env.planner_counts=[];var b="all today tomorrow week starred done deleted overdue".split(" ");$("#planner_items_list").hide();for(var c in b)planner_show(b[c]);$("#planner_items_list").show();a&&planner_dialog_adjust_gui(a)}
function planner_dialog(){if(rcmail.env.planner_dialog_initialized)$("#planner_input").dialog("open");else{$dialogContent=$("#planner_input");var a={};a[rcmail.gettext("planner.search")]=function(c){c.preventDefault();rcmail.env.planner_search_mode=!0;planner_overlay_toggle(!0);planner_search();planner_overlay_toggle(!1);$(".flink").css("font-weight","normal")};a[rcmail.gettext("planner.plan")]=function(c){c.preventDefault();planner_dialog_submit()};a[rcmail.gettext("planner.cancel")]=function(){$dialogContent.dialog("close")};
var b=rcmail.gettext("planner.new");"edit"==$("#planner_mode").val()&&(b=rcmail.gettext("planner.edit"));$dialogContent.dialog({modal:"true"===$("#dialog_modal").html(),title:b,width:parseInt($("#dialog_width").html()),height:parseInt($("#dialog_height").html()),zIndex:parseInt($("#dialog_zIndex").html()),close:function(){planner_dialog_reset_gui()},buttons:a}).show();rcmail.env.planner_dialog_initialized=!0}var c=-1;$(".ui-dialog-buttonset").children().each(function(){c++;switch(c){case 0:"new"==
$("#planner_mode").val()?($(this).focus(),$(this).css("font-weight","bold")):$(this).css("font-weight","normal");break;case 1:"edit"==$("#planner_mode").val()?($(this).focus(),$(this).css("font-weight","bold")):$(this).css("font-weight","normal");break;case 2:$(this).css("font-weight","normal")}});$("#planner_help").hide()}
function planner_search(){planner_items=0;$("#planner_items_list li").hide();for(var a=$.trim($.trim($("#planner_preview_date").text())+" "+$.trim($("#planner_preview_time").text())+" "+$.trim($("#planner_preview_text").text())),b=a;-1<a.indexOf(" ");)a=a.replace(" ","");for(;-1<a.indexOf(".");)a=a.replace(".","");for(;-1<a.indexOf(":");)a=a.replace(":","");$("#planner_items_list li").each(function(){for(var c=$(this).text();-1<c.indexOf(" ");)c=c.replace(" ","");for(;-1<c.indexOf(".");)c=c.replace(".",
"");for(;-1<c.indexOf(":");)c=c.replace(":","");0>c.search(RegExp(a,"i"))?$(this).hide():(planner_items++,$(this).show())});$("#dfilter").attr("title",b);18<b.length&&(b=b.substr(0,15)+" ...");$("#dfilter").html(rcmail.gettext("planner.searchresult")+" &raquo;<b>"+b+"</b>&laquo;");planner_dialog_adjust_gui();$("#items_count").text(planner_items+"/"+(parseInt($("#all_count").text())+parseInt($("#done_count").text())+parseInt($("#deleted_count").text())));$(".lcontrol").css("font-weight","normal");
b=rcmail.gettext("planner.matches_plural");1==planner_items&&(b=rcmail.gettext("planner.matches"));$("#planner_input").dialog("option","title",rcmail.gettext("planner.search")+": "+planner_items+" "+b)}
function planner_datetimepicker(){var a=!1;js_time_formats[rcmail.env.rc_time_format]||(rcmail.env.rc_time_format="HH:MM");js_date_formats[rcmail.env.rc_date_format]||(rcmail.env.rc_date_format="dd.mm.yy");"tt"==js_time_formats[rcmail.env.rc_time_format].substr(js_time_formats[rcmail.env.rc_time_format].length-2).toLowerCase()&&(a=!0);$("#planner_datetimepicker").datetimepicker({timeText:rcmail.gettext("planner.timeText"),hourText:rcmail.gettext("planner.hourText"),minuteText:rcmail.gettext("planner.minuteText"),
minDate:new Date(9E5*Math.round((new Date).getTime()/9E5)),showButtonPanel:!1,onSelect:function(a){a=planner_dialog_ampm_replace(a)+" ";var c=$("#planner_raw").val(),e=planner_dialog_parse($("#planner_raw").val());e[0]&&(c=$.trim(c.replace(e[0],"")));e[1]&&(c=$.trim(c.replace(e[1],"")));$("#planner_raw").val(a+c);planner_dialog_preview(c,a)},timeFormat:js_time_formats[rcmail.env.rc_time_format].toLowerCase(),dateFormat:js_date_formats[rcmail.env.rc_date_format].toLowerCase(),ampm:a,defaultDate:new Date(9E5*
Math.round(((new Date).getTime()+36E5)/9E5))})}
function planner_dialog_submit(){$("#planner_help").hide();if(""!=$.trim($("#planner_text").val())){var a="";!0===$("#planner_starred").prop("checked")&&(a="&_starred=1");!0===$("#planner_done").prop("checked")&&(a+="&_done=1");!0===$("#planner_deleted").prop("checked")&&(a+="&_deleted=1");""!=$("#planner_datetime").val()&&(a=a+"&_d="+encodeURIComponent($("#planner_datetime").val()));"new"==$("#planner_mode").val()?rcmail.http_post("plugin.planner_new","_t="+encodeURIComponent($("#planner_text").val())+
"&_d="+encodeURIComponent($("#planner_datetime").val())+a):rcmail.http_post("plugin.planner_edit","_id="+$("#planner_id").val()+"&_c="+$("#planner_created").val()+"&_t="+encodeURIComponent($("#planner_text").val())+a);planner_overlay_toggle(!0);$("#planner_help").hide();$("#planner_raw").val("");$("#planner_mode").val("new");$("#planner_id").val("");$("#planner_datetimepicker").datetimepicker("setDate",new Date);$("#planner_input").dialog("close")}}
function planner_keypress(){for(var a=Math.min(rcmail.gettext("planner.tomorrow").length,rcmail.gettext("planner.today").length),b=0;b<=a&&rcmail.gettext("planner.tomorrow").substr(b,1)==rcmail.gettext("planner.today").substr(b,1);b++);b=Math.max(b+1,1);$(document).keyup(function(){if($("#planner_raw").val().length>=b)if($("#planner_raw").val().toLowerCase()==rcmail.gettext("planner.today").substr(0,$("#planner_raw").val().length).toLowerCase()){var c=9E5*Math.round(((new Date).getTime()+36E5)/9E5);
$("#planner_datetimepicker").datetimepicker("setDate",new Date(c));c=(new Date(c)).format(js_time_formats[rcmail.env.rc_time_format]);c=planner_dialog_ampm_replace(c);$("#planner_autocomplete").show();$("#planner_autocomplete_content").html(rcmail.gettext("planner.today").toLowerCase()+" "+c+" ")}else $("#planner_raw").val().toLowerCase()==rcmail.gettext("planner.tomorrow").substr(0,$("#planner_raw").val().length).toLowerCase()?(c=9E5*Math.round((new Date).getTime()/9E5)+864E5,$("#planner_datetimepicker").datetimepicker("setDate",
new Date(c)),c=(new Date(c)).format(js_time_formats[rcmail.env.rc_time_format]),c=planner_dialog_ampm_replace(c),$("#planner_autocomplete").show(),$("#planner_autocomplete_content").html(rcmail.gettext("planner.tomorrow").toLowerCase()+" "+c+" ")):($("#planner_autocomplete").hide(),$("#planner_autocomplete_content").html(""));var a=planner_dialog_parse($("#planner_raw").val()),c=a[1]&&a[0]?a[1]+" "+a[0]:!1,d=$("#planner_raw").val();a[2]&&(d=a[2]);planner_dialog_preview(d,c)});$(document).keypress(function(a){if(13==
a.charCode)$("#planner_autocomplete").is(":visible")?$("#planner_autocomplete").trigger("click"):(a.preventDefault(),planner_overlay_toggle(!0),"new"==$("#planner_mode").val()?(planner_search(),planner_overlay_toggle(!1)):planner_dialog_submit());else if(13!=a.charCode){a=String.fromCharCode(a.charCode);try{!0!==$("#planner_input").dialog("isOpen")&&planner_dialog()}catch(b){planner_dialog()}a&&$("#planner_raw").focus()}});$(document).keydown(function(a){40==a.keyCode&&$("#planner_autocomplete").is(":visible")&&
(a.preventDefault(),$("#planner_autocomplete").trigger("click"))})}
function planner_dialog_parse(a){var b=[],c=[],e=[],d=[],g,h,c=$("#planner_raw").val().split(" ");if(2>c.length)return b;g=c[0];if(c[0].toLowerCase()==rcmail.gettext("planner.today").toLowerCase())b[0]=planner_dialog_time(c[1]),b[1]=g,b[2]=a.replace(g,"").replace(b[0],"");else if(c[0].toLowerCase()==rcmail.gettext("planner.tomorrow").toLowerCase())b[0]=planner_dialog_time(c[1]),b[1]=g,b[2]=a.replace(g,"").replace(b[0],"");else if((d=c[0].match(/\+(([0-9][0-9])|([0-9]))/))&&d[0])c=a.split(d[0]),b[0]=
planner_dialog_time(c[1]),b[1]=g,b[2]=a.replace(g,"").replace(b[0],"");else{c[0]+=" ";e=$("#planner_datetimepicker").datepicker("option","dateFormat");e=e.replace(/dd/i,"d");e=e.replace(/mm/i,"m");e=e.replace(/yy/i,"y");h=planner_dialog_date_separator();e=e.split(h);h="[\\"+h+"]";var d="",f;for(f in e)d+=e[f],f<e.length-1&&(d+=h);d=d.replace("d","(0[1-9]|[12][0-9]|3[01])");d=d.replace("m","(0[1-9]|1[012])");d=d.replace("y","((20)[0-9][0-9])");if((d=c[0].match(eval("/"+d+"/")))&&d[0])c=a.split(d[0]),
b[0]=planner_dialog_time(c[1]),b[1]=g,b[2]=a.replace(g,"").replace(b[0],"");else{d="";for(f in e)"y"!=e[f]&&(d=d+e[f]+h);d=d.replace("d","(0[1-9]|[12][0-9]|3[01])");d=d.replace("m","(0[1-9]|1[012])");d="/"+d+"/";d=d.replace("]/","\\s]/");if((d=c[0].match(eval(d)))&&d[0])c=a.split(d[0]),b[0]=planner_dialog_time(c[1]),b[1]=g,b[2]=a.replace(g,"").replace(b[0],"")}}return b}
function planner_dialog_time(a){var b=[],c="default";a=" "+a+" ";(b=a.match(/([\s]([0-9])|(0[0-9])|(1[0-9]|2[0-3])):([0-5][0-9](am\s|pm\s|a\s|p\s|h\s|\s))/))&&b[0]?c=b[0]:(b=a.match(/([\s]([0-9])|(0[0-9])|(1[0-9]|2[0-3]))(h\s|am\s|pm\s|a\s|p\s|\s)/i))&&b[0]&&(c=b[0]);return $.trim(c)}function planner_dialog_date_separator(a){var b=[];a||(a=$("#planner_datetimepicker").datepicker("option","dateFormat"));return(b=a.match(/[^a-z0-9]/i))&&b[0]?b[0]:!1}
function planner_dialog_ampm_replace(a){a=a.replace(/\sam/i,"am");return a=a.replace(/\spm/i,"pm")}function planner_dialog_format_reduce(a){var b=[];separator=planner_dialog_date_separator(a);var b=a.split(separator),c;for(c in b)a=a.replace(b[c],b[c].substr(0,1).toLowerCase());return a}
function planner_dialog_datetime_display(a,b){var c,e,d,g,h,f,k;g=[];c=[];d=[];-1<a.indexOf("default")&&(a=a.replace("default",default_starttime));c=planner_dialog_format_reduce($("#planner_datetimepicker").datepicker("option","dateFormat"));b||(b=c);g=a.split(" ");d=g[0];g=g[1];b=planner_dialog_format_reduce(b);if("+"!=a.substr(0,1)){e=planner_dialog_date_separator(c);c=c.split(e);for(var j in c)switch(c[j]){case "y":h=j;break;case "m":f=j;break;case "d":k=j}if(e=planner_dialog_date_separator(d))d=
d.split(e),3>d.length&&0==h&&(d=(new Date).getFullYear()+e+d[0]+e+d[1],d=d.split(e)),a=b.replace("m",d[f]),a=a.replace("d",d[k]),d[h]||(d[h]=(new Date).getFullYear()),a=a.replace("y",d[h])+" "+g}return a}
function planner_dialog_datetime(a){var b=[],c=[],e=[],d;a=planner_dialog_datetime_display(a,"m/d/y");b=a.split(" ");if(b[0]&&b[1]){if(-1<b[1].indexOf(":")){for(d=0;d<b.length;d++)0==b[d].substr(0,1)&&(b[d]=b[d].substr(1));c=b[1].split(":");b[1]=12>parseInt(c[0])&&-1<b[1].toLowerCase().indexOf("p")?Math.min(parseInt(c[0])+12,23)+":"+c[1]:c[0]+":"+c[1]}else b[1]=12>parseInt(b[1])&&-1<b[1].toLowerCase().indexOf("p")?Math.min(parseInt(b[1])+12,23)+":00":b[1]+":00";c=b[1].split(":");2>c[0].length&&(c[0]=
"0"+c[0]);2>c[1].length&&(c[1]="0"+c[1]);b[1]=c[0]+":"+c[1];e.time_format=js_time_formats[rcmail.env.rc_time_format];c=a.split(" ");e.date_formatted=c[0];if(b[0].toLowerCase()==rcmail.gettext("planner.today").toLowerCase())datetime=new Date,datetime=datetime.getMonth()+1+"/"+datetime.getDate()+"/"+datetime.getFullYear()+" "+b[1];else if(b[0].toLowerCase()==rcmail.gettext("planner.tomorrow").toLowerCase())datetime=new Date((new Date).getTime()+864E5),datetime=datetime.getMonth()+1+"/"+datetime.getDate()+
"/"+datetime.getFullYear()+" "+b[1];else if("+"==b[0].substr(0,1)){datetime=new Date((new Date).getFullYear(),(new Date).getMonth(),(new Date).getDate());datetime=36E5*Math.round(datetime.getTime()/36E5)+864E5*parseInt(b[0]);c=b[1].split(":");for(d=0;d<c.length;d++)0==c[d].substr(0,1)&&(c[d]=c[d].substr(1));datetime=datetime+36E5*parseInt(c[0])+6E4*parseInt(c[1])}else datetime=(new Date(b[0]+" "+b[1])).getTime();e.date=b[0];e.time=b[1];datetime&&(e.date_stamp=datetime,datetime=new Date(datetime),
e.time_formatted=datetime.format(e.time_format),a=datetime.getMonth()+1+"",2>a.length&&(a="0"+a),b=datetime.getDate()+"",2>b.length&&(b="0"+b),c=datetime.getHours()+"",2>c.length&&(c="0"+c),d=datetime.getMinutes()+"",2>d.length&&(d="0"+d),e.datetime=datetime.getFullYear()+"-"+a+"-"+b+" "+c+":"+d+":00",datetime=datetime.format("dd mmm"),c=datetime.split(" "),e.date_short_locale=c[0]+" "+rcmail.gettext("planner."+c[1]))}return e}
function planner_html_sanitize(a){return a=a.replace("<","&lt;").replace(">","&gt;")}
function planner_dialog_preview(a,b){var c=[];$("#planner_text").val($.trim(a));$("#planner_preview_text").html($.trim(planner_html_sanitize(a)));b?(a=$.trim(b)+" "+$.trim(a),c=planner_dialog_datetime($.trim(b)),c.date_stamp?($("#planner_datetimepicker").datetimepicker("setDate",new Date(c.date_stamp)),$("#planner_datetime").val(c.datetime),$("#planner_preview_date").html(planner_html_sanitize(c.date_short_locale)),$("#planner_preview_time").html(planner_html_sanitize(c.time_formatted)),$("#planner_preview_text").addClass("datetime")):
($("#planner_raw").val(c[0]+" "),$("#planner_preview_text").html(planner_html_sanitize(b+" "+a)),$("#planner_text").val(b+" "+a),$("#planner_datetime").val(""))):($("#planner_preview_text").removeClass("datetime"),$("#planner_preview_time").html(""),$("#planner_preview_date").html(""),$("#planner_datetime").val(""))}
function planner_dialog_edit(a,b,c){planner_dialog_reset_gui();var e=a.find(".created").val();$("#planner_input").dialog("option","title",rcmail.gettext("planner.edit"));planner_dialog_preview(b,c);c&&(c=planner_dialog_datetime_display(c),b=c+" "+b);$("#planner_raw").val(b);$("#planner_mode").val("edit");$("#planner_id").val(a.parent().parent().attr("id"));$("#planner_created").val(e);"delete"==a.parent().parent().children().next().attr("class")&&($("#planner_done").prop("checked",!0),$("#planner_preview_done").removeClass("pdelete"),
$("#planner_preview_done").addClass("pdone"));"star"==a.parent().parent().children().attr("class")&&($("#planner_starred").prop("checked",!0),$("#planner_preview_star").removeClass("pnostar"),$("#planner_preview_star").addClass("pstar"));"deleted"==$("#controls").val()&&($("#planner_deleted").prop("checked",!0),$("#planner_done").prop("checked",!1),$("#planner_preview_done").removeClass("pdone"),$("#planner_preview_done").addClass("pdelete"));planner_dialog()}
function planner_dialog_reset_gui(){$("#planner_raw").val("");$("#planner_autocomplete_content").html("");$("#planner_autocomplete").hide();$("#planner_done").prop("checked",!1);$("#planner_preview_done").removeClass("pdone");$("#planner_starred").prop("checked",!1);$("#planner_preview_star").removeClass("pstar");$("#planner_preview_star").addClass("pnostar");$("#planner_deleted").prop("checked",!1);$("#planner_preview_done").removeClass("pdelete");$("#planner_id").val("");try{!0!==$("#planner_input").dialog("isOpen")&&
$("#planner_input").dialog("option","title",rcmail.gettext("planner.new"))}catch(a){planner_dialog(),$("#planner_input").dialog("option","title",rcmail.gettext("planner.new"))}$("#planner_mode").val("new");$("#planner_datetime").val("");$("#planner_text").val("");$("#planner_preview_text").html("");$("#planner_preview_time").html("");$("#planner_preview_date").html("");$("#planner_datetimepicker").datetimepicker("setDate",new Date(9E5*Math.round(((new Date).getTime()+36E5)/9E5)));$(".ui-dialog-buttonset").children().blur();
$("#planner_raw").focus()}
function planner_dialog_adjust_gui(){"birthdays"==rcmail.env.planner_filter?$(".nobirthday").hide():$(".nobirthday").show();planner_items=0;$("#planner_items_list li").each(function(){"none"!=$(this).css("display")&&planner_items++});rcmail.env.planner_counts&&rcmail.env.planner_counts[rcmail.env.planner_items]?$("#items_count").text(planner_items+"/"+rcmail.env.planner_counts[rcmail.env.planner_items]):$("#items_count").text(planner_items);planner_show_overdue_count();if("right"==$("#control_bar_position").html())var a=
$("#planner_items").offset().left+$("#planner_items_list").width()-$("#control_bar").width()-parseInt($("#control_bar_fudge").html());else"left"==$("#control_bar_position").html()?a=$("#planner_items").offset().left:"center"==$("#control_bar_position").html()&&(a=$("#planner_items").offset().left,$("#control_bar").css("width",$("#planner_items_list").width()),$("#control_bar").html("<center>"+$("#control_bar").html()+"</center>"));a&&$("#control_bar").css("left",a);$("#control_bar").show();if("variable"==
$("#filter_bar_position").html()){var b=$("#planner_items_list").offset().top+$("#planner_items_list").height(),b=Math.min(b,$(window).height()-parseInt($("#filter_bar_fudge").html()));$("#filter_bar").css("top",b);a=$("#planner_items").offset().left+$("#planner_items_list").width()-$("#expunge_bar").width()-parseInt($("#control_bar_fudge").html());$("#expunge_bar").css("top",b);$("#expunge_bar").css("left",a)}rcmail.env.planner_filter&&rcmail.env.planner_filter!=rcmail.env.planner_last_filter&&(rcmail.env.planner_last_filter=
rcmail.env.planner_filter,planner_save_prefs(),$("#f"+rcmail.env.planner_filter).trigger("click"))}
function planner_save_prefs(){rcmail.env.planner_items&&rcmail.env.planner_items!=rcmail.env.planner_saved_view&&(rcmail.env.planner_saved_view=rcmail.env.planner_items,planner_request[0]="_v="+rcmail.env.planner_items+"&");rcmail.env.planner_filter&&rcmail.env.planner_filter!=rcmail.env.planner_saved_filter&&(rcmail.env.planner_saved_filter=rcmail.env.planner_filter,planner_request[1]="_f="+rcmail.env.planner_filter+"&");if(planner_request[0]||planner_request[1]){var a="";planner_request[0]&&(a+=
planner_request[0]);planner_request[1]&&(a+=planner_request[1]);a=a.substr(0,a.length-1);a!=rcmail.env.planner_saved_request&&(rcmail.env.planner_saved_request=a,rcmail.http_post("plugin.planner_prefs",a))}}
function planner_show(a){"function"==typeof eval("planner_show_"+a)&&($("#planner_items").css("overflow","hidden"),"all"!=a&&"today"!=a&&"tomorrow"!=a&&"week"!=a?($("#birthdays_count").hide(),$("#bdlabel").hide(),$("#cbirthdays").hide()):($("#birthdays_count").show(),$("#bdlabel").show(),$("#cbirthdays").show()),planner_overlay_toggle(!0),eval("planner_show_"+a)(),planner_overlay_toggle(!1),$("#planner_items").css("overflow","auto"),rcmail.env.planner_select=a)}
function planner_show_init(){planner_filter("all")}function planner_show_all(){$("#planner_items_list li").show();$(".delete").each(function(){$(this).parent().hide()});$(".remove").each(function(){$(this).parent().hide()});planner_filter("all")}
function planner_show_overdue(){$(".datetime").each(function(){var a=new Date($(this).prev().prev().val());if(a){var b=new Date,a=a.getTime(),b=b.getTime();a<b?$(this).parent().parent().show():$(this).parent().parent().hide()}});$(".nodate").each(function(){$(this).parent().parent().hide()});$(".delete").each(function(){$(this).parent().hide()});$(".remove").each(function(){$(this).parent().hide()});$(".birthday").each(function(){$(this).parent().hide()});planner_filter("overdue")}
function planner_show_today(){$(".nodate").each(function(){$(this).parent().parent().show()});$(".datetime").each(function(){var a=new Date($(this).prev().prev().val());if(a){var b=new Date,b=new Date(b.getFullYear(),b.getMonth(),b.getDate(),23,59,59),c=new Date((new Date(b)).getTime()-864E5),c=new Date(c.getFullYear(),c.getMonth(),c.getDate(),23,59,59),a=a.getTime(),b=b.getTime(),c=c.getTime();a>b||a<=c?$(this).parent().parent().hide():$(this).parent().parent().show()}});$(".delete").each(function(){$(this).parent().hide()});
$(".remove").each(function(){$(this).parent().hide()});planner_filter("today")}
function planner_show_tomorrow(){$(".nodate").each(function(){$(this).parent().parent().show()});$(".datetime").each(function(){var a=new Date($(this).prev().prev().val());if(a){var b=new Date,b=new Date(b.getFullYear(),b.getMonth(),b.getDate(),23,59,59),c=new Date((new Date(b)).getTime()+864E5),c=new Date(c.getFullYear(),c.getMonth(),c.getDate(),23,59,59),a=a.getTime(),b=b.getTime(),c=c.getTime();a>b&&a<=c?$(this).parent().parent().show():$(this).parent().parent().hide()}});$(".delete").each(function(){$(this).parent().hide()});
$(".remove").each(function(){$(this).parent().hide()});planner_filter("tomorrow")}
function planner_show_week(){$(".nodate").each(function(){$(this).parent().parent().show()});$(".datetime").each(function(){var a=new Date($(this).prev().prev().val());if(a){var b=new Date,b=new Date(b.getFullYear(),b.getMonth(),b.getDate(),23,59,59),c=b.getDay();0==c&&(c=7);b=new Date(b.getTime()-864E5*c);c=new Date((new Date(b)).getTime()+6048E5);c=new Date(c.getFullYear(),c.getMonth(),c.getDate(),23,59,59);a=a.getTime();b=b.getTime();c=c.getTime();a>b&&a<=c?$(this).parent().parent().show():$(this).parent().parent().hide()}});
$(".delete").each(function(){$(this).parent().hide()});$(".remove").each(function(){$(this).parent().hide()});planner_filter("week")}function planner_show_starred(){$("#planner_items_list li").show();$(".delete").each(function(){$(this).parent().hide()});$(".remove").each(function(){$(this).parent().hide()});$(".birthday").each(function(){$(this).parent().hide()});$(".nostar").each(function(){$(this).parent().hide()});planner_filter("starred")}
function planner_show_done(){$(".done").each(function(){$(this).parent().hide()});$(".remove").each(function(){$(this).parent().hide()});$(".birthday").each(function(){$(this).parent().hide()});$(".nostar").each(function(){$(this).parent().hide()});$(".star").each(function(){$(this).parent().hide()});$(".delete").each(function(){$(this).parent().show()});planner_filter("done")}
function planner_show_deleted(){$("#planner_items_list li").hide();$(".remove").each(function(){$(this).parent().show()});planner_filter("deleted")}
function planner_show_overdue_count(){var a=0;$(".datetime").each(function(){var c=new Date($(this).prev().prev().val());if(c){var b=new Date,c=c.getTime(),b=b.getTime();c<b&&(!$(this).parent().hasClass("birthday")&&$(this).parent().prev().hasClass("done"))&&a++}});0<a&&!rcmail.env.planner_blink&&(rcmail.env.planner_blink=!0,$("#overdue_count").blink({delay:1500}));a==rcmail.env.planner_counts.overdue?(clearInterval(blink_timer),rcmail.env.planner_blink=!1,$("#overdue_count").css("visibility","visible")):
$("#overdue_count").html(a);if(a>rcmail.env.planner_counts.overdue)try{var b=$('<audio src="plugins/planner/sound.wav" />');b.get(0).play()}catch(c){b=$('<embed id="sound" src="plugins/planner/sound.wav" hidden=true autostart=true loop=false />'),b.appendTo($("body")),window.setTimeout("$('#sound').remove()",5E3)}}
function planner_sort(){$("#planner_items_list li").sortElements(function(a,b){var c=$(a).children().next().next().children().next().next().next().val();c||(c=$(a).children().next().children().next().next().next().val())||(c=0);var c=(new Date(c)).getTime(),e=$(b).children().next().next().children().next().next().next().val();e||(e=$(b).children().next().children().next().next().next().val())||(e=0);var d=$(a).children().next().next().children().next().next().next().text();d||(d=$(a).children().next().next().children().text());
var g=$(b).children().next().next().children().next().next().next().text();g||(g=$(b).children().next().next().children().text());var h="0000000000000",f="0000000000000";0==c&&(h=(new Date).getTime()-parseInt($(a).children().next().next().children().find(".created").val())+"",f=(new Date).getTime()-parseInt($(b).children().next().next().children().find(".created").val())+"");for(;13>h.length;)h="0"+h;for(;13>f.length;)f="0"+f;e=(new Date(e)).getTime();c=c+h+d.toLowerCase();e=e+f+g.toLowerCase();return c>
e?1:-1})}
function planner_filter(a){a&&(planner_items=0,$("#planner_items_list li").each(function(){"none"!=$(this).css("display")&&planner_items++}),$("#"+a+"_count").html(planner_items),rcmail.env.planner_counts[a]=planner_items);switch(rcmail.env.planner_filter){case "todos":$(".datetime").each(function(){$(this).parent().parent().hide()});break;case "plans":$(".nodate").each(function(){$(this).parent().parent().hide()});break;case "birthdays":$(".nodate").each(function(){$(this).parent().parent().hide()}),$(".datetime").each(function(){$(this).parent().hasClass("birthday")||
$(this).parent().parent().hide()})}"deleted"!=rcmail.env.planner_items?$("#expunge_bar").hide():1<planner_items&&$("#expunge_bar").show();window.setTimeout("planner_dialog_adjust_gui()",100)}
function planner_drag(){$("#planner_items_list").sortable({revert:!1,containment:"window",scroll:!1,helper:"clone",cursor:"move",items:"li.drag_nodate",stop:function(a,b){var d=b.item.find(".drag_id").val(),g=$("#"+d).prev().find(".created").val(),h=$("#"+d).prev();h.hasClass("drag_datetime")||h.hasClass("drag_birthday")?planner_sort():(g=g?g-1E3:(new Date).getTime(),$("#"+d).prev().find(".created").val(g),planner_overlay_toggle(!0),rcmail.http_post("plugin.planner_created","_id="+d+"&_c="+Math.round(g/
1E3)));planner_drag()},appendTo:"#planner_drag_list",zIndex:999999});"function"==typeof planner_drag_notes&&planner_drag_notes();"function"==typeof planner_drag_events&&planner_drag_events();if("function"==typeof planner_drag_birthdays)planner_drag_birthdays();else{var a=$("#planner_items"),b=$(".button-mail");$("li.drag_birthday",a).draggable({cancel:"a.ui-icon",revert:"invalid",containment:"window",scroll:!1,helper:"clone",cursor:"move",appendTo:"#planner_drag_list",zIndex:999999});b.droppable({accept:"#planner_items_list > li.drag_birthday",
activeClass:"ui-state-highlight",tolerance:"touch",drop:function(a,b){var d=(new Date(b.draggable.find(".time").next().val())).getTime()+252E5,d=Math.round(d/1E3);new Date(1E3*d)<new Date&&(d=new Date(1E3*d),d=(new Date(d.getMonth()+1+"/"+d.getDate()+"/"+(d.getFullYear()+1)+" 08:00:00")).getTime(),d=Math.round(d/1E3));var d="&_date="+d,g=b.draggable.find(".drag_email").val(),h=rcmail.env.task;rcmail.env.task="mail";rcmail.env.compose_newwindow?composenewwindowcommandcaller("compose",g+"?subject="+
rcmail.gettext("planner.happybirthday")+d,this):rcmail.command("compose",g+"?subject="+rcmail.gettext("planner.happybirthday")+d,this);$("#planner_help").hide();rcmail.env.task=h}})}a=$("#planner_items");$("li.drag_birthday",a).draggable({cancel:"a.ui-icon",revert:"invalid",containment:"window",scroll:!1,helper:"clone",cursor:"move",appendTo:"#planner_drag_list",zIndex:999999});$("li.drag_datetime",a).draggable({cancel:"a.ui-icon",revert:"invalid",containment:"window",scroll:!1,helper:"clone",cursor:"move",
appendTo:"#planner_drag_list",zIndex:999999});$(".ddate").droppable({accept:function(a){if(a.children().hasClass("edit"))return!0},activeClass:"ui-state-highlight",tolerance:"pointer",drop:function(a,b){planner_overlay_toggle(!0);var d=b.draggable.find(".datetime").text();d||(d=b.draggable.text());var g=$(this).attr("id"),h=new Date(9E5*Math.round(((new Date).getTime()+36E5)/9E5)),f=b.draggable.find(".datetime").prev().prev().val();f?(f=f.split(" "),f=f[1].split(":"),f=f[0]+":"+f[1]):f=h.getHours()+
":"+h.getMinutes();switch(g){case "today":case "ctoday":rcmail.http_post("plugin.planner_edit","_id="+b.draggable.find(".drag_id").val()+"&_t="+encodeURIComponent(d)+"&_d="+encodeURIComponent((new Date(h)).format("mm/dd/yyyy")+" "+f));break;case "tomorrow":case "ctomorrow":h=new Date((new Date(h)).getTime()+864E5);(f=b.draggable.find(".datetime").prev().prev().val())?(f=f.split(" "),f=f[1].split(":"),f=f[0]+":"+f[1]):f=h.getHours()+":"+h.getMinutes();rcmail.http_post("plugin.planner_edit","_id="+
b.draggable.find(".drag_id").val()+"&_t="+encodeURIComponent(d)+"&_d="+encodeURIComponent((new Date(h)).format("mm/dd/yyyy")+" "+f));break;case "week":case "cweek":planner_overlay_toggle(!1),b.draggable.find(".nodate").trigger("click"),$("#planner_datetimepicker").datepicker("setDate",h),$(".ui-state-highlight").trigger("click")}}});$("#planner_items_list").disableSelection();$(".date").attr("title",rcmail.gettext("planner.remove_date"));$(".date").live("mousedown",function(a){if(3==a.which){a=$(this).parent().find(".datetime").text();
var b=$(this).parent().find(".drag_id").val();planner_overlay_toggle(!0);var d=$(this).parent().find(".created").val();$(this).parent().parent().removeClass("today");$(this).parent().parent().removeClass("highlight");$(this).parent().parent().removeClass("drag_datetime");$(this).parent().parent().addClass("drag_nodate");rcmail.http_post("plugin.planner_edit","_id="+b+"&_c="+d+"&_t="+encodeURIComponent(a))}})};