<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/archivefolder/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 01/08/2015 15:52:26
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Arkistoi kansio';
$labels['plugindescription'] = 'Siirrä viestit ennaltamääritettyyn arkistokansioon.';
$labels['buttontitle'] = 'Arkistoi';
$labels['archived'] = 'Arkistointi onnistui';
$labels['archivefolder'] = 'Arkistoi';
$labels['folders'] = 'Kaikki kansiot';

?>