<?php

/*
+-----------------------------------------------------------------------+
| language/nl_NL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Archiefmap';
$labels['plugindescription'] = 'Verplaats berichten naar de vooringestelde archiefmap.';
$labels['buttontitle'] = 'Bericht archiveren';
$labels['archived'] = 'Archiveren voltooid';
$labels['archivefolder'] = 'Archief';
$labels['folders'] = 'Alle Mappen';

?>