<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Captcha';
$labels['plugindescription'] = 'Evita a software automatitzat executar accions que puguin degradar la qualitat del servei Roundcube';
$labels['submit'] = 'Enviar';
$labels['entersecuritycode'] = 'Introdueix el codi de seguretat';
$labels['reload'] = 'Recarrega';
$labels['showriddle'] = 'Fes clic per mostrar l\'endevinalla';
$labels['hideriddle'] = 'Amaga l\'endevinalla';
$labels['back'] = 'Enrere';
$labels['guess'] = 'Endevina les lletres i números (endevinalla de contrasenya)';
$labels['andthen'] = 'i llavors';
$labels['followedby'] = 'seguit per';
$labels['and'] = 'i';
$labels['andnota'] = 'i no un/a';
$labels['but'] = 'però';
$labels['small'] = 'petita';
$labels['letters'] = 'lletra/es';
$labels['charsbefore'] = 'caràcters abans';
$labels['captchainput'] = 'Si us plau, introdueixi el codi de seguretat';
$labels['captchafailed'] = 'El codi de seguretat no coincideix';

?>