<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| EXAuthor: Ales Pospichal <ales@pospichalales.info>                    |
| Now: Ondrej Krejcik <ondra@tachec.org>                                |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Captcha ověření';
$labels['plugindescription'] = 'Zabraňuje automatizovanému software provádění akcí, které degradují kvalitu služby Roundcube.';
$labels['submit'] = 'Potvrdit';
$labels['entersecuritycode'] = 'Napište ověřovací kód';
$labels['reload'] = 'Obnovit';
$labels['showriddle'] = 'Klikněte pro zobrazení hádanky';
$labels['hideriddle'] = 'Schovat hádanku';
$labels['showphrase'] = 'Zobrazit heslo';
$labels['back'] = 'Zpět';
$labels['guess'] = 'Hádejte písmena a číslice (heslová hádanka)';
$labels['andthen'] = 'a pak';
$labels['followedby'] = 'následováno';
$labels['and'] = 'a';
$labels['andnota'] = 'a nikoli';
$labels['but'] = 'ale';
$labels['small'] = 'malá';
$labels['letters'] = 'písmena';
$labels['charsbefore'] = 'znaků před';
$labels['captchainput'] = 'Napište prosím ověřovací kód';
$labels['captchafailed'] = 'Ověřovací kód nesouhlasí';

?>