<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['submit'] = 'Potvrdit';
$labels['entersecuritycode'] = 'Napište ověřovací kód';
$labels['reload'] = 'Obnovit';
$labels['back'] = 'Zpět';
$labels['guess'] = 'Hádejte písmena a číslice (heslová hádanka)';
$labels['andthen'] = 'a pak';
$labels['followedby'] = 'následováno';
$labels['and'] = 'a';
$labels['andnota'] = 'a nikoli';
$labels['but'] = 'ale';
$labels['small'] = 'malá';
$labels['letters'] = 'písmena';
$labels['charsbefore'] = 'znaků před';

?>