<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 17:56:48
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Captcha';
$labels['plugindescription'] = 'Menschliche Eingaben erkennen.';
$labels['submit'] = 'Abschicken';
$labels['entersecuritycode'] = 'Security Code eingeben';
$labels['reload'] = 'Neu laden';
$labels['showriddle'] = 'Rätsel einblenden';
$labels['hideriddle'] = 'Rätsel ausblenden';
$labels['back'] = 'Zurück';
$labels['guess'] = 'Erraten Sie die Buchstaben und Ziffern';
$labels['andthen'] = 'und dann';
$labels['followedby'] = 'gefolgt von';
$labels['and'] = 'und';
$labels['andnota'] = 'und nicht ein';
$labels['but'] = 'aber';
$labels['small'] = 'klein';
$labels['letters'] = 'Buchstabe(n)';
$labels['charsbefore'] = 'Buchstabe(n) bevor';
$labels['captchainput'] = 'Bitte Security Code eingeben';
$labels['captchafailed'] = 'Security Code stimmt nicht überein';

?>