<?php

$labels = array();
$labels['pluginname'] = 'Captcha';
$labels['plugindescription'] = 'Menschliche Eingaben erkennen.';
$labels['submit'] = 'Abschicken';
$labels['entersecuritycode'] = 'Security Code eingeben';
$labels['reload'] = 'Neu laden';
$labels['showriddle'] = 'Rätsel einblenden';
$labels['hideriddle'] = 'Rätsel ausblenden';
$labels['showphrase'] = 'Sicherheitscode anzeigen';
$labels['back'] = 'Zurück';
$labels['guess'] = 'Erraten Sie die Buchstaben und Ziffern';
$labels['andthen'] = 'und dann';
$labels['followedby'] = 'gefolgt von';
$labels['and'] = 'und';
$labels['andnota'] = 'und nicht ein';
$labels['but'] = 'aber';
$labels['small'] = 'klein';
$labels['letters'] = 'Buchstabe(n)';
$labels['charsbefore'] = 'Buchstabe(n) bevor';
$labels['captchainput'] = 'Bitte Security Code eingeben';
$labels['captchafailed'] = 'Security Code stimmt nicht überein';

?>