<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:31:55
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Captcha Challenge';
$labels['plugindescription'] = 'Prevent automated software from performing actions which degrade the quality of your Roundcube se...';
$labels['submit'] = 'Submit';
$labels['entersecuritycode'] = 'Enter Security Code';
$labels['reload'] = 'Reload';
$labels['back'] = 'Back';
$labels['guess'] = 'Guess the letters andnumbers (passphrase riddle)';
$labels['andthen'] = 'and then';
$labels['followedby'] = 'followed by';
$labels['and'] = 'and';
$labels['andnota'] = 'and not a';
$labels['but'] = 'but';
$labels['small'] = 'small';
$labels['letters'] = 'letter(s)';
$labels['charsbefore'] = 'chars before';
$labels['captchainput'] = 'Please enter Security Code';
$labels['captchafailed'] = 'Security Code does not match';

?>