<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 09/05/2012 11:27:06
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Captcha';
$labels['plugindescription'] = 'Empêche les logiciels automatisés d\'exécuter des actions qui dégradent la qualité de votre service Roundcube.';
$labels['submit'] = 'Valider';
$labels['entersecuritycode'] = 'Entrer le code de sécurité';
$labels['reload'] = 'Recharger';
$labels['showriddle'] = 'Cliquer pour voir le code';
$labels['hideriddle'] = 'Masquer le code';
$labels['showphrase'] = 'Montrer la phrase secrète';
$labels['back'] = 'Précédent';
$labels['guess'] = 'Deviner les lettres et les chiffres (mot de passe codé)';
$labels['andthen'] = 'et puis';
$labels['followedby'] = 'suivi par';
$labels['and'] = 'et';
$labels['andnota'] = 'et pas un';
$labels['but'] = 'mais';
$labels['small'] = 'petit';
$labels['letters'] = 'lettre(s)';
$labels['charsbefore'] = 'caractère précédent';
$labels['captchainput'] = 'Merci d\'entrer le code de sécurité';
$labels['captchafailed'] = 'Le code de séccurité ne correspond pas';

?>