<?php
$labels = array();
$labels['submit'] = 'Enviar';
$labels['entersecuritycode'] = 'Introduza o código de seguridade';
$labels['reload'] = 'Recargar';
$labels['back'] = 'Atrás';
$labels['guess'] = "Adiviñe as letras e\nnúmeros (contrasinal oculta)";
$labels['andthen'] = 'e logo';
$labels['followedby'] = 'seguido por';
$labels['and'] = 'e';
$labels['andnota'] = 'e non un';
$labels['but'] = 'pero';
$labels['small'] = 'pequeno';
$labels['letters'] = 'carta(s)';
$labels['charsbefore'] = 'caracteres antes';
$labels['captchainput'] = 'Por favor, introduza o código de seguridade';
$labels['captchafailed'] = 'O código de seguridade non coincide';
?>