<?php

/*
+-----------------------------------------------------------------------+
| language/pt_PT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Desafio Captcha';
$labels['plugindescription'] = 'Previne que softwares automatizados executem ações para degradar a qualidade do seu serviço Roundcube.';
$labels['submit'] = 'Enviar';
$labels['entersecuritycode'] = 'Digite o código de segurança';
$labels['reload'] = 'Recarregar';
$labels['showriddle'] = 'Clique para mostrar o enigma';
$labels['hideriddle'] = 'Ocultar o enigma';
$labels['back'] = 'Voltar';
$labels['guess'] = 'Adivinhe as letras e números (frase enigma)';
$labels['andthen'] = 'e, em seguida';
$labels['followedby'] = 'seguido por';
$labels['and'] = 'e';
$labels['andnota'] = 'e não um';
$labels['but'] = 'mas';
$labels['small'] = 'pequeno';
$labels['letters'] = 'letra(s)';
$labels['charsbefore'] = 'caracteres antes';
$labels['captchainput'] = 'Digite o código de segurança';
$labels['captchafailed'] = 'O código de segurança não corresponde';

?>