<?php
$labels = array();
$labels['pluginname'] = 'Капча';
$labels['plugindescription'] = 'Предотвращает автоматизированные действия, направленные на ухудшение качества работы вашего Roundcube сервиса.';
$labels['submit'] = 'Подтвердить';
$labels['entersecuritycode'] = 'Введите секретный код';
$labels['reload'] = 'Обновить';
$labels['showriddle'] = 'Кликните для просмотра Загадки';
$labels['hideriddle'] = 'Скрыть Загадку';
$labels['back'] = 'Назад';
$labels['guess'] = 'Угадайте буквы и цифры (загадочная фраза)';
$labels['andthen'] = 'и потом';
$labels['followedby'] = 'следует';
$labels['and'] = 'и';
$labels['andnota'] = 'и не';
$labels['but'] = 'но';
$labels['small'] = 'маленький';
$labels['letters'] = 'буква(ы)';
$labels['charsbefore'] = 'символы до';
$labels['captchainput'] = 'Пожалуйста, введите секретный код';
$labels['captchafailed'] = 'Секретный код не совпадает';

?>