<?php
$labels = array();
$labels['pluginname'] = '验证码';
$labels['plugindescription'] = '阻止全自动软件行为，避免降低您的Roundcube服务品质。';
$labels['submit'] = '提交';
$labels['entersecuritycode'] = '请输入验证码';
$labels['reload'] = '刷新';
$labels['showriddle'] = '单击显示谜语';
$labels['hideriddle'] = '隐藏谜语';
$labels['showphrase'] = '显示密码短语';
$labels['back'] = '返回';
$labels['guess'] = "请猜字母和数字（字谜）";
$labels['andthen'] = 'and then';
$labels['followedby'] = 'followed by';
$labels['and'] = 'and';
$labels['andnota'] = 'and not a';
$labels['but'] = 'but';
$labels['small'] = 'small';
$labels['letters'] = 'letter(s)';
$labels['charsbefore'] = 'chars before';
$labels['captchainput'] = '请输入验证码';
$labels['captchafailed'] = '验证码错误';
?>