<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/myrc_sprites/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 01/22/2015 08:06:54
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'MyRoundcube sprity';
$labels['plugindescription'] = 'Pomocný doplněk, který obsahuje sprity a sdílené obrázky, které využívají ostatní doplňky.';

?>