<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/myrc_sprites/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 05/08/2013 03:47:20
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'MyRoundcube sprites';
$labels['plugindescription'] = 'A helper plugin which holds sprites and shared images for other plugins.';

?>