<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/myrc_sprites/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 17:54:50
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Imágenes MyRoundcube';
$labels['plugindescription'] = 'Un complemento auxiliar que contiene imágenes compartidas para distintos complementos.';

?>