<?php

/*
+-----------------------------------------------------------------------+
| language/bg_BG/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['submit'] = 'Добави';
$labels['entersecuritycode'] = 'Въведете код за сигурност';
$labels['reload'] = 'Презареди';
$labels['back'] = 'Назад';
$labels['letters'] = 'Букви';

?>