<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Captcha Udfordring';
$labels['plugindescription'] = 'Forhindre automatiseret software i at udføre handlinger, der nedsætter kvaliteten af din Roundcube service.';
$labels['submit'] = 'Afsend';
$labels['entersecuritycode'] = 'Angiv Sikkerheds Kode';
$labels['reload'] = 'Opdater';
$labels['showriddle'] = 'Klik for at vise gåde';
$labels['hideriddle'] = 'Skjul gåde';
$labels['showphrase'] = 'Vis kode frase';
$labels['back'] = 'Tilbage';
$labels['guess'] = 'Gæt bokstaver og numre (kode frase gåde)';
$labels['andthen'] = 'og så';
$labels['followedby'] = 'efterfuldt af';
$labels['and'] = 'og';
$labels['andnota'] = 'og ikke et';
$labels['but'] = 'men';
$labels['small'] = 'lille';
$labels['letters'] = 'bogstav(er)';
$labels['charsbefore'] = 'tegn før';
$labels['captchainput'] = 'Angiv venligst Sikkerheds Kode';
$labels['captchafailed'] = 'Sikkerheds Koden er ikke ens';

?>