<?php
$labels = array();
$labels['pluginname'] = 'Captcha Challenge';
$labels['plugindescription'] = 'Prevent automated software from performing actions which degrade the quality of your Roundcube service.';
$labels['submit'] = 'Submit';
$labels['entersecuritycode'] = 'Enter Security Code';
$labels['reload'] = 'Reload';
$labels['showriddle'] = 'Click to show Riddle';
$labels['hideriddle'] = 'Hide Riddle';
$labels['showphrase'] = 'Show Pass Phrase';
$labels['back'] = 'Back';
$labels['guess'] = "Guess the letters and\nnumbers (passphrase riddle)";
$labels['andthen'] = 'and then';
$labels['followedby'] = 'followed by';
$labels['and'] = 'and';
$labels['andnota'] = 'and not a';
$labels['but'] = 'but';
$labels['small'] = 'small';
$labels['letters'] = 'letter(s)';
$labels['charsbefore'] = 'chars before';
$labels['captchainput'] = 'Please enter Security Code';
$labels['captchafailed'] = 'Security Code does not match';
?>