<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 10/24/2014 15:06:31
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Captcha';
$labels['plugindescription'] = 'Evitar que software automatizado realice acciones que degraden la calidad de su servicio Roundcube.';
$labels['submit'] = 'Enviar';
$labels['entersecuritycode'] = 'Introduzca el código de seguridad';
$labels['reload'] = 'Recargar';
$labels['showriddle'] = 'Haga clic para mostrar Adivinanza';
$labels['hideriddle'] = 'Ocultar Adivinanza';
$labels['showphrase'] = 'Mostrar Frase';
$labels['back'] = 'Atrás';
$labels['guess'] = 'Adivine las letras ynúmeros (contraseña oculta)';
$labels['andthen'] = 'y luego';
$labels['followedby'] = 'seguido por';
$labels['and'] = 'y';
$labels['andnota'] = 'y no un';
$labels['but'] = 'pero';
$labels['small'] = 'pequeño';
$labels['letters'] = 'carta(s)';
$labels['charsbefore'] = 'caracteres antes';
$labels['captchainput'] = 'Por favor, introduzca el código de seguridad';
$labels['captchafailed'] = 'El código de seguridad no coincide';

?>