<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/it_IT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Roberto - 11/07/2012 09:43:49
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Captcha Challenge';
$labels['plugindescription'] = 'Impedisce a programmi automatici di eseguire azioni che possono degradare la qualità del servizio del tuo Roundcube.';
$labels['submit'] = 'Invia';
$labels['entersecuritycode'] = 'Inserisci Codice di Sicurezza';
$labels['reload'] = 'Ricarica';
$labels['showriddle'] = 'Clicca per mostrare l\'indovinello';
$labels['hideriddle'] = 'Nscondi l\'indovinello';
$labels['showphrase'] = 'Mostra la "pass-phrase"';
$labels['back'] = 'Indietro';
$labels['guess'] = 'Indovina lettere e numeri (frase segreta)';
$labels['andthen'] = 'e poi';
$labels['followedby'] = 'seguito da';
$labels['and'] = 'e';
$labels['andnota'] = 'e non a';
$labels['but'] = 'ma';
$labels['small'] = 'minuscolo';
$labels['letters'] = 'lettera(e)';
$labels['charsbefore'] = 'caratteri prima';
$labels['captchainput'] = 'Per favore inserisci il Codice di Sicurezza';
$labels['captchafailed'] = 'Il Codice di Sicurezza non corrisponde';

?>