<?php

/*
+-----------------------------------------------------------------------+
| language/nl_NL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Captcha uitdaging';
$labels['plugindescription'] = 'Voorkom dat geautomatiseerde software uw Roundcube installatie misbruikt.';
$labels['submit'] = 'Verstuur';
$labels['entersecuritycode'] = 'Beveiligingscode invullen';
$labels['reload'] = 'Herladen';
$labels['showriddle'] = 'Klik voor weergeven raadsel';
$labels['hideriddle'] = 'Verberg raadsel';
$labels['showphrase'] = 'Toon wachtwoordenzin';
$labels['back'] = 'Terug';
$labels['guess'] = 'Raad de letters en nummers (Wachtwoordenzin raadsels) ';
$labels['andthen'] = 'en dan';
$labels['followedby'] = 'gevolgd door';
$labels['and'] = 'en';
$labels['andnota'] = 'en niet een';
$labels['but'] = 'maar';
$labels['small'] = 'klein';
$labels['letters'] = 'letters';
$labels['charsbefore'] = 'Voorloop karakter';
$labels['captchainput'] = 'Beveiligingscode invullen alstublieft';
$labels['captchafailed'] = 'Beveiligingscode komt niet overeen';

?>