<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Pytanie Captcha';
$labels['plugindescription'] = 'Zablokuj spamerów przed wykonywaniem akcji w Roudcube, które mogą pogorszyć działanie usługi Roundcube.';
$labels['submit'] = 'Potwierdź';
$labels['entersecuritycode'] = 'Wpisz kod zabezpieczający';
$labels['reload'] = 'Odświerz';
$labels['showriddle'] = 'Kliknij aby pokazać Zagadkę';
$labels['hideriddle'] = 'Ukryj Zagadkę';
$labels['showphrase'] = 'Pokaż frazę Hasła';
$labels['back'] = 'Powrót';
$labels['guess'] = 'Wpisz litery i cyfry';
$labels['andthen'] = 'i wtedy';
$labels['followedby'] = 'następnie';
$labels['and'] = 'i';
$labels['andnota'] = 'i nie';
$labels['but'] = 'ale';
$labels['small'] = 'małe';
$labels['letters'] = 'litera(y)';
$labels['charsbefore'] = 'znaki przed';
$labels['captchainput'] = 'Proszę wprowadź Kod Bezpieczęństwa';
$labels['captchafailed'] = 'Kod Bezpieczeństwa nie pasuje.';

?>