<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/captcha/localization/pt_BR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: filhocf - 08/24/2012 16:37:36
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Desafio Captcha';
$labels['plugindescription'] = 'Previne softwares automatizados em executar ações para degradar a qualidade do seu serviço Roundcube.';
$labels['submit'] = 'Enviar';
$labels['entersecuritycode'] = 'Digite o código de segurança';
$labels['reload'] = 'Recarregar';
$labels['showriddle'] = 'Clique para mostrar o enigma';
$labels['hideriddle'] = 'Ocultar o enigma';
$labels['showphrase'] = 'Mostrar a senha';
$labels['back'] = 'Voltar';
$labels['guess'] = 'Adivinhe as letras e números (senha enigma)';
$labels['andthen'] = 'e em seguida';
$labels['followedby'] = 'seguido por';
$labels['and'] = 'e';
$labels['andnota'] = 'e não um';
$labels['but'] = 'mas';
$labels['small'] = 'pequeno';
$labels['letters'] = 'cartas(s)';
$labels['charsbefore'] = 'caracteres antes';
$labels['captchainput'] = 'Digite o código de segurança';
$labels['captchafailed'] = 'O código de segurança não combina';

?>