<?php

/*
+-----------------------------------------------------------------------+
| language/de_DE/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Passwortstärke';
$labels['plugindescription'] = 'Hilfsplugin um die Passwortstärke zu ermitteln.';
$labels['pwstrength'] = 'Passwortstärke liegt bei %s%';
$labels['continue'] = 'Passwort ist ausreichend sicher.';
$labels['passwordweak'] = 'Passwort ist zu schwach. Bitte nutze ein sicheres Passwort. Kombinationen aus Klein- und Großbuchstaben, Sonder- und Satzzeichen sowie Zahlen sind sehr sicher und schwierig zu erraten.';

?>