<?php
$labels = array();
$labels['pluginname'] = 'Password strength';
$labels['plugindescription'] = 'Helper plugin to measure password strength.';
$labels['pwstrength'] = 'Password strength is %s%';
$labels['continue'] = 'Password is strong enough.';
$labels['passwordweak'] = 'Password is too weak. Please use a secure pasword. A combination of lower and upper case letters, symbols, numbers and punctuation is highly secure and extremely difficult to guess.';
?>