var cnw_obj;try{cnw_obj=opener&&opener.window&&opener.parent&&opener.window.parent.rcmail?opener.window.parent:opener}catch(e$$8){cnw_obj=opener}
function composenewwindowcommandcaller(a,c,b){switch(a){case "compose":var d="";switch(rcmail.env.task){case "mail":c&&(d="&_to="+c);opencomposewindow("./?_task=mail&_action=compose&_mbox="+urlencode(rcmail.env.mailbox)+d);break;case "addressbook":if(c)" "!=c&&(d="&_to="+c),opencomposewindow("./?_task=mail&_action=compose"+d);else{var f,e=[];if(rcmail.contact_list){var g=rcmail.contact_list.get_selection(),d=0;for(f=g.length;d<f;d++)e.push(g[d])}e.length?(b="_cid="+e.join(",")+"&_source="+rcmail.env.source,
opencomposewindow("./?_task=addressbook&_action=mailto&"+b)):rcmail.command(a,c,b)}break;default:opencomposewindow("./?_task=mail&_action=compose")}break;case "reply-list":case "reply-all":case "reply":if(b=rcmail.get_single_uid())b="_reply_uid="+b+"&_mbox="+urlencode(rcmail.env.mailbox),"reply-all"==a?b+="&_all="+(!c&&rcmail.commands["reply-list"]?"list":"all"):"reply-list"==a&&(b+="&_all=list"),opencomposewindow("./?_task=mail&_action=compose&"+b);break;case "forward-attachment":case "forward":if(b=
rcmail.get_single_uid()){b="_forward_uid="+b+"&_mbox="+urlencode(rcmail.env.mailbox);if("forward-attachment"==a||!c&&rcmail.env.forward_attachment)b+="&_attachment=1";opencomposewindow("./?_task=mail&_action=compose&"+b)}1<rcmail.message_list.get_selection().length&&"function"==typeof rcmail_forwardatt_url&&(b=rcmail_forwardatt_url(c),opencomposewindow("./?_task=mail&_action=plugin.forwardatt&"+b));break;case "edit":cid=rcmail.get_single_uid(),b=rcmail.env.mailbox==rcmail.env.drafts_mailbox?"_draft_uid=":
"_uid=",opencomposewindow("./?task=mail&_action=compose&"+b+cid+"&_mbox="+urlencode(rcmail.env.mailbox))}return!1}function opencomposewindow(a){var c=Math.min(screen.width-20,1400),b=screen.left?screen.left:0,d=screen.top?screen.top:0,f=(screen.width-c)/2+b,e=(screen.height-800)/2+d-50,e=e<d?d:e,f=f<b?b:f,a=a.replace("_mbox=undefined","_mbox=INBOX"),a=window.open(a,"","scrollbars=no,width="+c+",height=800,top="+e+",left="+f);a.focus();return a}
function opencomposewindowcaller(a){window.opener?(a=opener.document.referrer,a=-1<a.indexOf("_task=mail")?"./?_task=mail":a,cnw_obj.rcmail.env.task==rcmail.env.task&&cnw_obj.rcmail.env.action==rcmail.env.action&&(window.opener.$("html").html(""),cnw_obj.location.href=a),$(window).bind("blur",function(){self.focus()}),$("body").bind("mouseover click keypress",function(){$(window).unbind("blur")}),$(window).unload(function(){(cnw_obj.$("#mailboxlist-container").html()||cnw_obj.$("#mailboxcontainer").html())&&
cnw_obj.rcmail.list_mailbox(cnw_obj.rcmail.env.mailbox,cnw_obj.rcmail.env.current_page);self.close()}),rcmail.addEventListener("actionafter",function(a){a.action=="savedraft"&&window.setTimeout("cnw_obj.rcmail.command('list');",2E3)})):rcmail.env.compose_window=opencomposewindow(a)}
$(document).ready(function(){window.rcmail&&rcmail.gui_objects.messagelist&&rcmail.addEventListener("insertrow",function(a){rcmail.env.drafts_mailbox==rcmail.env.mailbox&&($("#rcmrow"+a.uid+" > td").bind("dblclick",function(){rcmail.mddetect=!0}),$("#rcmrow"+a.uid+" > td").bind("mousedown",function(){rcmail.dblclick_detect&&(new Date).getTime()-rcmail.dblclick_detect<=rcmail.message_list.dblclick_time?(rcmail.dblclick_cancel=!0,composenewwindowcommandcaller("edit"),$(document).mousemove(function(){$("#rcmdraglayer").css("display",
"none")})):(rcmail.dblclick_detect=(new Date).getTime(),$(document).unbind("mousemove"))}),$("#rcmrow"+a.uid+" > td").bind("mouseup",function(a){rcmail.dblclick_cancel&&(rcube_event.cancel(a),rcmail.dblclick_cancel=!1)}))})});
