<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/calendar/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: intio.nl (info@intio.nl) - 04/03/2015 12:30:16
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['default_view'] = 'Standaard agenda';
$labels['time_format'] = 'Tijdsformaat';
$labels['timeslots'] = 'Timeslots per uur';
$labels['first_day'] = 'Eerste weekdag';
$labels['first_hour'] = 'Eerste uur tonen';
$labels['workinghours'] = 'Werkuren';
$labels['add_category'] = 'Categorie toevoegen';
$labels['remove_category'] = 'Categorie verwijderen';
$labels['defaultcalendar'] = 'Maak nieuwe gebeurtenis in';
$labels['eventcoloring'] = 'Gebeurtenis kleur';
$labels['coloringmode0'] = 'Volgens de kalender';
$labels['coloringmode1'] = 'Volgens categorie';
$labels['coloringmode2'] = 'Kalender voor het overzicht, categorie voor de inhoud';
$labels['coloringmode3'] = 'Categorie voor overzicht, kalender voor de inhoud';
$labels['calendar'] = 'Agenda';
$labels['calendars'] = 'Kalenders';
$labels['category'] = 'Categorie';
$labels['categories'] = 'Categorieën';
$labels['createcalendar'] = 'Maak een nieuwe kalender';
$labels['editcalendar'] = 'Kalender eigenschappen bewerken';
$labels['name'] = 'Naam';
$labels['color'] = 'Kleur';
$labels['day'] = 'Dag';
$labels['week'] = 'Week';
$labels['month'] = 'Maand';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nieuw';
$labels['new_event'] = 'Nieuw evenement';
$labels['edit_event'] = 'Wijzig evenement';
$labels['edit'] = 'Wijzig';
$labels['save'] = 'Bewaar';
$labels['remove'] = 'Verwijder';
$labels['cancel'] = 'Terug';
$labels['select'] = 'Selecteer';
$labels['print'] = 'Print';
$labels['printtitle'] = 'Print kalender';
$labels['title'] = 'Samenvatting';
$labels['description'] = 'Beschrijving';
$labels['all-day'] = 'hele dag';
$labels['export'] = 'Exporteer naar ICS';
$labels['exporttitle'] = 'Exporteer naar iCalendar';
$labels['exportrange'] = 'Gebeurtenissen van';
$labels['exportattachments'] = 'Met bijlagen';
$labels['customdate'] = 'Aangepaste datum';
$labels['location'] = 'Locatie';
$labels['url'] = 'URL';
$labels['date'] = 'Datum';
$labels['start'] = 'Start';
$labels['end'] = 'Eind';
$labels['selectdate'] = 'Kies datum';
$labels['freebusy'] = 'Toon mij als';
$labels['free'] = 'Vrij';
$labels['busy'] = 'Bezet';
$labels['outofoffice'] = 'Out of Office';
$labels['tentative'] = 'Voorlopig';
$labels['priority'] = 'Prioriteit';
$labels['sensitivity'] = 'Privacy';
$labels['public'] = 'Openbaar';
$labels['private'] = 'Privé';
$labels['confidential'] = 'Vertrouwelijk';
$labels['alarms'] = 'Herinnering';
$labels['generated'] = 'Gegenereerd op';
$labels['printdescriptions'] = 'Print omschrijvingen';
$labels['parentcalendar'] = 'In te voegen in';
$labels['searchearlierdates'] = '« Zoeken naar eerdere gebeurtenissen';
$labels['searchlaterdates'] = 'Zoeken naar latere gebeurtenissen »';
$labels['andnmore'] = '$nr meer...';
$labels['togglerole'] = 'Klik om de rol te schakelen';
$labels['createfrommail'] = 'Opslaan als gebeurtenis';
$labels['importevents'] = 'Gebeurtenissen importeren';
$labels['importrange'] = 'Gebeurtenissen van';
$labels['onemonthback'] = '1 maand terug';
$labels['nmonthsback'] = '$nr maanden terug';
$labels['showurl'] = 'Toon kalender URL';
$labels['listrange'] = 'Weergave bereik:';
$labels['listsections'] = 'Verdeel in:';
$labels['smartsections'] = 'Slimme secties';
$labels['until'] = 'tot';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['thisweek'] = 'Deze week';
$labels['nextweek'] = 'Volgende week';
$labels['thismonth'] = 'Deze maand';
$labels['nextmonth'] = 'Volgende maand';
$labels['weekofyear'] = 'Week';
$labels['pastevents'] = 'Verleden';
$labels['futureevents'] = 'Toekomst';
$labels['showalarms'] = 'Toon alarmen';
$labels['defaultalarmtype'] = 'Standaardinstelling herinnering';
$labels['defaultalarmoffset'] = 'Standaardherinneringstijd';
$labels['attendee'] = 'Deelnemer';
$labels['role'] = 'Role';
$labels['availability'] = 'Beschikbaar';
$labels['confirmstate'] = 'Status';
$labels['addattendee'] = 'Deelnemer toevoegen';
$labels['roleorganizer'] = 'Organisator';
$labels['rolerequired'] = 'Vereist';
$labels['roleoptional'] = 'Optioneel';
$labels['cutypegroup'] = 'Groep';
$labels['cutyperoom'] = 'Kamer';
$labels['availfree'] = 'Vrij';
$labels['availbusy'] = 'Bezet';
$labels['availunknown'] = 'Onbekend';
$labels['first'] = 'eerste';
$labels['second'] = 'tweede';
$labels['third'] = 'derde';
$labels['fourth'] = 'vierde';
$labels['last'] = 'laatste';
$labels['dayofmonth'] = 'Dag van de maand';
$labels['changeeventconfirm'] = 'Wijzig gebeurtenis';
$labels['removeeventconfirm'] = 'Verwijder gebeurtenis';
$labels['currentevent'] = 'Huidige';
$labels['futurevents'] = 'Toekomst';
$labels['allevents'] = 'Alles';
$labels['saveasnew'] = 'Opslaan als nieuw';

?>