<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/fileapi_attachments/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 08/31/2012 06:36:01
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['dragupload'] = 'Arrastre archivos adjuntos';
$labels['pluginname'] = 'Arrastrar y Soltar';
$labels['plugindescription'] = 'Agregar archivos adjuntos arrastrando y soltando en la ventana de redacción.';
?>