<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/fileapi_attachments/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 09/21/2012 13:23:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['dragupload'] = 'Coller des fichiers joints';
$labels['pluginname'] = 'Copier & coller des fichiers joints';
$labels['plugindescription'] = 'Ajouter des fichiers joints en déplacant ceux-ci dans la fenêtre de composition de mail';

?>