<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: www.aspHOSTpage.com                                           |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['dragupload'] = 'Fájl behúzása (Drag & Drop)';
$labels['pluginname'] = 'Drag & Drop melléklet';
$labels['plugindescription'] = 'Melléklet hozzáadása Drag & Drop (fogd és vidd) technikával.';

?>