<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/fileapi_attachments/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: HiJack! - 09/21/2012 11:23:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['dragupload'] = 'Bijlage(s) verslepen en neerzetten';
$labels['pluginname'] = 'Verslepen en neerzetten';
$labels['plugindescription'] = 'Voeg bijlage(s) toe door deze  te te slepen en neer te zetten in het venster bij het aanmaken van een nieuw bericht.';

?>