<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['dragupload'] = 'Upuśc załączniki';
$labels['pluginname'] = 'Złap i upuść Załączniki';
$labels['plugindescription'] = 'Dodaj załączniki poprzez przeciągnięcie i upuszczenie ich w oknie wiadomości.';

?>