<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/fileapi_attachments/localization/pt_BR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: filhocf - 08/24/2012 16:37:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['dragupload'] = 'Descartar anexos';

?>