<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/fileapi_attachments/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: JG - 09/12/2012 12:28:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['dragupload'] = 'Largar ficheiros';
$labels['pluginname'] = 'Arrastar e Largar anexos';
$labels['plugindescription'] = 'Adicionar anexos através da funcionalidade "Arrastar e Largar" na janela de composição da mensagem.';
?>