<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Evita Keyloggers';
$labels['plugindescription'] = 'Afegeix un teclat virtual per introduir contrasenyes. És ideal per prevenir que malware (keyloggers) registrin la vostra contrasenya com pot passar si escriviu fent servir un teclat convencional.';
$labels['vk00'] = 'Interfície de Teclat Virtual';
$labels['vk01'] = 'Mostra interfície de teclat virtual';
$labels['vk02'] = 'Selecciona la disposició del teclat';
$labels['vk03'] = 'Tecles Inactives';
$labels['vk04'] = 'Activa';
$labels['vk05'] = 'Desactiva';
$labels['vk06'] = 'Tanca el Teclat';
$labels['vk07'] = 'Suprimeix';
$labels['vk08'] = 'Neteja tota l\'entrada';
$labels['vk09'] = 'Versió';
$labels['vk10'] = 'Ajusta la mida del teclat';

?>