<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/vkeyboard/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/04/2014 13:27:06
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Virtuální klávesnice';
$labels['plugindescription'] = 'Přidá virtuální klávesnici pro zadání hesla při přihlašování. Ideální jako prevence proti odposlechu klávesnice při přihlašování na nedůvěryhodných počítačích.';
$labels['vk00'] = 'Virtuální klávesnice';
$labels['vk01'] = 'Zobraz virtuální klávesnici';
$labels['vk02'] = 'Vyberte rozložení klávesnice';
$labels['vk03'] = 'Mrtvé klávesy';
$labels['vk04'] = 'On';
$labels['vk05'] = 'Off';
$labels['vk06'] = 'Zavřít klávesnici';
$labels['vk07'] = 'Vymazat';
$labels['vk08'] = 'Vymazat vstup';
$labels['vk09'] = 'Verze';
$labels['vk10'] = 'Změnit velikost klávesnice';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '↵ ';
$labels['bksp'] = '←';

?>