<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ondrej Krejcik <ondra@tachec.org>                             |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Virtuální klávesnice';
$labels['plugindescription'] = 'Přidá virtuální klávesnici pro zadání hesla při přihlašování. Ideální jako prevence proti odposlechu klávesnice při přihlašování na nedůvěryhodných počítačích.';
$labels['vk00'] = 'Virtuální klávesnice';
$labels['vk01'] = 'Zobraz virtuální klávesnici';
$labels['vk02'] = 'Vyberte rozložení klávesnice';
$labels['vk03'] = 'Mrtvé klávesy';
$labels['vk04'] = 'On';
$labels['vk05'] = 'Off';
$labels['vk06'] = 'Zavřít klávesnici';
$labels['vk07'] = 'Vymazat';
$labels['vk08'] = 'Vymazat vstup';
$labels['vk09'] = 'Verze';
$labels['vk10'] = 'Změnit velikost klávesnice';

?>