<?php

$labels = array();
$labels['pluginname'] = 'Passwörter per Maus eingeben';
$labels['plugindescription'] = 'Geben sie Passwörter mit einer virtuellen Tastatur ein und vermeiden Sie so, dass Malware auf öffentlichen Computern die Tastatureingaben aufzeichnet und so möglicherweise Ihre Passwörter missbraucht werden.';
$labels['vk00'] = 'Virtuelle Tastatur';
$labels['vk01'] = 'Virtuelle Tastatur öffnen';
$labels['vk02'] = 'Layout auswählen';
$labels['vk03'] = 'Dead Keys';
$labels['vk04'] = 'An';
$labels['vk05'] = 'Aus';
$labels['vk06'] = 'Virtuelle Tastatur schliessen';
$labels['vk07'] = 'Löschen';
$labels['vk08'] = 'Eingabe Löschen';
$labels['vk09'] = 'Version';
$labels['vk10'] = 'Größe anpassen';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '↵';
$labels['bksp'] = '←';

?>