<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/vkeyboard/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:36:19
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Prevent Keyloggers';
$labels['plugindescription'] = 'Add a virtual keyboard to enter passwords. Ideal for preventing malware (keyloggers) from logging...';
$labels['vk00'] = 'Virtual Keyboard Interface';
$labels['vk01'] = 'Display virtual keyboard interface';
$labels['vk02'] = 'Select keyboard layout';
$labels['vk03'] = 'Dead keys';
$labels['vk04'] = 'On';
$labels['vk05'] = 'Off';
$labels['vk06'] = 'Close the keyboard';
$labels['vk07'] = 'Clear';
$labels['vk08'] = 'Clear this input';
$labels['vk09'] = 'Version';
$labels['vk10'] = 'Adjust keyboard size';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '  ↵  ';
$labels['bksp'] = '  ←  ';

?>