<?php
/* Author: Yoni <yoni@unlockforus.com> - Courtesy <www.unlockforus.com> */
$labels = array();
$labels['pluginname'] = 'Evitar Keyloggers';
$labels['plugindescription'] = 'Añadir un teclado virtual para introducir contraseñas. Ideal para prevenir que malware (keyloggers) registren su contraseña como sucede mientras escribe utilizando el teclado tradicional.';
$labels['vk00'] = 'Interfaz de Teclado Virtual';
$labels['vk01'] = 'Mostrar interfaz de teclado virtual';
$labels['vk02'] = 'Seleccionar disposición de teclado';
$labels['vk03'] = 'Teclas Inactivas';
$labels['vk04'] = 'Activar';
$labels['vk05'] = 'Desactivar';
$labels['vk06'] = 'Cerrar el Teclado';
$labels['vk07'] = 'Borrar';
$labels['vk08'] = 'Borrar esta entrada';
$labels['vk09'] = 'Versión';
$labels['vk10'] = 'Ajustar el tamaño del teclado';

/* Do not translate the following labels */
$labels['shift'] = '?';
$labels['tab'] = '?';
$labels['caps'] = '?';
$labels['enter'] = '  ?  ';
$labels['bksp'] = '  ?  ';
?>