<?php
/*
+-----------------------------------------------------------------------+
| ./plugins/vkeyboard/localization/fr_FR.inc
|
| Language file of MyRoundcube Plugins Bundle
| Copyright (C) 2010-2012, Roland 'rosali' Liebl
| Licensed under the GNU GPL
|
+-----------------------------------------------------------------------+
| Author: hugues@mail4us.net - 03/31/2012 15:37:19
+-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Éviter les keyloggers';
$labels['plugindescription'] = 'Ajoutez un clavier virtuel pour introduire votre mot de passe. Idéal pour prévenir les malware et autres virus (keyloggers) d\'enregistrer votre mot de passe quand vous utilisez votre clavier traditionnel';
$labels['vk00'] = 'Interface de clavier virtuel';
$labels['vk01'] = 'Affiche l\'interface de clavier virtuel';
$labels['vk02'] = 'Choisissez votre clavier';
$labels['vk03'] = 'Clé morte';
$labels['vk04'] = 'On';
$labels['vk05'] = 'Off';
$labels['vk06'] = 'Fermer le clavier';
$labels['vk07'] = 'Effacer';
$labels['vk08'] = 'Effacer l\'entrée';
$labels['vk09'] = 'Version';
$labels['vk10'] = 'Ajuster la taille du clavier';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '  ↵  ';
$labels['bksp'] = '  ←  ';

?>