<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/vkeyboard/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: HiJack! - 03/27/2012 21:38:06
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Virtueel toetsenbord';
$labels['plugindescription'] = 'Voeg een virtueel toetsenbord toe als er wachtwoorden dienen te worden ingevoerd (om keyloggers tegen te gaan).';
$labels['vk00'] = 'Virtueel toetsenbord';
$labels['vk01'] = 'Virtueel toetsenbord starten';
$labels['vk02'] = 'Selecteer toetsenbord layout';
$labels['vk03'] = 'Dode toetsen';
$labels['vk04'] = 'Aan';
$labels['vk05'] = 'Uit';
$labels['vk06'] = 'Sluit het toetsenbord';
$labels['vk07'] = 'Wissen';
$labels['vk08'] = 'Wis invoer';
$labels['vk09'] = 'Versie';
$labels['vk10'] = 'Toetsenbordgrootte aanpassen';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '↵ ';
$labels['bksp'] = '← ';

?>