<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                              |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['pluginname'] = 'Previve Keyloggers';
$labels['plugindescription'] = 'Adiciona um teclado virtual para digitar senhas. Oideal para prevenir malwares (keyloggers) de registrar a senha que você digitou usando seu teclado tradicional.';
$labels['vk00'] = 'Interface do teclado virtual';
$labels['vk01'] = 'Mostrar interface do teclado virtual';
$labels['vk02'] = 'Selecionar o leiaute do teclado';
$labels['vk03'] = 'Teclas mortas';
$labels['vk04'] = 'Ativar';
$labels['vk05'] = 'Desativar';
$labels['vk06'] = 'Fechar o teclaro';
$labels['vk07'] = 'Limpar';
$labels['vk08'] = 'Limpar essa entrada';
$labels['vk09'] = 'Versão';
$labels['vk10'] = 'Ajustar o tamanho do teclado';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '  ↵  ';
$labels['bksp'] = '  ←  ';

