<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/libgpl/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 01/22/2015 08:02:38
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['calendar_caldav'] = 'CalDAV kalendář';
$labels['calendar_kolab'] = 'Kolab kalendář';
$labels['calendar_database'] = 'lokální kalendář';
$labels['calendar_ical'] = 'iCAL kalendář';
$labels['calendar_google_xml'] = 'Google XML kalendář';
$labels['sync_interval'] = 'Synchronizovat každých';
$labels['minute_s'] = 'minut(y)';
$labels['tasks'] = 'Úkoly';
$labels['errorimportingtask'] = 'Nepodařilo se naimportovat úkoly';
$labels['treat_as_allday'] = 'Zobrazit událost jako celodenní pokud trvá déle než';
$labels['hours'] = 'Hodin';
$labels['movetotasks'] = 'Přesunout do úkolů';
$labels['movetocalendar'] = 'Přesunout do kalendáře';
$labels['emailevent'] = 'Poslat událost';
$labels['emailnote'] = 'Poslat poznámku';
$labels['emailtask'] = 'Poslat úkol';
$labels['movetonotes'] = 'Přesunout do poznámek';
$labels['quit'] = 'Ukončit';
$labels['eventaction'] = 'Akce události...';
$labels['googledisabled'] = 'Povolte prosím přístup k vašemu účtu Google (přejděte na "Nastavení" -> "Správa účtu" -> "Další nastavení účtu" a proveďte patřičná nastavení).';
$labels['googledisabled_redirect'] = 'Povolte prosím přístup k vašemu účtu Google.';
$labels['allowfreebusy'] = 'Povolit požadavek na obsazenost';
$labels['freebusy'] = 'Obsazenost';
$labels['unabletoadddefaultcalendars'] = 'Nelze přidat výchozí kalendář';
$labels['taskaction'] = 'Akce úkolu...';
$labels['due'] = ' ';
$labels['is_subtask'] = 'Dílčí úkol';
$labels['subscribe'] = 'Abyste mohli vytvářet úkoly, tak si je prosím povolte ve svém kalendáři.';
$labels['subscribed'] = 'Přihlášeno';
$labels['tags'] = 'Kategorie';
$labels['list'] = 'Kalendář';
$labels['editlist'] = 'Upravit kalendář';
$labels['synchronize'] = 'Synchronizovat';
$labels['submenuprefix'] = '»';
$labels['birthdays'] = 'Narozeniny';
$labels['birthdayof'] = 'narozeniny';
$labels['showbirthdays'] = 'Zobrazit narozeniny';
$labels['sameday'] = 'V den narozenin';
$labels['onedaybefore'] = 'Den před narozeninami';
$labels['twodaysbefore'] = 'Dva dny před narozeninami';
$labels['threedaysbefore'] = 'Tři dny před narozeninami';
$labels['happybirthday'] = 'Všechno nejlepší k narozeninám';
$labels['birthdaygreetings'] = 'Sestavit blahopřání k narozeninám';
$labels['sql'] = 'Osobní';
$labels['url'] = 'URL';
$labels['no_google_xml'] = 'Toto není Google XML Feed URL';
$labels['click_here'] = 'Klikněte zde';
$labels['reminder'] = 'Upomínka';
$labels['reminderfooter_event'] = 'Obdrželi jste tento e-mail, protože jste chtěli být informováni o nadcházející události ve vašem kalendáři.';
$labels['reminderfooter_task'] = 'Obdrželi jste tento e-mail, protože jste chtěli být informováni o nadcházejícím úkolu z vašeho seznamu úkolů.';
$labels['participiants'] = 'účastníci';
$labels['ACCEPTED'] = 'přijat';
$labels['NEEDS-ACTION'] = 'očekávaný';
$labels['CONFIRMED'] = 'potvrzen';
$labels['TENTATIVE'] = 'možný';
$labels['DECLINED'] = 'odmítnut';
$labels['attachments'] = 'Přílohy';
$labels['highest'] = 'nejvyšší';
$labels['high'] = 'vysoká';
$labels['normal'] = 'normální';
$labels['low'] = 'nízká';
$labels['lowest'] = 'nejnižší';
$labels['minical'] = 'Zobrazit mini kalendář';
$labels['playsound'] = 'z';
$labels['confidentialcaldavaccess'] = 'Důvěrný CalDAV přístup [%s]';
$labels['readwrite'] = 'číst/zapisovat';
$labels['readonly'] = 'pouze číst';
$labels['isenabled'] = 'povolen';
$labels['isdisabled'] = 'zakázán';
$labels['caltoken'] = 'Token';
$labels['share'] = 'Sdílet';
$labels['sharing'] = 'Sdílení';
$labels['resource'] = 'Zdroj';
$labels['shareinvitation'] = 'Poslat pozvánku';
$labels['sharehint'] = 'Výše uvedené údaje (uživatelské jméno, heslo (Token) a adresy URL) poskytněte ostatním, aby mohli sdílet vaše kalendáře. Tyto informace umožňují přístup pro čtení i zápis. Pro zamezení přístupu změňte token nebo jej smažte.';
$labels['sharehint_readonly'] = 'Výše uvedené údaje (uživatelské jméno, heslo (Token) a adresy URL) poskytněte ostatním, aby mohli sdílet vaše kalendáře. Tyto informace umožňují pouze přístup pro čtení. Pro zamezení přístupu změňte token nebo jej smažte.';
$labels['copytoclipboard'] = 'Zkopírovat do schránky';
$labels['copiedtoclipboard'] = 'Zkopírováno do schránky';
$labels['checkresources'] = 'Kontrola zdrojů';
$labels['checkatleastoneresource'] = 'Zkontrolujte prosím alespoň jeden zdroj';
$labels['send'] = 'Poslat';
$labels['cancel'] = 'Zrušit';
$labels['access'] = 'Přístup';
$labels['invitationsubject'] = '%s vám nabízí přístup do CalDAV kalendáře';
$labels['tutorials'] = 'Návody';
$labels['gotodate'] = 'Jít na datum';
$labels['overview'] = 'Přehled';
$labels['close'] = 'Zavřít';
$labels['restore'] = 'Obnovit všechny položky';
$labels['history'] = 'Historie';
$labels['forward'] = 'dopředu';
$labels['back'] = 'zpět';
$labels['caldav_notify'] = 'Odeslat e-mail při změně události';
$labels['cal_notify_to'] = 'Příjemce';
$labels['events'] = 'Události';
$labels['export'] = 'Export';
$labels['custommail'] = 'Naplánovat vlastní e-mail';
$labels['sounds'] = 'Zvuky';
$labels['play'] = 'přehrát';
$labels['nodefaultcalendar'] = 'Vyberte prosím výchozí kalendář v konfiguraci kalendáře.';

?>