<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/libgpl/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 03/16/2015 08:03:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['calendar_caldav'] = 'CalDAV kalenteri';
$labels['calendar_kolab'] = 'Kolab kalenteri';
$labels['calendar_database'] = 'Paikallinen kalenteri';
$labels['calendar_ical'] = 'iCal kalenteri';
$labels['calendar_webcal'] = 'WebCAL kalenteri';
$labels['calendar_google_xml'] = 'Google XML kalenteri';
$labels['sync_interval'] = 'Synkronisointi joka';
$labels['minute_s'] = 'minuutti(a)';
$labels['events'] = 'tapahtumat';
$labels['tasks'] = 'Tehtävät';
$labels['errorimportingtask'] = 'Tehtävän tuonti epäonnistui';
$labels['treat_as_allday'] = 'Näytä tapahtumat koko päivän tapahtumana jos ne kestävät enemmän kuin';
$labels['hours'] = 'Tuntia';
$labels['movetotasks'] = 'Siirrä tehtäviin';
$labels['movetocalendar'] = 'Siirrä kalenteriin';
$labels['emailevent'] = 'Lähetä tapahtuma';
$labels['emailnote'] = 'Lähetä viesti';
$labels['emailtask'] = 'Lähetä tehtävä';
$labels['movetonotes'] = 'Siirrä muistioon';
$labels['quit'] = 'Poistu';
$labels['eventaction'] = 'Tapahtuman toiminto...';
$labels['googledisabled'] = 'Anna valtuutus Google tilille ("Asetukset" -> "Tilin hallinta" -> "Muut tilin asetukset")';
$labels['googledisabled_redirect'] = 'Anna valtuutus Google tilillesi';
$labels['allowfreebusy'] = 'Salli freebusy pyynnöt';
$labels['freebusy'] = 'Freebusy';
$labels['unabletoadddefaultcalendars'] = 'Oletuskalenterien lisäys epäonnistui';
$labels['taskaction'] = 'Tehtävän toiminto...';
$labels['due'] = 'valmistuu';
$labels['is_subtask'] = 'Alatehtävä';
$labels['subscribe'] = 'Tee tilaus kalenteriin jotta voit luoda tehtäviä.';
$labels['subscribed'] = 'Tilattu';
$labels['tags'] = 'Kategoriat';
$labels['list'] = 'Kalenteri';
$labels['editlist'] = 'Muokkaa kalenteria';
$labels['synchronize'] = 'Synkronoi';
$labels['submenuprefix'] = '»';
$labels['birthdays'] = 'Syntymäpäivät';
$labels['birthdayof'] = 'syntymäpäivät';
$labels['showbirthdays'] = 'Näytä syntymäpäivät';
$labels['sameday'] = 'Syntymäpäivänä';
$labels['onedaybefore'] = 'Päivä ennen syntymäpäivää';
$labels['twodaysbefore'] = 'Kaksi päivää ennen syntymäpäivää';
$labels['threedaysbefore'] = 'Kolme päivää ennen syntymäpäivää';
$labels['happybirthday'] = 'Hyvää Syntymäpäivää';
$labels['birthdaygreetings'] = 'Luo syntymäpäivä tervehdyksiä';
$labels['sql'] = 'Yksityinen';
$labels['url'] = 'URL';
$labels['no_google_xml'] = 'Tämä ei ol Google XML syöte';
$labels['click_here'] = 'Klikkaa tästä';
$labels['reminder'] = 'Muistutus';
$labels['reminderfooter_event'] = 'Sait tämän viestin koska olet pyytänyt muistutusta tulevasta tapahtumassa kalenterissasi.';
$labels['reminderfooter_task'] = 'Sait tämän viestin koska olet pyytänyt muistutusta tulevasta tehtävästä tehtävälistassasi.';
$labels['participiants'] = 'Osallistujat';
$labels['ACCEPTED'] = 'hyväksytty';
$labels['NEEDS-ACTION'] = 'odottaa';
$labels['CONFIRMED'] = 'varmistettu';
$labels['TENTATIVE'] = 'ehkä';
$labels['DECLINED'] = 'kieltäydytty';
$labels['attachments'] = 'Liitteet';
$labels['highest'] = 'korkein';
$labels['high'] = 'korkea';
$labels['normal'] = 'normaali';
$labels['low'] = 'alhainen';
$labels['lowest'] = 'alhaisin';
$labels['minical'] = 'Näytä minikalenteri';
$labels['playsound'] = 'Soita ääni tulevien tapahtuin muistutuksissa';
$labels['caldavaccess'] = 'Luottamuksellinen CadDAV käyttöoikeus';
$labels['readwrite'] = 'luku/kirjoitus';
$labels['readonly'] = 'vain luku';
$labels['isenabled'] = 'on päällä';
$labels['isdisabled'] = 'on pois päältä';
$labels['caltoken'] = 'Token';
$labels['share'] = 'Jaa';
$labels['sharing'] = 'Jakaminen';
$labels['resource'] = 'Resurssi';
$labels['shareinvitation'] = 'Lähetä kutsu';
$labels['sharehint'] = 'Anna seuraavat tiedot (Käyttäjänimi, Salasana (Token) ja URLit) jottaitoiset pääsevät jaettuihin kalentereihisi<br>Nämä tiedot antavat luku- ja kirjoitusoikeudet. Muuta tai poista token poistaaksesi pääsyn.';
$labels['sharehint_readonly'] = 'Anna seuraavat tiedot (Käyttäjänimi, Salasana (Token) ja URLit) jottaitoiset pääsevät jaettuihin kalentereihisi<br>Nämä tiedot antavat lukuoikeudet. Muuta tai poista token poistaaksesi pääsyn.';
$labels['copytoclipboard'] = 'Kopioi leikepöydälle';
$labels['copiedtoclipboard'] = 'Kopioitu leikepöydälle';
$labels['checkresources'] = 'Tarkista resurssit';
$labels['checkatleastoneresource'] = 'Ruksi ainakin yksi resurssi';
$labels['send'] = 'Lähetä';
$labels['cancel'] = 'Peruuta';
$labels['access'] = 'Pääsy';
$labels['invitationsubject'] = '%s kutsuu sinut pääsyyn CalDAV kalentereihin';
$labels['tutorials'] = 'Ohjekirjat';
$labels['gotodate'] = 'Mene päivään';
$labels['overview'] = 'Yleiskatsaus';
$labels['close'] = 'Sulje';
$labels['restore'] = 'Palauta kaikki';
$labels['history'] = 'Historia';
$labels['forward'] = 'eteenpäin';
$labels['back'] = 'taaksepäin';
$labels['caldav_notify'] = 'Lähetä viesti kun tapahtumia on muokannut osallistuja.';
$labels['cal_notify_to'] = 'Saaja';
$labels['events'] = 'Tapahtumat';
$labels['export'] = 'Vienti';
$labels['custommail'] = 'Aikatauluta sähköpostiviesti';
$labels['sounds'] = 'Äänet';
$labels['play'] = 'soita';
$labels['nodefaultcalendar'] = 'Valitse oletuskalenteri kalenteriasetuksista.';
$labels['due'] = 'Valmistuu';
$labels['defaultbackgroundcolor'] = 'Luku/kirjoitus tapahtumien oletus taustaväri';
$labels['defaultreadonlybackgroundcolor'] = 'Vain luku tapahtumien oletus taustaväri';
$labels['fontcolor'] = 'Fontin väri';
$labels['blackwhite'] = 'musta/valkoinen';
$labels['black'] = 'musta';
$labels['white'] = 'valkoinen';
$labels['complementary'] = 'täydentävä';
?>