<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Календарь +';
$labels['plugindescription'] = 'Добавляет расширенный функционал к плагину Календарь (CalDAV, расширенные опции печати, импорт событий из vcf, показывает маленький календарь в списке сообщений, показывает дни рождения, общий доступ к календарям, потоки, фильтр событий, поиск)';
$labels['synchronize'] = 'Синхронизировать';
$labels['submenuprefix'] = '>>';
$labels['birthdays'] = 'Дни рождения';
$labels['birthdayof'] = 'день рождения';
$labels['showbirthdays'] = 'Показывать дни рождения';
$labels['sameday'] = 'В день рождения';
$labels['onedaybefore'] = 'За день до дня рождения';
$labels['twodaysbefore'] = 'За два дня до дня рождения';
$labels['threedaysbefore'] = 'За три дня до дня рождения';
$labels['happybirthday'] = 'С Днём рождения!';
$labels['birthdaygreetings'] = 'Сочинить поздравлению с днём рождения';
$labels['sql'] = 'Личное';
$labels['url'] = 'URL';
$labels['no_google_xml'] = 'Это не XML Google feed';
$labels['click_here'] = 'Кликните здесь';
$labels['reminder'] = 'Напоминание';
$labels['reminderfooter_event'] = 'Вы получили это письмо, потому что запросили напоминание об этом грядущем событии в вашем календаре';
$labels['reminderfooter_task'] = 'Вы получили это письмо, потому что запросили напоминание об этом грядущем событии в вашем списке задач';
$labels['participiants'] = 'Участники';
$labels['ACCEPTED'] = 'принято';
$labels['NEEDS-ACTION'] = 'ждёт';
$labels['CONFIRMED'] = 'подтверждено';
$labels['TENTATIVE'] = 'может быть';
$labels['DECLINED'] = 'отвергнуто';
$labels['attachments'] = 'Приложения';
$labels['highest'] = 'высший';
$labels['high'] = 'высокий';
$labels['normal'] = 'обычный';
$labels['low'] = 'низкий';
$labels['lowest'] = 'низший';
$labels['minical'] = 'Показать мини-календарь';
$labels['playsound'] = 'Озвучивать напоминания о предстоящих событиях';
$labels['caldavaccess'] = 'Закрытый доступ к CalDAV';
$labels['readwrite'] = 'Доступ на чтение и запись';
$labels['readonly'] = 'Доступ только на чтение';
$labels['isenabled'] = 'включено';
$labels['isdisabled'] = 'выключено';
$labels['caltoken'] = 'Ключ';
$labels['share'] = 'Поделиться';
$labels['sharing'] = 'Общий доступ';
$labels['resource'] = 'Ресурс';
$labels['shareinvitation'] = 'Послать приглашение';
$labels['sharehint'] = 'Приведете информацию, описанную выше (Логин, пароль (ключ) и URL) для других для соединения к вашим разделенным календарям.<br/>Эта информация предоставит доступ на чтение и запись. Смените или удалите ключ для прекращения доступа.';
$labels['sharehint_readonly'] = 'Приведете информацию, описанную выше (Логин, пароль (ключ) и URL) для других для соединения к вашим разделенным календарям.<br/>Эта информация предоставит доступ на чтение. Смените или удалите ключ для прекращения доступа.';
$labels['copytoclipboard'] = 'Скопировать в буфер';
$labels['copiedtoclipboard'] = 'Скопировано в буфер';
$labels['checkresources'] = 'Выбрать ресурсы';
$labels['checkatleastoneresource'] = 'Пожалуйста, выберите хотя бы один ресурс';
$labels['send'] = 'Послать';
$labels['cancel'] = 'Отменить';
$labels['access'] = 'Доступ';
$labels['invitationsubject'] = '%s приглашает вас получить доступ к календарю CalDAV';
$labels['tutorials'] = 'Инструкции';
$labels['gotodate'] = 'Перейти на дату';
$labels['overview'] = 'Обзор';
$labels['close'] = 'Закрыть';
$labels['restore'] = 'Восстановить все элементы';
$labels['history'] = 'История';
$labels['forward'] = 'вперёд';
$labels['back'] = 'назад';
$labels['caldav_notify'] = 'Послать оповещение, когда посетители изменяют события';
$labels['cal_notify_to'] = 'ПОлучатель';
$labels['events'] = 'События';
$labels['export'] = 'Экспорт';
$labels['custommail'] = 'Запланировать настраиваемое письмо';
$labels['sounds'] = 'Звуки';
$labels['play'] = 'играть';
$labels['nodefaultcalendar'] = 'Выберите календарь по умолчанию в настройках календаря';
$labels['due'] = 'На дату';
$labels['defaultbackgroundcolor'] = 'Цвет фона по умолчанию для событий с правом на чтение и запись';
$labels['defaultreadonlybackgroundcolor'] = 'Цвет фона по умолчанию для событий только на чтение';
$labels['fontcolor'] = 'Цвет шрифта';
$labels['blackwhite'] = 'чёрный/белый';
$labels['black'] = 'чёрный';
$labels['white'] = 'белый';
$labels['complementary'] = 'дополнительный';

?>