<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Webmail Notificering';
$labels['plugindescription'] = 'En Browser tilføjelse for at blive notificeret ved nye meddelelser.';
$labels['webmailnotifieraddon'] = 'Få %s Webmail notificerings tilføjelse';
$labels['webmailnotifierscript'] = 'Få %s Webmail notificerings script';
$labels['webmailnotifierflag'] = 'Notificer med flag';
$labels['webmailnotifierfolders'] = 'Tjek mapper';
$labels['recent'] = 'Ny';
$labels['unseen'] = 'Ulæst';
$labels['tutorial'] = 'Vejledning';

?>