ALTER TABLE events ADD labels varchar(255) NOT NULL DEFAULT '';
ALTER TABLE events ADD created timestamp DEFAULT NULL;
ALTER TABLE events ADD modified timestamp DEFAULT NULL;
ALTER TABLE events_cache ADD labels varchar(255) NOT NULL DEFAULT '';
ALTER TABLE events_cache ADD created timestamp DEFAULT NULL;
ALTER TABLE events_cache ADD modified timestamp DEFAULT NULL;
ALTER TABLE events_caldav ADD labels varchar(255) NOT NULL DEFAULT '';
ALTER TABLE events_caldav ADD created timestamp DEFAULT NULL;
ALTER TABLE events_caldav ADD modified timestamp DEFAULT NULL;
UPDATE system SET value='initial|20130512|20130804|20140409' WHERE name='myrc_calendar';