<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/myrc_sprites/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 01/15/2015 09:31:58
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'MyRoundcube sprites';
$labels['plugindescription'] = 'Helper lisosa joka sisältää spritet ja jaetut kuvat muille lisäosille.';

?>