<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Previene i Keylogger';
$labels['plugindescription'] = 'Aggiungi una tastiera virtuale per inserire le password. Soluzione ideale per prevenire software malevoli (keylogger) dal carpire la password mentre viene digitata sulla tastiera tradizionale.';
$labels['vk00'] = 'Tastiera Virtuale';
$labels['vk01'] = 'Mostra la tastiera virtuale';
$labels['vk02'] = 'Seleziona ';
$labels['vk03'] = 'Tasti non assegnati';
$labels['vk04'] = 'Accesa';
$labels['vk05'] = 'Spenta';
$labels['vk06'] = 'Chiudi la tastiera';
$labels['vk07'] = 'Cancella';
$labels['vk08'] = 'Cancella questa immissione';
$labels['vk09'] = 'Versione';
$labels['vk10'] = 'Regola la dimensione della tastiera';

/* Do not translate the following labels */
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '  ↵  ';
$labels['bksp'] = '  ←  ';

?>