<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Klawiatura ekranowa';
$labels['plugindescription'] = 'Klawiatura ekranowa pozwala na zapobiegania kradzieży hasła za pomocą keylogger\'ów.';
$labels['vk00'] = 'Interfejs klawiatury ekranowej';
$labels['vk01'] = 'Wyświetl klawiaturę ekranową';
$labels['vk02'] = 'Zmień układ klawiatury';
$labels['vk03'] = 'Puste klawisze';
$labels['vk04'] = 'Włączony';
$labels['vk05'] = 'Wyłączony';
$labels['vk06'] = 'Zamknij klawiaturę';
$labels['vk07'] = 'Wyczyść';
$labels['vk08'] = 'Wyczyść to pole';
$labels['vk09'] = 'Wersja';
$labels['vk10'] = 'Dostosuj wielkość klawiatury';
$labels['shift'] = '⇑';
$labels['tab'] = '⇔';
$labels['caps'] = '⇓';
$labels['enter'] = '↵ ';
$labels['bksp'] = '← ';

?>