<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/09/2014 10:27:23
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Oznámení nových zpráv';
$labels['plugindescription'] = 'Doplněk do prohlížeče upozorňující na nové příchozí zprávy';
$labels['webmailnotifieraddon'] = 'Získat doplněk %s Webmail Notifier';
$labels['webmailnotifierscript'] = 'Získat skript %s Webmail Notifier';
$labels['webmailnotifierflag'] = 'Upozornit na vlajku';
$labels['webmailnotifierfolders'] = 'Zkontrolovat složky';
$labels['recent'] = 'Nové';
$labels['unseen'] = 'Nepřečtené';
$labels['tutorial'] = 'Tutoriál';

?>