<?php

/*
+-----------------------------------------------------------------------+
| language/el_GR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Ειδοποιητής Webmail';
$labels['plugindescription'] = 'Πρόσθετο του περιηγητή για ειδοποίηση νέων μηνυμάτων.';
$labels['webmailnotifierfolders'] = 'Έλεγχος φακέλων';
$labels['recent'] = 'Νέο';
$labels['unseen'] = 'Αδιάβαστο';
$labels['tutorial'] = 'Οδηγός';

?>