<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 01/15/2015 09:48:48
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Webmail muistuttaja';
$labels['plugindescription'] = 'Selain lisäosa joka muistuttaa uusista viesteistä.';
$labels['webmailnotifieraddon'] = 'Nouda %s Webmail muistutus lisäosa';
$labels['webmailnotifierscript'] = 'Nouda %s Webmail muistutus skripti';
$labels['webmailnotifierflag'] = 'Muistuta kun viesti on merkitty';
$labels['webmailnotifierfolders'] = 'Tarkista kansiot';
$labels['recent'] = 'Uusi';
$labels['unseen'] = 'Lukematon';
$labels['tutorial'] = 'Ohjeistus';

?>