<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Уведомления ВебПочты';
$labels['plugindescription'] = 'Дополнение к для уведомления о новых входящих сообщениях.';
$labels['webmailnotifieraddon'] = 'Получить %s Уведомления ВебПочты дополнение';
$labels['webmailnotifierscript'] = 'Получить %s Уведомления ВебПочты скрипт';
$labels['webmailnotifierflag'] = 'Включить Уведомления';
$labels['webmailnotifierfolders'] = 'Проверять Папки';
$labels['recent'] = 'Новые';
$labels['unseen'] = 'Непрочитанные';

?>