<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Ondrej Krejcik ondra@tachec.org - 04/04/2014 13:25:23
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Trvalé přihlášení';
$labels['plugindescription'] = 'Tento doplněk poskytuje funkcionalitu trvalého přihlášení.';
$labels['ifpl_rememberme'] = 'Zůstat trvale přihlášen';
$labels['ifpl_rememberme_hint'] = 'Z bezpečnostních důvodů nepoužívejte tuto volbu na veřejných počítačích.';

?>