<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 06/01/2013 11:47:40
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Persistent Login';
$labels['plugindescription'] = 'This plugin provides a persistent login functionality, also known as “remember me” or “stay logged in” option.';
$labels['ifpl_rememberme'] = 'Keep me logged in';
$labels['ifpl_rememberme_hint'] = 'Do not use this option in public computers for security reason.';

?>