<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 12/25/2012 00:07:43
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Sesión persistente';
$labels['plugindescription'] = 'Este plugin proporciona una funcionalidad de inicio de sesión permanente, también conocida como "recordarme" ó "permanecer conectado".';
$labels['ifpl_rememberme'] = 'No cerrar la sesión';
$labels['ifpl_rememberme_hint'] = 'No utilice esta función en equipos públicos para su seguridad.';

?>