<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 10/28/2014 14:50:20
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Muista minut kirjautuminen';
$labels['plugindescription'] = 'Tämä lisäosa tuo vaihtoehdon jolla käyttäjä on sisäänkirjautuneena ensi kerralla';
$labels['ifpl_rememberme'] = 'Muista minut';
$labels['ifpl_rememberme_hint'] = 'Älä käytä tätä vaihtoehtoa julkisilla tietokoneilla tietoturvan takia.';

?>