<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/hu_HU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Mihaly Vukovics - 08/16/2013 13:46:52
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Tartós bejelentkezés';
$labels['plugindescription'] = 'A plugin lehetőséget ad a tartós bejeletkezésre, közismertebben: "emlékezz" rám, illetve "maradjak bejelentkezve".';
$labels['ifpl_rememberme'] = 'Maradjak bejelentkezve';
$labels['ifpl_rememberme_hint'] = 'Csak olyan számítógépen használja, amihez más nem fér hozzá. Ellenkező esetben mások is el tudjál olvasni a leveleit!';

?>