<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/persistent_login/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: intio.nl (info@intio.nl) - 02/19/2015 13:10:57
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Persistent Login';
$labels['plugindescription'] = 'This plugin provides a persistent login functionality, also known as “remember me” or “stay logged in” option.';
$labels['ifpl_rememberme'] = 'Mijn gegevens onthouden';
$labels['ifpl_rememberme_hint'] = 'Gebruik deze functie niet op openbare computers om veiligheidsredenen.';

?>