<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Redactar en finestra nova';
$labels['pluginname'] = 'Redactar en finestra nova';
$labels['plugindescription'] = 'Redacta els missatges nous en una finestra emergent. Pots tenir una finestra dedicada per a cada missatge que estiguis redactant.';
$labels['popupblockerwarning'] = 'Si us plau, habilita les finestres emergents!';

?>