<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 2.05 (20100218)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Ny mail i nyt vindue';
$labels['enabled'] = 'Aktiver ny mail i nyt vindue';
$labels['hidebar'] = 'Skjul værktøjslinie i ny mail vinduet';
$labels['popupblockerwarning'] = 'Tillad popups!';
?>