<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/compose_newwindow/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:02:57
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['compose_newwindow'] = 'Nachrichten in neuem Fenster erstellen';
$labels['pluginname'] = 'Nachrichten in neuem Fenster erstellen';
$labels['plugindescription'] = 'Nachrichten in einem neuen Fenster erstellen.';
$labels['enabled'] = 'Aktivieren';
$labels['hidebar'] = 'Navigationsleiste verbergen';
$labels['popupblockerwarning'] = 'Bitte erlauben Sie Popups!';

?>