<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 2.05 (20100218)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Nachrichten in neuem Fenster erstellen';
$labels['pluginname'] = 'Nachrichten in neuem Fenster erstellen';
$labels['plugindescription'] = 'Nachrichten in einem neuen Fenster erstellen.';
$labels['popupblockerwarning'] = 'Bitte erlauben Sie Popups!';
?>
