<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/compose_newwindow/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:32:22
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Compose in New Window';
$labels['pluginname'] = 'Compose in New Window';
$labels['plugindescription'] = 'Compose new message(s) in a pop-up window. Have a dedicated window for each particular message yo...';
$labels['enabled'] = 'Enable compose in new window';
$labels['hidebar'] = 'Hide main toolbar in compose windows';
$labels['popupblockerwarning'] = 'Please allow Popups!';

?>