<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 2.05 (20100218)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Compose in New Window';
$labels['pluginname'] = 'Compose in New Window';
$labels['plugindescription'] = 'Compose new message(s) in a pop-up window. Have a dedicated window for each particular message you are composing.';
$labels['popupblockerwarning'] = 'Please allow Popups!';
?>
