<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 2.05 (20100218)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010 Karl McMurdo
 *
 */
/* Author: Yoni <yoni@unlockforus.com> - Courtesy <www.unlockforus.com> */
$labels = array();

$labels['compose_newwindow'] = 'Redactar en Ventanas';
$labels['pluginname'] = 'Redactar en Ventanas';
$labels['plugindescription'] = 'Redactar nuevo mensaje(s) en ventanas por separado. Crea una ventana por separado para cada mensaje que esté componiendo.';
$labels['popupblockerwarning'] = 'Por favor permita ventanas emergentes!';
?>
