<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/compose_newwindow/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: hugues@mail4us.net - 04/07/2012 15:30:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['compose_newwindow'] = 'Composition dans une nouvelle fenêtre';
$labels['pluginname'] = 'Composition dans une nouvelle fenêtre';
$labels['plugindescription'] = 'Composition des messages dans une fenêtre popup. Chaque message possède sa propre fenêtre de composition.';
$labels['enabled'] = 'Activer la composition dans une nouvelle fenêtre';
$labels['hidebar'] = 'Masquer la barre d\'outils dans la fenêtre de composition';
$labels['popupblockerwarning'] = 'Merci d\'autoriser les popups';

?>