<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Componi in Nuova Finestra';
$labels['pluginname'] = 'Componi in una Nuova Finestra';
$labels['plugindescription'] = 'Componi i nuovi messaggi in una finestra pop-up. La creazione di ogni messaggio avverrà in una sua finestra separata.';
$labels['enabled'] = 'Abilita composizione in nuova finestra';
$labels['hidebar'] = 'Nascondi toolbar principale in componi finestre';
$labels['popupblockerwarning'] = 'Per favore permetti i Popup!';

?>