<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/compose_newwindow/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: HiJack! - 03/27/2012 17:00:18
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['compose_newwindow'] = 'Maak bericht in nieuw venster';
$labels['pluginname'] = 'Maak bericht in nieuw venster';
$labels['plugindescription'] = 'Berichten aanmaken in een nieuw venster.';
$labels['enabled'] = 'Berichten in een nieuw venster aanmaken';
$labels['hidebar'] = 'Verberg taakbalk in het nieuwe venster';
$labels['popupblockerwarning'] = 'Sta popupschermen toe voor deze website!';

?>