<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Komponuj emaile w Nowym Oknie';
$labels['pluginname'] = 'Komponuj emaile w Nowym Oknie';
$labels['plugindescription'] = 'Komponuj nowe wiadomości w oknie pop-up. Dla każdej wiadomości można otowrzyć osobne okno.';
$labels['popupblockerwarning'] = 'Proszę pozwól przeglądarce otwierać okna pop-up.';

?>