<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                              |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['compose_newwindow'] = 'Escrever em uma nova janela';
$labels['pluginname'] = 'Escrever em uma nova janela';
$labels['plugindescription'] = 'Escrever nova(s) mensagem(ns) em uma janela popup. Ter uma janela dedicada para cada mensagem individual que você escrever.';
$labels['enabled'] = 'Habilitar composição em uma nova janela';
$labels['hidebar'] = 'Ocultar a barra de ferramentas principal na janela de composição';
$labels['popupblockerwarning'] = 'Por favor, autorize Popups!';

