<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/compose_newwindow/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Ling Fude - 03/19/2012 15:08:32
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Compor numa nova janela';
$labels['pluginname'] = 'Compor numa nova janela';
$labels['plugindescription'] = 'Compor nova mensagem(ns) numa nova janela pop-up. Tenha uma janela dedicada para cada mensagem em particular...';
$labels['enabled'] = 'Ativar compor em nova janela';
$labels['hidebar'] = 'Esconder barra de ferramentas principal na composição em nova janela';
$labels['popupblockerwarning'] = 'Por favor, autorize janelas Popup!';

?>