<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Peter Zotov <whitequark@whitequark.org>                       |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Написать сообщение в новом окне';
$labels['pluginname'] = 'Написать Сообщение в Новом окне';
$labels['plugindescription'] = 'Создаёт новые сообщение(я) во всплывающем окне. Открывает новое окно для каждого сообщения которое вы создаёте.';
$labels['popupblockerwarning'] = 'Пожалуйста разрешите всплывающие окна!';

?>