<?php

$labels = array();
$labels['pluginname'] = 'Konto Information';
$labels['plugindescription'] = 'Viser grundlæggende oplysninger om kontoen såsom IMAP, POP3 og SMTP server protokollerne, dine oplysninger, evt. oplysninger om CalDAV/CardDAV URLs og andre detaljer.';
$labels['accountinformation'] = 'Konto oplysninger';
$labels['encryption'] = 'Kryptering';
$labels['port'] = 'Port';
$labels['auth'] = 'Validering';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nej';
$labels['created'] = 'Oprettet';
$labels['lastlogin'] = 'Sidste logind';
$labels['defaultidentity'] = 'Standard identitet';
$labels['back'] = 'Tilbage';
$labels['userinfo'] = 'Brugeroplysninger';
$labels['description'] = 'Hent detaljerede informationer om din konto.';
$labels['default'] = 'Standard';
$labels['clients'] = 'Anbefalet klienter som supporter %s protokol';
$labels['tutorial'] = 'Vejledning';
$labels['copiedtoclipboard'] = 'Kopieret til udklipsholder';
$labels['copytoclipboard'] = 'Kopier til udklipsholder';
$labels['calendars'] = 'Kalendere';
$labels['addressbooks'] = 'Adressebøger';
$labels['mailbox'] = 'Postkasse';

?>