<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:05:01
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['imapserver'] = 'IMAP-Server';
$labels['smtpserver'] = 'SMTP-Server';
$labels['port'] = 'Port';
$labels['created'] = 'Erstellt';
$labels['lastlogin'] = 'Letzter Login';
$labels['defaultidentity'] = 'Standard-Identität';
$labels['back'] = 'Zurück';
$labels['userinfo'] = 'Benutzer-Informationen';
$labels['description'] = 'Sehen Sie Informationen über Ihr Konto ein.';

?>