<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['imapserver'] = 'Server IMAP';
$labels['smtpserver'] = 'Server SMTP';
$labels['port'] = 'Porta';
$labels['created'] = 'Creato';
$labels['lastlogin'] = 'Ultimo Login';
$labels['defaultidentity'] = 'Identità di default';
$labels['back'] = 'Indietro';
$labels['userinfo'] = 'Informazioni Utente';
$labels['description'] = 'Fornisce informazioni dettagliate sul tuo Account.';

?>