<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Emiel Wieldraaijer - 12/15/2012 17:12:04
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Gebruiker informatie';
$labels['plugindescription'] = 'Laat standaard informatie zien van IMAP, POP en SMTP server protocollen, standaard identiteit, gebruikers CalDAV en CardDAV koppelingen en andere informatie.';
$labels['accountinformation'] = 'Gebuiker details';
$labels['encryption'] = 'Encryptie';
$labels['port'] = 'Poort';
$labels['auth'] = 'Authenticatie';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nee';
$labels['created'] = 'Aangemaakt';
$labels['lastlogin'] = 'Laatste keer aangemeld';
$labels['defaultidentity'] = 'Standraard indentiteit';
$labels['back'] = 'Terug';
$labels['userinfo'] = 'Gebruikers informatie';
$labels['description'] = 'Verkrijg detaileerde informatie over jezelf';
$labels['default'] = 'Standaard';
$labels['clients'] = 'Aanbevolen programma\'s welke het %s protocol ondersteunen';
$labels['tutorial'] = 'Handleiding';

?>