<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/ru_RU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Pavel - 01/14/2013 15:10:17
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Информация по профилю';
$labels['plugindescription'] = 'Показывает основную информацию профиля - выбор протоклов IMAP/POP/SMTP, идентификация, параметры CalDAV и CardDAV, и многое другое';
$labels['accountinformation'] = 'Подробности профиля';
$labels['encryption'] = 'Шифрование';
$labels['port'] = 'Порт';
$labels['auth'] = 'Авторизация';
$labels['yes'] = 'Да';
$labels['no'] = 'Нет';
$labels['created'] = 'Создан';
$labels['lastlogin'] = 'Последний вход';
$labels['defaultidentity'] = 'Профиль по умолчанию';
$labels['back'] = 'Назад';
$labels['userinfo'] = 'Информация о пользователе';
$labels['description'] = 'Получить детальную информацию о Вашем аккаунте.';
$labels['default'] = 'Основной';
$labels['clients'] = 'Рекомендованные клиенты, поддерживающие %s протокло';
$labels['tutorial'] = 'Уроки';
$labels['copytoclipboard'] = 'Копировать в буфер обмена: Ctrl+C, Enter';
$labels['copytoclipboardtitle'] = 'Копировать в буфер обмена';

?>