<?php

/*
+-----------------------------------------------------------------------+
| language/tr_TR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['userinfo'] = 'Kullanıcı Bilgisi';
$labels['imapserver'] = 'IMAP Sunucusu';
$labels['smtpserver'] = 'SMTP Sunucusu';
$labels['port'] = 'Port';
$labels['created'] = 'Oluşturuldu';
$labels['lastlogin'] = 'Son Giriş';
$labels['defaultidentity'] = 'Varsayılan Kimlik';
$labels['dateformat'] = 'Tarih biçimi';
$labels['back'] = 'Geri';

?>