<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/imap_hooks/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 07/18/2014 09:57:50
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Pomocný doplněk umožňující další nastavení';
$labels['plugindescription'] = 'Pomocný doplněk umožňující další nastavení.';

?>