<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Carpeta arxiu';
$labels['plugindescription'] = 'Mou missatges cap a una carpeta arxiu predeterminada';
$labels['buttontitle'] = 'Arxivar el missatge';
$labels['archived'] = 'Arxivat correctament';
$labels['archivefolder'] = 'Arxiu';
$labels['folders'] = 'Totes les carpetes';

?>