<?php
/* Author: Yoni <yoni@unlockforus.com> - Courtesy <www.unlockforus.com> */
$labels = array();
$labels['pluginname'] = 'Carpeta de Archivado';
$labels['plugindescription'] = 'Mover mensajes a una carpeta de archivado predefinida.';
$labels['buttontitle'] = 'Archivar este mensaje';
$labels['archived'] = 'Archivado éxitosamente';
$labels['archivefolder'] = 'Archivo';
$labels['folders'] = 'Todas las carpetas';

?>