<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/archivefolder/localization/sv_SE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Stefan Manninen - 10/28/2014 12:54:16
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Arkiv mapp';
$labels['plugindescription'] = 'Flytta meddelanden till förinställd arkiv mapp.';
$labels['buttontitle'] = 'Arkivera';
$labels['archived'] = 'Arkivering lyckades';
$labels['archivefolder'] = 'Arkiv';
$labels['folders'] = 'Alla kataloger';

?>