(function(a){a.fn.fixPNG=function(){return this.each(function(){var b=a(this).css("backgroundImage");b.match(/^url\(["']?(.*\.png)["']?\)$/i)&&(b=RegExp.$1,a(this).css({backgroundImage:"none",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod="+("no-repeat"==a(this).css("backgroundRepeat")?"crop":"scale")+", src='"+b+"')"}).each(function(){var b=a(this).css("position");"absolute"!=b&&"relative"!=b&&a(this).css("position","relative")}))})};var f,b,l=!1,e=new Image,
m,j=1,p=/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i,q=null,k=a.browser.msie&&6==a.browser.version.substr(0,1)&&!window.XMLHttpRequest,r=k||a.browser.msie&&7==a.browser.version.substr(0,1);a.fn.fancybox=function(c){function d(){a("#fancy_right, #fancy_left, #fancy_close, #fancy_title").hide();var i=b.itemArray[b.itemCurrent].href;if(i.match("iframe")||0<=f.className.indexOf("iframe"))a.fn.fancybox.showLoading(),n('<iframe id="fancy_frame" onload="jQuery.fn.fancybox.showIframe()" name="fancy_iframe'+Math.round(1E3*
Math.random())+'" frameborder="0" hspace="0" src="'+i+'"></iframe>',b.frameWidth,b.frameHeight);else if(i.match(/#/)){var c=window.location.href.split("#")[0],c=i.replace(c,""),c=c.substr(c.indexOf("#"));n('<div id="fancy_div">'+a(c).html()+"</div>",b.frameWidth,b.frameHeight)}else i.match(p)?(e=new Image,e.src=i,e.complete?s():(a.fn.fancybox.showLoading(),a(e).unbind().bind("load",function(){a("#fancy_loading").hide();s()}))):(a.fn.fancybox.showLoading(),a.get(i,function(i){a("#fancy_loading").hide();
n('<div id="fancy_ajax">'+i+"</div>",b.frameWidth,b.frameHeight)}))}function s(){var i=e.width,c=e.height,d=2*b.padding+40,g=2*b.padding+60,f=a.fn.fancybox.getViewport();if(b.imageScale&&(i>f[0]-d||c>f[1]-g))d=Math.min(Math.min(f[0]-d,i)/i,Math.min(f[1]-g,c)/c),i=Math.round(d*i),c=Math.round(d*c);n('<img alt="" id="fancy_img" src="'+e.src+'" />',i,c)}function t(){if(b.itemArray.length-1>b.itemCurrent){var a=b.itemArray[b.itemCurrent+1].href||!1;a&&a.match(p)&&(objNext=new Image,objNext.src=a)}if(0<
b.itemCurrent&&(a=b.itemArray[b.itemCurrent-1].href||!1)&&a.match(p))objNext=new Image,objNext.src=a}function n(c,d,h){l=!0;var g=b.padding;if(r||q)a("#fancy_content")[0].style.removeExpression("height"),a("#fancy_content")[0].style.removeExpression("width");if(0<g){if(d+=2*g,h+=2*g,a("#fancy_content").css({top:g+"px",right:g+"px",bottom:g+"px",left:g+"px",width:"auto",height:"auto"}),r||q)a("#fancy_content")[0].style.setExpression("height","(this.parentNode.clientHeight - "+2*g+")"),a("#fancy_content")[0].style.setExpression("width",
"(this.parentNode.clientWidth - "+2*g+")")}else a("#fancy_content").css({top:0,right:0,bottom:0,left:0,width:"100%",height:"100%"});if(a("#fancy_outer").is(":visible")&&d==a("#fancy_outer").width()&&h==a("#fancy_outer").height())a("#fancy_content").fadeOut("fast",function(){a("#fancy_content").empty().append(a(c)).fadeIn("normal",function(){o()})});else{var g=a.fn.fancybox.getViewport(),f=h+60>g[1]?g[3]:g[3]+Math.round(0.5*(g[1]-h-60)),e={left:d+40>g[0]?g[2]:g[2]+Math.round(0.5*(g[0]-d-40)),top:f,
width:d+"px",height:h+"px"};a("#fancy_outer").is(":visible")?a("#fancy_content").fadeOut("normal",function(){a("#fancy_content").empty();a("#fancy_outer").animate(e,b.zoomSpeedChange,b.easingChange,function(){a("#fancy_content").append(a(c)).fadeIn("normal",function(){o()})})}):0<b.zoomSpeedIn&&void 0!==b.itemArray[b.itemCurrent].orig?(a("#fancy_content").empty().append(a(c)),d=b.itemArray[b.itemCurrent].orig,h=a.fn.fancybox.getPosition(d),a("#fancy_outer").css({left:h.left-20-b.padding+"px",top:h.top-
20-b.padding+"px",width:a(d).width()+2*b.padding,height:a(d).height()+2*b.padding}),b.zoomOpacity&&(e.opacity="show"),a("#fancy_outer").animate(e,b.zoomSpeedIn,b.easingIn,function(){o()})):(a("#fancy_content").hide().empty().append(a(c)).show(),a("#fancy_outer").css(e).fadeIn("normal",function(){o()}))}}function m(){0!==b.itemCurrent&&(a("#fancy_left, #fancy_left_ico").unbind().bind("click",function(a){a.stopPropagation();b.itemCurrent--;d();return!1}),a("#fancy_left").show());b.itemCurrent!=b.itemArray.length-
1&&(a("#fancy_right, #fancy_right_ico").unbind().bind("click",function(a){a.stopPropagation();b.itemCurrent++;d();return false}),a("#fancy_right").show())}function o(){a.browser.msie&&(a("#fancy_content")[0].style.removeAttribute("filter"),a("#fancy_outer")[0].style.removeAttribute("filter"));m();t();a(document).bind("keydown.fb",function(c){if(c.keyCode==27&&b.enableEscapeButton)a.fn.fancybox.close();else if(c.keyCode==37&&b.itemCurrent!==0){a(document).unbind("keydown.fb");b.itemCurrent--;d()}else if(c.keyCode==
39&&b.itemCurrent!=b.itemArray.length-1){a(document).unbind("keydown.fb");b.itemCurrent++;d()}});b.hideOnContentClick&&a("#fancy_content").click(a.fn.fancybox.close);b.overlayShow&&b.hideOnOverlayClick&&a("#fancy_overlay").bind("click",a.fn.fancybox.close);b.showCloseButton&&a("#fancy_close").bind("click",a.fn.fancybox.close).show();if("undefined"!==typeof b.itemArray[b.itemCurrent].title&&0<b.itemArray[b.itemCurrent].title.length){var c=a("#fancy_outer").position();a("#fancy_title div").text(b.itemArray[b.itemCurrent].title).html();
a("#fancy_title").css({top:c.top+a("#fancy_outer").outerHeight()-32,left:c.left+(0.5*a("#fancy_outer").outerWidth()-0.5*a("#fancy_title").width())}).show()}b.overlayShow&&k&&a("embed, object, select",a("#fancy_content")).css("visibility","visible");a.isFunction(b.callbackOnShow)&&b.callbackOnShow(b.itemArray[b.itemCurrent]);a.browser.msie&&(a("#fancy_outer")[0].style.removeAttribute("filter"),a("#fancy_content")[0].style.removeAttribute("filter"));l=!1}var j=a.extend({},a.fn.fancybox.defaults,c),
u=this;return this.unbind("click.fb").bind("click.fb",function(){f=this;b=a.extend({},j);if(!l){a.isFunction(b.callbackOnStart)&&b.callbackOnStart();b.itemArray=[];b.itemCurrent=0;if(0<j.itemArray.length)b.itemArray=j.itemArray;else{var c={};if(!f.rel||""==f.rel){c={href:f.href,title:f.title};c.orig=a(f).children("img:first").length?a(f).children("img:first"):a(f);if(""==c.title||"undefined"==typeof c.title)c.title=c.orig.attr("alt");b.itemArray.push(c)}else for(var e=a(u).filter("a[rel="+f.rel+"]"),
h=0;h<e.length;h++){c={href:e[h].href,title:e[h].title};c.orig=a(e[h]).children("img:first").length?a(e[h]).children("img:first"):a(e[h]);if(""==c.title||"undefined"==typeof c.title)c.title=c.orig.attr("alt");b.itemArray.push(c)}}for(;b.itemArray[b.itemCurrent].href!=f.href;)b.itemCurrent++;b.overlayShow&&(k&&(a("embed, object, select").css("visibility","hidden"),a("#fancy_overlay").css("height",a(document).height())),a("#fancy_overlay").css({"background-color":b.overlayColor,opacity:b.overlayOpacity}).show());
a(window).bind("resize.fb scroll.fb",a.fn.fancybox.scrollBox);d()}return!1})};a.fn.fancybox.scrollBox=function(){var c=a.fn.fancybox.getViewport();if(b.centerOnScroll&&a("#fancy_outer").is(":visible")){var d=a("#fancy_outer").outerWidth(),e=a("#fancy_outer").outerHeight(),f={top:e>c[1]?c[3]:c[3]+Math.round(0.5*(c[1]-e)),left:d>c[0]?c[2]:c[2]+Math.round(0.5*(c[0]-d))};a("#fancy_outer").css(f);a("#fancy_title").css({top:f.top+e-32,left:f.left+(0.5*d-0.5*a("#fancy_title").width())})}k&&a("#fancy_overlay").is(":visible")&&
a("#fancy_overlay").css({height:a(document).height()});a("#fancy_loading").is(":visible")&&a("#fancy_loading").css({left:0.5*(c[0]-40)+c[2],top:0.5*(c[1]-40)+c[3]})};a.fn.fancybox.getNumeric=function(b,d){return parseInt(a.curCSS(b.jquery?b[0]:b,d,!0))||0};a.fn.fancybox.getPosition=function(b){var d=b.offset();d.top+=a.fn.fancybox.getNumeric(b,"paddingTop");d.top+=a.fn.fancybox.getNumeric(b,"borderTopWidth");d.left+=a.fn.fancybox.getNumeric(b,"paddingLeft");d.left+=a.fn.fancybox.getNumeric(b,"borderLeftWidth");
return d};a.fn.fancybox.showIframe=function(){a("#fancy_loading").hide();a("#fancy_frame").show()};a.fn.fancybox.getViewport=function(){return[a(window).width(),a(window).height(),a(document).scrollLeft(),a(document).scrollTop()]};a.fn.fancybox.animateLoading=function(){a("#fancy_loading").is(":visible")?(a("#fancy_loading > div").css("top",-40*j+"px"),j=(j+1)%12):clearInterval(m)};a.fn.fancybox.showLoading=function(){clearInterval(m);var b=a.fn.fancybox.getViewport();a("#fancy_loading").css({left:0.5*
(b[0]-40)+b[2],top:0.5*(b[1]-40)+b[3]}).show();a("#fancy_loading").bind("click",a.fn.fancybox.close);m=setInterval(a.fn.fancybox.animateLoading,66)};a.fn.fancybox.close=function(){l=!0;a(e).unbind();a(document).unbind("keydown.fb");a(window).unbind("resize.fb scroll.fb");a("#fancy_overlay, #fancy_content, #fancy_close").unbind();a("#fancy_close, #fancy_loading, #fancy_left, #fancy_right, #fancy_title").hide();__cleanup=function(){a("#fancy_overlay").is(":visible")&&a("#fancy_overlay").fadeOut("fast");
a("#fancy_content").empty();b.centerOnScroll&&a(window).unbind("resize.fb scroll.fb");k&&a("embed, object, select").css("visibility","visible");a.isFunction(b.callbackOnClose)&&b.callbackOnClose();l=!1};if(!1!==a("#fancy_outer").is(":visible"))if(0<b.zoomSpeedOut&&void 0!==b.itemArray[b.itemCurrent].orig){var c=b.itemArray[b.itemCurrent].orig,d=a.fn.fancybox.getPosition(c),c={left:d.left-20-b.padding+"px",top:d.top-20-b.padding+"px",width:a(c).width()+2*b.padding,height:a(c).height()+2*b.padding};
b.zoomOpacity&&(c.opacity="hide");a("#fancy_outer").stop(!1,!0).animate(c,b.zoomSpeedOut,b.easingOut,__cleanup)}else a("#fancy_outer").stop(!1,!0).fadeOut("fast",__cleanup);else __cleanup();return!1};a.fn.fancybox.build=function(){a('<div id="fancy_overlay"></div><div id="fancy_loading"><div></div></div><div id="fancy_outer"><div id="fancy_inner"><div id="fancy_close"></div><div id="fancy_bg"><div class="fancy_bg" id="fancy_bg_n"></div><div class="fancy_bg" id="fancy_bg_ne"></div><div class="fancy_bg" id="fancy_bg_e"></div><div class="fancy_bg" id="fancy_bg_se"></div><div class="fancy_bg" id="fancy_bg_s"></div><div class="fancy_bg" id="fancy_bg_sw"></div><div class="fancy_bg" id="fancy_bg_w"></div><div class="fancy_bg" id="fancy_bg_nw"></div></div><a href="javascript:;" id="fancy_left"><span class="fancy_ico" id="fancy_left_ico"></span></a><a href="javascript:;" id="fancy_right"><span class="fancy_ico" id="fancy_right_ico"></span></a><div id="fancy_content"></div></div></div><div id="fancy_title"></div>').appendTo("body");
a('<table cellspacing="0" cellpadding="0" border="0"><tr><td class="fancy_title" id="fancy_title_left"></td><td class="fancy_title" id="fancy_title_main"><div></div></td><td class="fancy_title" id="fancy_title_right"></td></tr></table>').appendTo("#fancy_title");a.browser.msie&&a(".fancy_bg").fixPNG();if(k){a("div#fancy_overlay").css("position","absolute");a("#fancy_loading div, #fancy_close, .fancy_title, .fancy_ico").fixPNG();a("#fancy_inner").prepend('<iframe id="fancy_bigIframe" src="javascript:false;" scrolling="no" frameborder="0"></iframe>');
var b=a("#fancy_bigIframe")[0].contentWindow.document;b.open();b.close()}};a.fn.fancybox.defaults={padding:10,imageScale:!0,zoomOpacity:!0,zoomSpeedIn:0,zoomSpeedOut:0,zoomSpeedChange:300,easingIn:"swing",easingOut:"swing",easingChange:"swing",frameWidth:560,frameHeight:340,overlayShow:!0,overlayOpacity:0.3,overlayColor:"#666",enableEscapeButton:!0,showCloseButton:!0,hideOnOverlayClick:!0,hideOnContentClick:!0,centerOnScroll:!0,itemArray:[],callbackOnStart:null,callbackOnShow:null,callbackOnClose:null};
a(document).ready(function(){q=a.browser.msie&&!a.boxModel;1>a("#fancy_outer").length&&a.fn.fancybox.build()})})(jQuery);
