<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/libgpl/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/10/2015 10:46:25
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['calendar_caldav'] = 'Calendario CalDAV';
$labels['calendar_kolab'] = 'Calendario Kolab';
$labels['calendar_database'] = 'Calendario Local';
$labels['calendar_ical'] = 'Calendario iCAL';
$labels['calendar_google_xml'] = 'Calendario Google XML';
$labels['sync_interval'] = 'Sincronización cada';
$labels['minute_s'] = 'minuto(s)';
$labels['tasks'] = 'Tareas';
$labels['errorimportingtask'] = 'No se pudo importar la tarea';
$labels['treat_as_allday'] = 'Mostrar evento como \'todo el día\' si toma más de';
$labels['hours'] = 'Horas';
$labels['movetotasks'] = 'Mover a tareas';
$labels['movetocalendar'] = 'Mover al calendario';
$labels['emailevent'] = 'Enviar evento por correo';
$labels['emailnote'] = 'Enviar nota por correo';
$labels['emailtask'] = 'Enviar tarea por correo';
$labels['movetonotes'] = 'Mover a notas';
$labels['quit'] = 'Salir';
$labels['eventaction'] = 'Acción de evento...';
$labels['googledisabled'] = 'Please authorize access to your Google account (browse to "Settings" -> "Account Administration" -> "Other account\'s settings" and proceed).  Por favor, autorizar el acceso a su cuenta de Google (vaya a "Configuración" -> "Administración de Cuenta" -> "Otros ajustes de cuentas" y proceda).';
$labels['googledisabled_redirect'] = 'Por favor, autorizar el acceso a su cuenta de Google.';
$labels['allowfreebusy'] = 'Permitir solicitudes Libre/Ocupado';
$labels['freebusy'] = 'Libre/Ocupado';
$labels['unabletoadddefaultcalendars'] = 'No se pudo agregar calendarios predeterminados';
$labels['taskaction'] = 'Acción de tarea...';
$labels['due'] = 'debido el';
$labels['is_subtask'] = 'Subtarea';
$labels['subscribe'] = 'Por favor, suscribirse a un calendario para poder crear tarea.';
$labels['subscribed'] = 'Suscrito';
$labels['tags'] = 'Categorías';
$labels['list'] = 'Calendario';
$labels['editlist'] = 'Editar calendario';
$labels['synchronize'] = 'Sincronizar';
$labels['submenuprefix'] = '» ';
$labels['birthdays'] = 'Cumpleaños';
$labels['birthdayof'] = 'cumpleaños de';
$labels['showbirthdays'] = 'Mostrar cumpleaños';
$labels['sameday'] = 'En el cumpleaños';
$labels['onedaybefore'] = 'Un día antes del cumpleaños';
$labels['twodaysbefore'] = 'Dos días antes del cumpleaños';
$labels['threedaysbefore'] = 'Tres días antes del cumpleaños';
$labels['happybirthday'] = 'Feliz Cumpleaños';
$labels['birthdaygreetings'] = 'Componer Saludos de Cumpleaños';
$labels['sql'] = 'Personal';
$labels['url'] = 'URL';
$labels['no_google_xml'] = 'Esto no es un  URL de Google XML Feed';
$labels['click_here'] = 'Haga clic aquí';
$labels['reminder'] = 'Aviso';
$labels['reminderfooter_event'] = 'Usted está recibiendo este correo electrónico porque ha solicitado que se le recuerde acerca de este próximo evento en el calendario.';
$labels['reminderfooter_task'] = 'Usted está recibiendo este correo electrónico porque ha solicitado que se le recuerde acerca de esta próxima tarea en su lista de tareas.';
$labels['participiants'] = 'Participantes';
$labels['ACCEPTED'] = 'aceptado';
$labels['NEEDS-ACTION'] = 'pendiente';
$labels['CONFIRMED'] = 'confirmdo';
$labels['TENTATIVE'] = 'quizás';
$labels['DECLINED'] = 'rechazado';
$labels['attachments'] = 'Adjuntos';
$labels['highest'] = 'la más alta';
$labels['high'] = 'alta';
$labels['normal'] = 'normal';
$labels['low'] = 'baja';
$labels['lowest'] = 'la más baja';
$labels['minical'] = 'Mostrar Mini-Calendario';
$labels['playsound'] = 'Reproducir sonido como aviso de próximos eventos';
$labels['confidentialcaldavaccess'] = 'Acceso CalDAV Confidencial [%s]';
$labels['readwrite'] = 'lectura/escritura';
$labels['readonly'] = 'solo lectura';
$labels['isenabled'] = 'habilitado';
$labels['isdisabled'] = 'deshabilitado';
$labels['caltoken'] = 'Token';
$labels['share'] = 'Compartir';
$labels['sharing'] = 'Compartir';
$labels['resource'] = 'Recurso';
$labels['shareinvitation'] = 'Enviar invitación';
$labels['sharehint'] = 'Proporcione la información de arriba (nombre de usuario, contraseña (Token) y URLs) para que otros puedan conectarse a sus calendarios compartidos. Esta información provee acceso de lectura y escritura. Modifique o elimine el token para cerrar el acceso.<br />';
$labels['sharehint_readonly'] = 'Proporcione la información de arriba (nombre de usuario, contraseña (Token) y URLs) para que otros puedan conectarse a sus calendarios compartidos.<br /> Esta información provee acceso de sólo lectura. Modifique o elimine el token para cerrar el acceso.';
$labels['copytoclipboard'] = 'Copiar al portapapeles';
$labels['copiedtoclipboard'] = 'Copiado al portapapeles';
$labels['checkresources'] = 'Seleccione los recursos';
$labels['checkatleastoneresource'] = 'Por favor, seleccione al menos un recurso';
$labels['send'] = 'Enviar';
$labels['cancel'] = 'Cancelar';
$labels['access'] = 'Acceso';
$labels['invitationsubject'] = '%s le invita a acceder calendarios CalDAV';
$labels['tutorials'] = 'Tutoriales';
$labels['gotodate'] = 'Pasar a fecha';
$labels['overview'] = 'Información General';
$labels['close'] = 'Cerrar';
$labels['restore'] = 'Restaurar todos los elementos';
$labels['history'] = 'Historia';
$labels['forward'] = 'adelante';
$labels['back'] = 'atrás';
$labels['caldav_notify'] = 'Enviar notificación cuando asistentes modifican eventos';
$labels['cal_notify_to'] = 'Destinatario';
$labels['events'] = 'Eventos';
$labels['export'] = 'Exportar';
$labels['custommail'] = 'Programar correo electrónico personalizado';
$labels['sounds'] = 'Sonidos';
$labels['play'] = 'reproducir';
$labels['nodefaultcalendar'] = 'Por favor, elija un calendario predeterminado en la configuración del calendario.';
?>