<?php
/*
+-----------------------------------------------------------------------+
| ./plugins/libgpl/localization/fr_FR.inc
|
| Language file of MyRoundcube Plugins Bundle
| Copyright (C) 2010-2012, Roland 'rosali' Liebl
|
+-----------------------------------------------------------------------+
| Author: Thomas Parvais - 12/11/2012 11:38:10
|         Olivier Zolli - 01/11/2015
+-----------------------------------------------------------------------+
*/

$labels = array();
$labels['calendar_caldav'] = 'Agenda CalDAV';
$labels['calendar_kolab'] = 'Agenda Kolab';
$labels['calendar_database'] = 'Agenda local';
$labels['calendar_ical'] = 'Agenda iCAL';
$labels['calendar_google_xml'] = 'Agenda Google XML';
$labels['sync_interval'] = 'Synchronisation chaque';
$labels['minute_s'] = 'minute(s)';
$labels['tasks'] = 'Tâches';
$labels['errorimportingtask'] = 'Echec d\'importation de la tâche';
$labels['treat_as_allday'] = 'Montrer l\'évènement comme "Toute la journée" s\'il dure plus de';
$labels['hours'] = 'Heures';
$labels['movetotasks'] = 'Déplacer vers les tâches';
$labels['movetocalendar'] = 'Déplacer vers l\'agenda';
$labels['emailevent'] = 'Evènement courriel';
$labels['emailnote'] = 'Evènement note';
$labels['emailtask'] = 'Evènement tâche';
$labels['movetonotes'] = 'Déplacer vers les notes';
$labels['quit'] = 'Quitter';
$labels['eventaction'] = 'Action d\'évènement';
$labels['googledisabled'] = 'Veuillez autoriser l\'accès à votre compte Google (<i>"Paramètres"</i> -> <i>"Administration du compte"</i> -> <i>"Autres paramètres du compte"</i>';
$labels['googledisabled_redirect'] = 'Veuillez autoriser l\'accès à votre compte Google';
$labels['allowfreebusy'] = 'Autoriser les requêtes Libre/Occupé';
$labels['freebusy'] = 'Libre/Occupé';
$labels['unabletoadddefaultcalendars'] = 'Impossible d\'ajouter les agendas par défaut';
$labels['taskaction'] = 'Action de tâche';
$labels['due'] = 'requis';
$labels['is_subtask'] = 'Sous-tâche';
$labels['subscribe'] = 'Veuillez vous inscrire à un agenda pour créer une tâche';
$labels['subscribed'] = 'Inscrit';
$labels['tags'] = 'Catégories';
$labels['list'] = 'Agenda';
$labels['editlist'] = 'Editer l\'agenda';
$labels['synchronize'] = 'Synchroniser';
$labels['submenuprefix'] = '» ';
$labels['birthdays'] = 'Anniversaires';
$labels['birthdayof'] = 'anniversaire de';
$labels['showbirthdays'] = 'Afficher les anniversaires';
$labels['sameday'] = 'Le jour même';
$labels['onedaybefore'] = 'La veille';
$labels['twodaysbefore'] = 'Deux jours avant';
$labels['threedaysbefore'] = 'Trois jours avant';
$labels['happybirthday'] = 'Bon anniversaire';
$labels['birthdaygreetings'] = 'Composer les voeux';
$labels['sql'] = 'Personnel';
$labels['url'] = 'URL';
$labels['no_google_xml'] = 'Ce n\'est pas une URL Google XML Feed';
$labels['click_here'] = 'Cliquer ici';
$labels['reminder'] = 'Rappel';
$labels['reminderfooter_event'] = 'Vous recevez ce message car vous avez demandé à ce qu\'on vous rappelle cet évènement futur dans votre agenda.';
$labels['reminderfooter_task'] = 'Vous recevez ce message car vous avez demandé à ce qu\'on vous rappelle cet évènement futur dans votre liste de tâches.';
$labels['participiants'] = 'Participants';
$labels['ACCEPTED'] = 'Accepter';
$labels['NEEDS-ACTION'] = 'En attente';
$labels['CONFIRMED'] = 'Confirmé';
$labels['TENTATIVE'] = 'Peut-être';
$labels['DECLINED'] = 'Refuser';
$labels['attachments'] = 'Pièces jointes';
$labels['highest'] = 'La plus élevée';
$labels['high'] = 'Elevée';
$labels['normal'] = 'Normale';
$labels['low'] = 'Basse';
$labels['lowest'] = 'La plus basse';
$labels['minical'] = 'Afficher Mini-Calendrier';
$labels['playsound'] = 'Jouer un son pour les rappels d\'évènements futurs';
$labels['confidentialcaldavaccess'] = 'Accès CalDAV confidentiel';
$labels['readwrite'] = 'lecture/écriture';
$labels['readonly'] = 'lecture seule';
$labels['isenabled'] = 'activée';
$labels['isdisabled'] = 'désactivée';
$labels['caltoken'] = 'Jeton';
$labels['share'] = 'Partage';
$labels['sharing'] = 'Partage';
$labels['resource'] = 'Ressource';
$labels['shareinvitation'] = 'Envoi invitation';
$labels['sharehint'] = 'Veuillez fournir les informations demandées ci-dessus (nom d\'utilisateur, mot de passe (jeton) et ressources) pour que les autres utilisateurs puissent accéder à vos agendas partagés. Accès en lecture/écriture. Changez ou supprimez le jeton pour fermer l\'accès.';
$labels['sharehint_readonly'] = 'Veuillez fournir les informations demandées ci-dessus (nom d\'utilisateur, mot de passe (jeton) et ressources) pour que les autres utilisateurs puissent accéder à vos agendas partagés. Accès en lecture seule. Changez ou supprimez le jeton pour fermer l\'accès.';
$labels['copytoclipboard'] = 'Copier dans le presse-papier';
$labels['copiedtoclipboard'] = 'Copié dans le presse-papier';
$labels['checkresources'] = 'Sélectionner les ressources';
$labels['checkatleastoneresource'] = 'Merci de sélectionner au moins une ressource';
$labels['send'] = 'Envoyer';
$labels['cancel'] = 'Annuler';
$labels['access'] = 'Accès';
$labels['invitationsubject'] = '%s vous invite à accéder à ses agendas CalDAV';
$labels['tutorials'] = 'Tutoriels';
$labels['gotodate'] = 'Vers date';
$labels['overview'] = 'Aperçu';
$labels['close'] = 'Fermer';
$labels['restore'] = 'Restaurer tous les objets';
$labels['history'] = 'Historique';
$labels['forward'] = 'en avant';
$labels['back'] = 'en arrière';
$labels['caldav_notify'] = 'Envoyer une notification quand les participants modifient l\'évènement';
$labels['cal_notify_to'] = 'Destinataire';
$labels['events'] = 'Evènements';
$labels['export'] = 'Export';
$labels['custommail'] = 'Planifier un message personnalisé';
$labels['sounds'] = 'Sons';
$labels['play'] = 'Lire';
$labels['nodefaultcalendar'] = 'Veuillez choisir un agenda par défaut dans les réglages d\'agenda.';

?>