<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/libgpl/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: intio.nl (info@intio.nl) - 03/02/2015 10:11:39
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Kalender +';
$labels['plugindescription'] = 'Extra geavanceerde functies voor plugin kalender.';
$labels['synchronize'] = 'Synchroniseren';
$labels['submenuprefix'] = '» ';
$labels['birthdays'] = 'Verjaardagen';
$labels['birthdayof'] = 'Verjaardag van';
$labels['showbirthdays'] = 'Verjaardagen weergeven';
$labels['sameday'] = 'Op de verjaardag';
$labels['onedaybefore'] = 'Eén dag voor verjaardag';
$labels['twodaysbefore'] = 'Twee dagen voor de verjaardag';
$labels['threedaysbefore'] = 'Drie dagen voor de verjaardag';
$labels['happybirthday'] = 'Hartelijk gefeliciteerd';
$labels['birthdaygreetings'] = 'Verjaardag groet opstellen';
$labels['sql'] = 'Persoonlijk';
$labels['url'] = 'URL';
$labels['minical'] = 'Weergeef mini-kalender';
$labels['caldavaccess'] = 'Vertrouwelijke toegang CalDAV';
$labels['readwrite'] = 'Lees / schrijf toegang';
$labels['readonly'] = 'Lees toegang';
$labels['isenabled'] = 'ingeschakeld';
$labels['isdisabled'] = 'uitgeschakeld';
$labels['caltoken'] = 'Token';
$labels['share'] = 'Deel';
$labels['sharing'] = 'Delen';
$labels['resource'] = 'Bron';
$labels['shareinvitation'] = 'Verstuur uitnodiging';
$labels['sharehint'] = 'Zorg voor de bovenstaande informatie (gebruikersnaam, wachtwoord (Token) en URL\'s) voor anderen om verbinding te maken met uw gedeelde agenda. Deze informatie verleent lees en schrijftoegang. Wijzig of verwijder token om toegang te sluiten.';
$labels['sharehint_readonly'] = 'Zorg voor de bovenstaande informatie (gebruikersnaam, wachtwoord (Token) en URL\'s) voor anderen om verbinding te maken met uw gedeelde agenda. Deze informatie verleent lees toegang. Wijzig of verwijder token om toegang te sluiten.';
$labels['copytoclipboard'] = 'Kopiëren naar het klembord';
$labels['copiedtoclipboard'] = 'Gekopieerd naar het klembord';
$labels['checkresources'] = 'Controleer bronnen';
$labels['checkatleastoneresource'] = 'Selecteer minstens één bron';
$labels['send'] = 'Verstuur';
$labels['cancel'] = 'Anulleer';
$labels['access'] = 'Toegang';
$labels['fontcolor'] = 'Tekstkleur';
$labels['blackwhite'] = 'zwart/wit';
$labels['black'] = 'zwart';
$labels['white'] = 'wit';

?>