<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/libcalendaring/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/10/2015 11:44:04
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['until'] = 'hasta';
$labels['at'] = 'a';
$labels['alarmemail'] = 'Enviar correo';
$labels['alarmdisplay'] = 'Mostrar mensaje';
$labels['alarmaudio'] = 'Reproducir sonido';
$labels['alarmdisplayoption'] = 'Mensaje';
$labels['alarmemailoption'] = 'Correo';
$labels['alarmaudiooption'] = 'Sonido';
$labels['alarmat'] = 'a $datetime';
$labels['trigger@'] = 'en fecha';
$labels['trigger-M'] = 'minutos antes';
$labels['trigger-H'] = 'horas antes';
$labels['trigger-D'] = 'días antes';
$labels['trigger+M'] = 'minutos después';
$labels['trigger+H'] = 'horas después';
$labels['trigger+D'] = 'días después';
$labels['triggerattime'] = 'en el momento';
$labels['addalarm'] = 'Añadir alarma';
$labels['removealarm'] = 'Eliminar alarma';
$labels['alarmtitle'] = 'Próximos eventos';
$labels['dismissall'] = 'Descartar todos';
$labels['dismiss'] = 'Descartar';
$labels['snooze'] = 'Posponer';
$labels['repeatinmin'] = 'Repetir en $min minutos';
$labels['repeatinhr'] = 'Repetir en 1 hora';
$labels['repeatinhrs'] = 'Repetir en $hrs horas';
$labels['repeattomorrow'] = 'Repetir mañana';
$labels['repeatinweek'] = 'Repetir en una semana';
$labels['showmore'] = 'Ver mas...';
$labels['frequency'] = 'Repetir';
$labels['never'] = 'nunca';
$labels['daily'] = 'diariamente';
$labels['weekly'] = 'semanalmente';
$labels['monthly'] = 'mensualmente';
$labels['yearly'] = 'anualmente';
$labels['rdate'] = 'en fechas';
$labels['every'] = 'Cada';
$labels['days'] = 'día(s)';
$labels['weeks'] = 'semana(s)';
$labels['months'] = 'mes(es)';
$labels['years'] = 'año(s)';
$labels['bydays'] = 'En';
$labels['untildate'] = 'el';
$labels['each'] = 'Cada';
$labels['onevery'] = 'De cada';
$labels['onsamedate'] = 'En la misma fecha';
$labels['forever'] = 'eternamente';
$labels['recurrencend'] = 'hasta';
$labels['untilenddate'] = 'hasta la fecha';
$labels['forntimes'] = 'por $nr ves(veces)';
$labels['first'] = 'primero';
$labels['second'] = 'segundo';
$labels['third'] = 'tercero';
$labels['fourth'] = 'cusrto';
$labels['last'] = 'último';
$labels['dayofmonth'] = 'Día del mes';
$labels['addrdate'] = 'Añadir fecha de repetición';
$labels['itipinvitation'] = 'Invitación a';
$labels['itipupdate'] = 'Actualización de';
$labels['itipcancellation'] = 'Cancelado:';
$labels['itipreply'] = 'Responder a';
$labels['itipaccepted'] = 'Aceptar';
$labels['itiptentative'] = 'Quizás';
$labels['itipdeclined'] = 'Rechazar';
$labels['itipdelegated'] = 'Delegar';
$labels['itipneeds-action'] = 'Posponer';
$labels['itipcomment'] = 'Su respuesta';
$labels['itipeditresponse'] = 'Introduzca texto de respuesta';
$labels['itipsendercomment'] = 'Comentario del remitente:';
$labels['itipsuppressreply'] = 'No enviar respuesta';
$labels['itipobjectnotfound'] = 'El objeto referido por este mensaje no se ha encontrado en su cuenta.';
$labels['itipsubjectaccepted'] = '"$title" ha sido aceptado por $name';
$labels['itipsubjecttentative'] = '"$title" ha sido tentativamente aceptado por $name';
$labels['itipsubjectdeclined'] = '"$title" ha sido rechazado por $name';
$labels['itipsubjectcancel'] = 'Su participación en "$title" ha sido cancelada';
$labels['itipnewattendee'] = 'Esta es una respuesta de un nuevo participante';
$labels['updateattendeestatus'] = 'Actualizar el estado del participante';
$labels['acceptinvitation'] = '¿Acepta esta invitación?';
$labels['acceptattendee'] = 'Aceptar participante';
$labels['declineattendee'] = 'Rechazar participante';
$labels['declineattendeeconfirm'] = 'Escriba un mensaje al participante rechazado (opcional):';
$labels['youhaveaccepted'] = 'Ha aceptado esta invitación';
$labels['youhavetentative'] = 'Ha aceptado tentativamente esta invitación';
$labels['youhavedeclined'] = 'Ha rechazado esta invitación';
$labels['youhavedelegated'] = 'Ha delegado esta invitación';
$labels['youhaveneeds-action'] = 'Su respuesta a esta invitación está aún pendiente';
$labels['youhavepreviouslyaccepted'] = 'Ha aceptado esta invitación con anterioridad';
$labels['youhavepreviouslytentative'] = 'Ha aceptado tentativamente esta invitación con anterioridad';
$labels['youhavepreviouslydeclined'] = 'Ha rechazado esta invitación con anterioridad';
$labels['youhavepreviouslydelegated'] = 'Ha delegado esta invitación con anterioridad';
$labels['youhavepreviouslyneeds-action'] = 'Su respuesta a esta invitación está aún pendiente';
$labels['attendeeaccepted'] = 'Participante ha aceptado';
$labels['attendeetentative'] = 'Participante ha aceptado tentativamente';
$labels['attendeedeclined'] = 'Participante ha rechazado';
$labels['attendeedelegated'] = 'Participante ha delegado a $delegatedto';
$labels['notanattendee'] = 'No está en la lista como asistente de este objeto';
$labels['outdatedinvitation'] = 'Esta invitación ha sido sustituida por una versión más reciente';
$labels['importtocalendar'] = 'Guardar en mi calendario';
$labels['removefromcalendar'] = 'Eliminar de mi calendario';
$labels['updatemycopy'] = 'Actualizar mi copia';
$labels['deleteobjectconfirm'] = '¿Realmente desea eliminar este objeto?';
$labels['declinedeleteconfirm'] = '¿También desea eliminar este objeto rechazado desde su cuenta?';
$labels['savingdata'] = 'Guardando datos...';
$labels['event'] = 'evento';
$labels['task'] = 'tarea';
$labels['changeobjectconfirm'] = 'Cambiar %s';
$labels['removeobjectconfirm'] = 'Eliminar %s';
$labels['currentobject'] = 'Actual';
$labels['futureobjects'] = 'Futuro';
$labels['allobjects'] = 'Todos';
$labels['deletealltasks'] = 'Eliminar todas las ocurrencias';
$labels['deletealltaskswithchilds'] = 'Eliminar todas las ocurrencias con todas las subtareas';
$labels['saveasnew'] = 'Guardar como nuevo';

?>