<?php

$labels=array();
$labels['pluginname'] = 'Indstillinger';
$labels['plugindescription'] = 'Dette er et hjælper modul. Det er krævet af flere andre moduler.';
$labels['menu'] = 'Menu';
$labels['managefolders'] = 'Håndter mapper';
$labels['account'] = 'Administration af konto';
$labels['classic'] = 'Standard';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Specielle mapper';
$labels['myroundcube'] = 'Min RoundCube Webmail';
$labels['skin_preview'] = 'Forhåndsvisning af brugerflade';

?>