<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/settings/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 05/08/2013 06:23:29
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Einstellungen';
$labels['plugindescription'] = 'Diese Hilfserweiterung wird von einigen anderen Erweiterungen benötigt (z.B. alle hmail_* Erweiterungen).';
$labels['menu'] = 'Menü';
$labels['managefolders'] = 'Ordner verwalten';
$labels['account'] = 'Konto-Einstellungen';
$labels['classic'] = 'Standard';
$labels['larry'] = 'Larry';
$labels['remotefolders'] = 'Spezialordner';
$labels['myroundcube'] = 'MyRoundCube';
$labels['skin_preview'] = 'Vorschau Benutzerobfläche';
$labels['serversettings.serversettings'] = 'Weitere Kontoeinstellungen';

?>