<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/message_highlight/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/15/2014 10:13:47
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['mh_title'] = 'Zvýrazňování zpráv';
$labels['mh_matches'] = 'odpovídá';
$labels['mh_color'] = 'barva';
$labels['mh_delete'] = 'smazat';
$labels['mh_delete_description'] = 'Smazat tento řádek';
$labels['mh_add'] = 'přidat řádek';
$labels['mh_add_description'] = 'Přidat další řádek pod tento řádek';
$labels['deleteconfirm'] = 'Opravdu chcete smazat toto pravidlo pro zvýrazňování?';
$labels['notsaved'] = 'Vaše změny nebyly zatím uloženy.';
$labels['headererror'] = 'Chyba v pravidle pro zvýrazňování';
$labels['inputempty'] = 'Jeden nebo více záznamů je prázdných';
$labels['invalidcolor'] = 'Neplatná barva';

?>