<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/message_highlight/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 12/25/2012 00:11:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['mh_title'] = 'Resaltar Mensajes';
$labels['mh_matches'] = 'coincide con';
$labels['mh_color'] = 'color';
$labels['mh_delete'] = 'eliminar';
$labels['mh_delete_description'] = 'Borrar esta linea';
$labels['mh_add'] = 'añadir una fila';
$labels['mh_add_description'] = 'Agregar fila adicional debajo de esta fila';
$labels['deleteconfirm'] = '¿Está seguro de que quiere eliminar esta regla?';
$labels['notsaved'] = 'Los cambios no han sido guardados todavía.';
$labels['headererror'] = 'Error en regla de mensaje';
$labels['inputempty'] = 'Una o más de sus coincidencias está(n) vacía(s)';
$labels['invalidcolor'] = 'Color no válido';

?>