<?php
$labels['mh_title'] = 'Resaltar Mensajes';
$labels['mh_matches'] = 'coincide con';
$labels['mh_color'] = 'color';
$labels['mh_delete'] = 'eliminar';
$labels['mh_delete_description'] = 'Borrar esta linea';
$labels['mh_add'] = 'añadir una fila';
$labels['mh_add_description'] = 'Agregar una fila adicional debajo de esta fila';
$labels['deleteconfirm'] = '¿Está seguro de que quiere eliminar esta regla?';

// these should never happen, but add anyways
$labels['headererror'] = 'Error en regla de mensaje';
$labels['inputempty'] = 'Una o más de sus coincidencias está(n) vacía(s)';
$labels['invalidcolor'] = 'Color no válido';

?>