<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/message_highlight/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 01/15/2015 10:03:25
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['mh_title'] = 'Korosta viestejä';
$labels['mh_matches'] = 'vastaa';
$labels['mh_color'] = 'väri';
$labels['mh_delete'] = 'poista';
$labels['mh_delete_description'] = 'Poista tämä rivi';
$labels['mh_add'] = 'lisää rivi';
$labels['mh_add_description'] = 'Lisää extrarivi tämän rivin alapuolelle';
$labels['deleteconfirm'] = 'Oletko varma että haluat poistaa tämän säännön?';
$labels['notsaved'] = 'Muutoksia ei ole vielä tallennettu.';
$labels['headererror'] = 'Virhe viestisäännössä';
$labels['inputempty'] = 'Yksi tai enemmän säännöistä on tyhjä';
$labels['invalidcolor'] = 'Väärä väri';

?>