<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: www.aspHOSTpage.com                                           |
+-----------------------------------------------------------------------+

*/

$labels['mh_title'] = 'Üzenet kiemelése';
$labels['mh_matches'] = '=';
$labels['mh_color'] = 'szín';
$labels['mh_delete'] = 'Törlés';
$labels['mh_delete_description'] = 'Kiemelés szabály törlése';
$labels['mh_add'] = 'Új';
$labels['mh_add_description'] = 'Új kiemelés szabály hozzáadása';
$labels['deleteconfirm'] = 'Biztos, hogy törlöd ezt a kiemelés szabályt?';
$labels['notsaved'] = 'A változtatások még nincsenek letárolva.';

// these should never happen, but add anyways
$labels['headererror'] = 'Hibás a szabály';
$labels['inputempty'] = 'Egy vagy több feltétel nincsen kitöltve';
$labels['invalidcolor'] = 'Érvénytelen színkód';

?>