<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/message_highlight/localization/pl_PL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tomasz.chilinski@chilan.com - 06/22/2013 12:40:28
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['mh_title'] = 'Podświetlanie wiadomości';
$labels['mh_matches'] = 'dopasowania';
$labels['mh_color'] = 'kolor';
$labels['mh_delete'] = 'usuń';
$labels['mh_delete_description'] = 'Usuń ten wiersz';
$labels['mh_add'] = 'dodaj wiersz';
$labels['mh_add_description'] = 'Dodaj dodatkowy wiersz za tym wierszem';
$labels['deleteconfirm'] = 'Czy na pewno chcesz usunąć tą regułę?';
$labels['notsaved'] = 'Zmiany nie zostały jeszcze zapisane.';
$labels['headererror'] = 'Błąd w regule wiadomości';
$labels['inputempty'] = 'Jedno lub więcej dopasowań jest pustych';
$labels['invalidcolor'] = 'Niepoprawny kolor';

?>