<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/message_highlight/localization/pt_BR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: filhocf - 07/19/2012 15:14:27
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['mh_title'] = 'Destaques de Mensagens';
$labels['mh_matches'] = 'combina';
$labels['mh_color'] = 'cor';
$labels['mh_delete'] = 'excluir';
$labels['mh_delete_description'] = 'Excluir essa linha';
$labels['mh_add'] = 'adicionar linha';
$labels['mh_add_description'] = 'Adicionar uma linha extra depois desta linha';
$labels['deleteconfirm'] = 'Você realmente deseja excluir esta regra?';
$labels['notsaved'] = 'Suas mudanças ainda não foram salvas.';
$labels['headererror'] = 'Erro na regra de mensagem';
$labels['inputempty'] = 'Uma ou mais de suas regras estão vazias';
$labels['invalidcolor'] = 'Cor inválida';

?>