<?php
$labels['mh_title'] = '高亮显示';
$labels['mh_matches'] = '匹配';
$labels['mh_color'] = '颜色';
$labels['mh_delete'] = '删除';
$labels['mh_delete_description'] = '删除这一行';
$labels['mh_add'] = '添加';
$labels['mh_add_description'] = '在这一行下面新增一行';
$labels['deleteconfirm'] = '你确定要删除这条规则?';
$labels['notsaved'] = '你的修改未保存';

// these should never happen, but add anyways
$labels['headererror'] = '规则错误';
$labels['inputempty'] = '一个或多个匹配为空';
$labels['invalidcolor'] = '无效颜色';

?>