<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/archivefolder/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:31:44
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Archive Folder';
$labels['plugindescription'] = 'Move messages to predefined Archive folder.';
$labels['buttontitle'] = 'Archive this message';
$labels['archived'] = 'Successfully archived';
$labels['archivefolder'] = 'Archive';
$labels['folders'] = 'All Folders';

?>