<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Cartella di archivio';
$labels['plugindescription'] = 'Sposta i messaggi nella cartella di archivio predefinita.';
$labels['buttontitle'] = 'Archivia questo messaggio';
$labels['archived'] = 'Archiviato con successo';
$labels['archivefolder'] = 'Archivio ';
$labels['folders'] = 'Tutte le Cartelle';

?>