<?php

/*
+-----------------------------------------------------------------------+
| language/uk_UA/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['buttontitle'] = 'Архівувати повідомлення';
$labels['archived'] = 'Успішно виконано';
$labels['archivefolder'] = 'Архів';
$labels['folders'] = 'Всі директорії';

?>