<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['planner'] = 'Planificador';
$labels['pluginname'] = 'Planificador';
$labels['plugindescription'] = 'És una barreja entre calendari i llista de tasques';
$labels['incompatiblebrowser'] = 'Per accedir al planificador, fes servir Explorer 9 o un altre navegador';
$labels['view'] = 'Vista';
$labels['select_view'] = 'Seleccionar vista';
$labels['flags'] = 'Marcadors';
$labels['preview'] = 'Previsualitzar';
$labels['new'] = 'Afegir nova tasca';
$labels['done'] = 'Fet';
$labels['done_plan'] = 'Marcar tasca com a assolida';
$labels['star'] = 'Destacar';
$labels['edit'] = 'Editar tasca';
$labels['delete'] = 'Esborrar tasca';
$labels['remove'] = 'Treure tasca';
$labels['remove_flag'] = 'Treure marcador';
$labels['remove_date'] = 'Esborrar data amb clic de botó dret';
$labels['toggle'] = 'Alternar marcador';
$labels['expunge'] = 'Esborrar articles';
$labels['expunge_deleted'] = 'Esborrar permanentment els articles esborrats';
$labels['help'] = 'Ajuda';
$labels['cancel'] = 'Cancel·la';
$labels['search'] = 'Cerca';
$labels['searchresult'] = 'Resultats de la cerca:';
$labels['matches'] = 'Coincidència';
$labels['matches_plural'] = 'Coincidències';
$labels['all'] = 'Tot';
$labels['show_all'] = 'Mostrar totes les tasques';
$labels['starred'] = 'Destacades';
$labels['star_plan'] = 'Destacar article';
$labels['unstar_plan'] = 'Desmarcar article';
$labels['today'] = 'Avui';
$labels['show_today'] = 'Mostrar les tasques d\'avui';
$labels['tomorrow'] = 'Demà';
$labels['show_tomorrow'] = 'Mostrar les tasques de demà';
$labels['week'] = 'Setmana';
$labels['deleted'] = 'Esborrats';
$labels['overdue'] = 'Endarrerit';
$labels['show_overdue'] = 'Mostrar tasques endarrerides';
$labels['birthdays'] = 'Aniversaris';
$labels['birthdays_singular'] = 'Aniversari';
$labels['filter'] = 'Filtre';
$labels['nofilter'] = 'Cap';
$labels['removefilter'] = 'Esborrar filtre';
$labels['plans'] = 'Tasques';
$labels['todos'] = 'Per fer';
$labels['birthdays_yes'] = 'Mostrar aniversaris';
$labels['birthdays_no'] = 'No mostrar aniversaris';
$labels['timeText'] = 'Temps';
$labels['hourText'] = 'Hores';
$labels['minuteText'] = 'Minuts';
$labels['datetimehints'] = 'Formats de data i hora (exemples)';
$labels['errorsaving'] = 'Error mentre es desava';
$labels['happybirthday'] = 'Felicitacions d\'aniversari!';

?>