<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:05:14
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Planen';
$labels['pluginname'] = 'Termine und Aufgaben planen';
$labels['plugindescription'] = 'Verwalten Sie Ihre Aufgaben und Termine mit einem einfachen Kalender.';
$labels['incompatiblebrowser'] = 'Bitte benutzen Sie für den Planer Internet Explorer 9 oder einen alternativen Browser.';
$labels['plan'] = 'Eintragen';
$labels['view'] = 'Ansicht';
$labels['select_view'] = 'Ansicht auswählen';
$labels['flags'] = 'Kennzeichnungen';
$labels['preview'] = 'Vorschau';
$labels['new'] = 'Neuen Eintrag hinzufügen';
$labels['done'] = 'Erledigt';
$labels['done_plan'] = 'Eintrag als erledigt kennzeichnen';
$labels['star'] = 'Stern';
$labels['edit'] = 'Eintrag editieren';
$labels['delete'] = 'Eintrag löschen';
$labels['remove'] = 'Eintrag endgültig entfernen';
$labels['remove_flag'] = 'Kennzeichnung entfernen';
$labels['remove_date'] = 'Rechte Maustaste zum Entfernen des Datums klicken';
$labels['toggle'] = 'Kennzeichnung umkehren';
$labels['expunge'] = 'Alle entfernen';
$labels['expunge_deleted'] = 'Gelöschte Einträge endgültig entfernen';
$labels['help'] = 'Hilfe';
$labels['cancel'] = 'Abbrechen';
$labels['search'] = 'Suchen';
$labels['searchresult'] = 'Suchergebnis für';
$labels['matches'] = 'Treffer';
$labels['matches_plural'] = 'Treffer';
$labels['all'] = 'Alle';
$labels['show_all'] = 'Alle Einträge anzeigen';
$labels['starred'] = 'Markiert';
$labels['star_plan'] = 'Eintrag markieren';
$labels['unstar_plan'] = 'Markierung entfernen';
$labels['today'] = 'Heute';
$labels['show_today'] = 'Heutige Einträge anzeigen';
$labels['tomorrow'] = 'Morgen';
$labels['show_tomorrow'] = 'Morgige Einträge anzeigen';
$labels['week'] = 'Diese Woche';
$labels['deleted'] = 'Gelöscht';
$labels['overdue'] = 'Überfällig';
$labels['show_overdue'] = 'Überfällige Einträge anzeigen';
$labels['birthdays'] = 'Geburtstage';
$labels['birthdays_singular'] = 'Geburtstag';
$labels['filter'] = 'Filter';
$labels['nofilter'] = 'Kein Filter';
$labels['removefilter'] = 'Filter entfernen';
$labels['plans'] = 'Ereignisse';
$labels['todos'] = 'Aufgaben';
$labels['birthdays_yes'] = 'Geburtstage anzeigen';
$labels['birthdays_no'] = 'Geburtstage nicht anzeigen';
$labels['timeText'] = 'Uhrzeit';
$labels['hourText'] = 'Stunden';
$labels['minuteText'] = 'Minuten';
$labels['datetimehints'] = 'Datums- und Uhrzeitformate (Beispiele)';
$labels['errorsaving'] = 'Zeitüberschreitung';
$labels['happybirthday'] = 'Herzliche Glückwünsche zum Geburtstag!';

?>