<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/03/2012 07:19:42
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Planificador';
$labels['pluginname'] = 'Planificador';
$labels['plugindescription'] = 'Este es un complemento mixto entre un calendario simple y una lista de tareas.';
$labels['incompatiblebrowser'] = 'Para acceder al Planificador, por favor use Internet Explorer 9 o un explorador alternativo.';
$labels['plan'] = 'Crear';
$labels['view'] = 'Ver';
$labels['select_view'] = 'Seleccionar vista';
$labels['flags'] = 'Indicadores';
$labels['preview'] = 'Vista Previa';
$labels['new'] = 'Agregar nuevo plan';
$labels['done'] = 'Realizado';
$labels['done_plan'] = 'Marque el plan como realizado';
$labels['star'] = 'Resaltar';
$labels['edit'] = 'Editar plan';
$labels['delete'] = 'Eliminar plan';
$labels['remove'] = 'Remover plan';
$labels['remove_flag'] = 'Remover indicador';
$labels['remove_date'] = 'Quitar fecha con botón derecho del ratón';
$labels['toggle'] = 'Activar indicador';
$labels['expunge'] = 'Eliminar elementos';
$labels['expunge_deleted'] = 'Remover elementos eliminados de forma permanente';
$labels['help'] = 'Ayuda';
$labels['cancel'] = 'Cancelar';
$labels['search'] = 'Buscar';
$labels['searchresult'] = 'Resultados de Búsqueda de';
$labels['matches'] = 'igualar';
$labels['matches_plural'] = 'iguala';
$labels['all'] = 'Todos';
$labels['show_all'] = 'Mostrat todos los planes';
$labels['starred'] = 'Resaltado';
$labels['star_plan'] = 'Resaltar elemento';
$labels['unstar_plan'] = 'Atenuar elemento';
$labels['today'] = 'Hoy';
$labels['show_today'] = 'Mostrar planes de hoy';
$labels['tomorrow'] = 'Mañana';
$labels['show_tomorrow'] = 'Mostrar planes para mañana';
$labels['week'] = 'Semana';
$labels['deleted'] = 'Eliminado';
$labels['overdue'] = 'Atrasado';
$labels['show_overdue'] = 'Mostrar planes atrasados';
$labels['birthdays'] = 'Cumpleaños';
$labels['birthdays_singular'] = 'Cumpleaño';
$labels['filter'] = 'Filtro';
$labels['nofilter'] = 'Ninguno';
$labels['removefilter'] = 'Remover Filtro';
$labels['plans'] = 'Planes';
$labels['todos'] = 'ToDo\'s';
$labels['birthdays_yes'] = 'Mostrar Cumpleaños';
$labels['birthdays_no'] = 'No mostrar Cumpleaños';
$labels['timeText'] = 'Horario';
$labels['hourText'] = 'Horas';
$labels['minuteText'] = 'Minutos';
$labels['datetimehints'] = 'Formatos de Hora y Fecha (Ejemplos)';
$labels['errorsaving'] = 'Ha ocurrido un error al guardar';
$labels['happybirthday'] = 'Saludos Feliz cumpleaños!';

?>