<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 09/05/2012 11:23:12
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Planning';
$labels['pluginname'] = 'Planner';
$labels['plugindescription'] = 'Plugin hybride entre un simple agenda et un liste de tâche';
$labels['incompatiblebrowser'] = 'Pour accéder Planner, vous devez utilisez Internet Explorer 9 ou un autre naviguateur';
$labels['view'] = 'Voir';
$labels['select_view'] = 'Choisir une vue';
$labels['flags'] = 'Drapeaux';
$labels['preview'] = 'Prévisualisation';
$labels['new'] = 'Ajouter une nouvelle tâche';
$labels['done'] = 'Terminé';
$labels['done_plan'] = 'Marquer la tâche terminée';
$labels['star'] = 'Etoile';
$labels['edit'] = 'Editer une tâche';
$labels['delete'] = 'Effacer une tâche';
$labels['remove'] = 'Enlever une tâche';
$labels['remove_flag'] = 'Enlever le drapeau';
$labels['remove_date'] = 'Enlever la date sur clic-droit';
$labels['toggle'] = 'Inverser le drapeau';
$labels['expunge'] = 'Effacer des entrées';
$labels['expunge_deleted'] = 'Effacer des entrées définitvement';
$labels['help'] = 'Aide';
$labels['cancel'] = 'Abandonner';
$labels['search'] = 'Rechercher';
$labels['searchresult'] = 'Résultats de la recherche';
$labels['matches'] = 'correspond';
$labels['matches_plural'] = 'correspond';
$labels['all'] = 'Tous';
$labels['show_all'] = 'Montrer toutes les tâches';
$labels['starred'] = 'Favoris';
$labels['star_plan'] = 'Marquer une entrée d\'une étoile';
$labels['unstar_plan'] = 'Enlever l\'étoile';
$labels['today'] = 'Aujourd\'hui';
$labels['show_today'] = 'Montrer les tâches du jour';
$labels['tomorrow'] = 'Demain';
$labels['show_tomorrow'] = 'Montrer les tâches de demain';
$labels['week'] = 'Semaine';
$labels['deleted'] = 'Effacé';
$labels['overdue'] = 'Dépassé';
$labels['show_overdue'] = 'Montrer les tâches dépassées';
$labels['birthdays'] = 'Anniversaires';
$labels['birthdays_singular'] = 'Anniversaire';
$labels['filter'] = 'Filtre';
$labels['nofilter'] = 'Aucun';
$labels['removefilter'] = 'Enlever le filtre';
$labels['plans'] = 'Tâches';
$labels['todos'] = 'A faire';
$labels['birthdays_yes'] = 'Montrer les anniversaires';
$labels['birthdays_no'] = 'Ne pas montrer les anniversaires';
$labels['timeText'] = 'Temps';
$labels['hourText'] = 'Heures';
$labels['minuteText'] = 'Minutes';
$labels['datetimehints'] = 'Format date - heure (exemples)';
$labels['errorsaving'] = 'Erreur lors de la sauvegarde';
$labels['happybirthday'] = 'Bon anniversaire !';

?>