<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['planner'] = 'Planner';
$labels['pluginname'] = 'Planner';
$labels['plugindescription'] = 'Questo è una via di mezzo tra un semplice calendario e una lista \'Da Fare\'';
$labels['incompatiblebrowser'] = 'Per accedere al Planner utilizza Internet Explorer 9 o un programma di navigazione alternativo.';
$labels['plan'] = 'Crea';
$labels['view'] = 'Vista';
$labels['select_view'] = 'Seleziona vista';
$labels['flags'] = 'Contrassegni';
$labels['preview'] = 'Anteprima';
$labels['new'] = 'Aggiungi un nuovo evento';
$labels['done'] = 'Fatto';
$labels['done_plan'] = 'Segna l\'evento come fatto';
$labels['star'] = 'Etichetta';
$labels['edit'] = 'Modifica evento';
$labels['delete'] = 'Cancella evento';
$labels['remove'] = 'Rimuovi evento';
$labels['remove_flag'] = 'Rimuovi contrassegno';
$labels['remove_date'] = 'Rimuovi la data';
$labels['toggle'] = 'Inverti la selezione';
$labels['expunge'] = 'Cancella eventi';
$labels['expunge_deleted'] = 'Rimuovi definitivamente gli eventi cancellati';
$labels['help'] = 'Aiuto';
$labels['cancel'] = 'Annulla';
$labels['search'] = 'Cerca';
$labels['searchresult'] = 'Carca Risultati per';
$labels['matches'] = 'corrisponde';
$labels['matches_plural'] = 'corrispondono';
$labels['all'] = 'Tutti';
$labels['show_all'] = 'Mostra tutti gli eventi';
$labels['starred'] = 'Etichettato';
$labels['star_plan'] = 'Aggiungi etichetta';
$labels['unstar_plan'] = 'Rimuovi etichetta';
$labels['today'] = 'Oggi';
$labels['show_today'] = 'Mostra gli eventi di oggi';
$labels['tomorrow'] = 'Domani';
$labels['show_tomorrow'] = 'Mostra gli eventi di domani';
$labels['week'] = 'Settimana';
$labels['deleted'] = 'Cancellati';
$labels['overdue'] = 'Scaduto';
$labels['show_overdue'] = 'Mostra eventi scaduti';
$labels['birthdays'] = 'Compleanni';
$labels['birthdays_singular'] = 'Compleanno';
$labels['filter'] = 'Filtro';
$labels['nofilter'] = 'Nessuno';
$labels['removefilter'] = 'Rimuovi Filtro';
$labels['plans'] = 'Eventi';
$labels['todos'] = 'Da fare';
$labels['birthdays_yes'] = 'Mostra i Compleanni';
$labels['birthdays_no'] = 'Non mostrare i Compleanni';
$labels['timeText'] = 'Orario';
$labels['hourText'] = 'Ore';
$labels['minuteText'] = 'Minuti';
$labels['datetimehints'] = 'Formati di data e ora (Esempi)';
$labels['errorsaving'] = 'Errore durante il salvataggio';
$labels['happybirthday'] = 'Auguri di Buon Compleanno!';

?>