<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Emiel Wieldraaijer - 12/16/2012 13:44:48
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Planner';
$labels['pluginname'] = 'Planner';
$labels['plugindescription'] = 'Dit is een tussenoplossing voor een simpele agenda en een nog-te-doen lijst.';
$labels['incompatiblebrowser'] = 'Om de planner te benaderen dient u Internet Explorer 9 of een alternatieve browser te gebruiken (bijvoorbeeld Google Chrome)';
$labels['plan'] = 'Plan';
$labels['view'] = 'Bekijken';
$labels['select_view'] = 'Selecteer kijkvenster';
$labels['flags'] = 'Markeringen';
$labels['preview'] = 'Voorvertoning';
$labels['new'] = 'Nieuw';
$labels['done'] = 'Klaar';
$labels['done_plan'] = 'Markeer als klaar';
$labels['star'] = 'Ster';
$labels['edit'] = 'Wijzig';
$labels['delete'] = 'Verwijder';
$labels['remove'] = 'Planning verwijderen';
$labels['remove_flag'] = 'Markering verwijderen';
$labels['remove_date'] = 'Verwijder tijdstip met rechter muisklik';
$labels['toggle'] = 'Markering in- of uitschakelen';
$labels['expunge'] = 'Verwijderde berichten';
$labels['expunge_deleted'] = 'Verwijderde berichten verwijderen';
$labels['help'] = 'Help';
$labels['cancel'] = 'Annuleren';
$labels['search'] = 'Zoeken';
$labels['searchresult'] = 'Zoek resultaat voor';
$labels['matches'] = 'overeenkomst';
$labels['matches_plural'] = 'overeenkomsten';
$labels['all'] = 'Alle';
$labels['show_all'] = 'Toon alle planningen';
$labels['starred'] = 'Ster';
$labels['star_plan'] = 'Plaats ster bij item';
$labels['unstar_plan'] = 'Verwijder ster bij item';
$labels['today'] = 'Vandaag';
$labels['show_today'] = 'Toon planning voor vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['show_tomorrow'] = 'Toon planning voor morgen';
$labels['week'] = 'Week';
$labels['deleted'] = 'Verwijderd';
$labels['overdue'] = 'Verlopen';
$labels['show_overdue'] = 'Toon verlopen planningen';
$labels['birthdays'] = 'Verjaardagen';
$labels['birthdays_singular'] = 'Verjaardag';
$labels['filter'] = 'Filter';
$labels['nofilter'] = 'Geen';
$labels['removefilter'] = 'Filter verwijderen';
$labels['plans'] = 'Plannen';
$labels['todos'] = 'Nog-te-doen';
$labels['birthdays_yes'] = 'Verjaardagen tonen';
$labels['birthdays_no'] = 'Verjaardagen niet tonen';
$labels['timeText'] = 'Tijd';
$labels['hourText'] = 'Uren';
$labels['minuteText'] = 'Minuten';
$labels['datetimehints'] = 'Datum en tijd formaat (voorbeelden)';
$labels['errorsaving'] = 'Er is een fout opgetreden bij het opslaan van de wijzigingen';
$labels['happybirthday'] = 'Verjaardags groet!';

?>