<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['planner'] = 'Planer';
$labels['pluginname'] = 'Planer';
$labels['plugindescription'] = 'To jest hybryda pomiędzy prostym kalendarzem a lista do zrobienia.';
$labels['incompatiblebrowser'] = 'Aby używać Planera , proszę uzywać IE 9 lub innej przeglądarki.';
$labels['view'] = 'Widok';
$labels['select_view'] = 'Wybierz Widok';
$labels['flags'] = 'Flagi';
$labels['preview'] = 'Podgląd';
$labels['new'] = 'Dodaj nowy plan';
$labels['done'] = 'Wykonane';
$labels['done_plan'] = 'Zaznacz jako wykonane';
$labels['star'] = 'Zaznacz';
$labels['edit'] = 'Edytuj plan';
$labels['delete'] = 'Usuń plan';
$labels['remove'] = 'Usuń plan';
$labels['remove_flag'] = 'Usuń flagę';
$labels['remove_date'] = 'Usuwaj datę prawym klikiem';
$labels['toggle'] = 'Przełącz flagę';
$labels['expunge'] = 'Usuń pozycje';
$labels['expunge_deleted'] = 'Usuń pozycje na zawsze';
$labels['help'] = 'Pomoc';
$labels['cancel'] = 'Anuluj';
$labels['search'] = 'Szukaj';
$labels['searchresult'] = 'Szukaj po ';
$labels['matches'] = 'dopasowanie';
$labels['matches_plural'] = 'trafienia';
$labels['all'] = 'Wszystkie';
$labels['show_all'] = 'Pokaż wszystkie plany';
$labels['starred'] = 'Zaznaczony';
$labels['star_plan'] = 'Zaznaczona pozycja';
$labels['unstar_plan'] = 'Odznacz pozycje';
$labels['today'] = 'Dziś';
$labels['show_today'] = 'Pokaż plan na dziś';
$labels['tomorrow'] = 'Jutro';
$labels['show_tomorrow'] = 'Pokaż plan na jutro';
$labels['week'] = 'Tydzień';
$labels['deleted'] = 'Usunięte';
$labels['overdue'] = 'Przeterminowane';
$labels['show_overdue'] = 'Pokaż przeterminowane plany';
$labels['birthdays'] = 'Urodziny';
$labels['birthdays_singular'] = 'Urodziny';
$labels['filter'] = 'Filtr';
$labels['nofilter'] = 'brak';
$labels['removefilter'] = 'Usuń filtr';
$labels['plans'] = 'Plany';
$labels['todos'] = 'Do zrobienia';
$labels['birthdays_yes'] = 'Pokaż urodziny';
$labels['birthdays_no'] = 'Nie pokazuj urodzin';
$labels['timeText'] = 'Czas';
$labels['hourText'] = 'Godziny';
$labels['minuteText'] = 'Minuty';
$labels['datetimehints'] = 'Formaty daty i czasu ( Przykłady)';
$labels['errorsaving'] = 'Wystąpił błąd podczas zapisu';
$labels['happybirthday'] = 'Wiadomośc urodzinowa! ';

?>