<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/planner/localization/ru_RU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Pavel - 01/14/2013 15:03:03
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['planner'] = 'Планировщик';
$labels['pluginname'] = 'Планировщик';
$labels['plugindescription'] = 'Это симбиоз календаря и списка дел';
$labels['incompatiblebrowser'] = 'Для входа в Планировщик используйте Internet Explorer 9 или альтернативный браузер';
$labels['view'] = 'Просмотр';
$labels['select_view'] = 'Выбрать просмотр';
$labels['flags'] = 'Флаги';
$labels['preview'] = 'Предпросмотр';
$labels['new'] = 'Добавить новый план';
$labels['done'] = 'Готово';
$labels['done_plan'] = 'Пометить план как завершенный';
$labels['star'] = 'Звезда';
$labels['edit'] = 'Редактировать план';
$labels['delete'] = 'Удалить план';
$labels['remove'] = 'Убрать план';
$labels['remove_flag'] = 'Убрать флаг';
$labels['remove_date'] = 'Убрать дату правым кликом';
$labels['toggle'] = 'Переключить флаг';
$labels['expunge'] = 'Удалить';
$labels['expunge_deleted'] = 'Удалять выделенное навсегда';
$labels['help'] = 'Помощь';
$labels['cancel'] = 'Отмена';
$labels['search'] = 'Поиск';
$labels['searchresult'] = 'Результаты поиска для';
$labels['matches'] = 'Совпадение';
$labels['matches_plural'] = 'Совпадления';
$labels['all'] = 'Все';
$labels['show_all'] = 'Показать все планы';
$labels['starred'] = 'Отмеченные';
$labels['star_plan'] = 'Отмеченный план';
$labels['unstar_plan'] = 'Неотмеченный план';
$labels['today'] = 'Сегодня';
$labels['show_today'] = 'Показать планы на сегодня';
$labels['tomorrow'] = 'Завтра';
$labels['show_tomorrow'] = 'Показать планы на завтра';
$labels['week'] = 'Неделя';
$labels['deleted'] = 'Удаленный';
$labels['overdue'] = 'Опаздывающие';
$labels['show_overdue'] = 'Показать опаздывающие планы';
$labels['birthdays'] = 'Дни рождения';
$labels['birthdays_singular'] = 'День рождения';
$labels['filter'] = 'Фильтр';
$labels['nofilter'] = 'Нет';
$labels['removefilter'] = 'Убрать фильтр';
$labels['plans'] = 'Планы';
$labels['todos'] = 'Дела';
$labels['birthdays_yes'] = 'Показать дни рождения';
$labels['birthdays_no'] = 'Не показывать дни рождения';
$labels['timeText'] = 'Время';
$labels['hourText'] = 'Часы';
$labels['minuteText'] = 'Минуты';
$labels['datetimehints'] = 'Форматы даты и времени (примеры)';
$labels['errorsaving'] = 'Возникла ошибка во время сохранения';
$labels['happybirthday'] = 'Поздравления с днем рождения';

?>