<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/companyaddressbook_plus/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 07/06/2014 16:18:32
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Companyaddressbook +';
$labels['plugindescription'] = 'Hilfserweiterung für den administrativen Bereich der Erweiterung.';

?>