<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Archivovat složku';
$labels['plugindescription'] = 'Umožní přesun zpráv do předdefinované archivní složky';
$labels['buttontitle'] = 'Archivovat tuto zprávu';
$labels['archived'] = 'Úspěšně archivováno';
$labels['archivefolder'] = 'Archiv';
$labels['folders'] = 'Všechny složky';

?>