<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['buttontitle'] = 'Arkiver denne besked';
$labels['archived'] = 'Succesfuldt arkiveret';
$labels['archivefolder'] = 'Arkiv';
$labels['folders'] = 'Alle mapper';

?>