<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/archivefolder/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 04/06/2012 18:24:07
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Archiv-Ordner';
$labels['plugindescription'] = 'Nachrichten archivieren.';
$labels['buttontitle'] = 'Archiv';
$labels['archived'] = 'Nachricht(en) wurde(n) erfolgreich archiviert';
$labels['archivefolder'] = 'Archiv';
$labels['folders'] = 'Alle Ordner';

?>