<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: www.aspHOSTpage.com                                           |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Archívum mappa';
$labels['plugindescription'] = 'Üzenetek áthelyezése az Archívum  mappába';
$labels['buttontitle'] = 'Üzenet archíválása';
$labels['archived'] = 'Sikeresen archíválva';
$labels['archivefolder'] = 'Archívum';
$labels['folders'] = 'Minden mappa';

?>