<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/archivefolder/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Ling Fude - 03/19/2012 14:53:12
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Pasta de Arquivo';
$labels['plugindescription'] = 'Mover mensagens para a pasta de Arquivo predefinida.';
$labels['buttontitle'] = 'Arquivar esta mensagem';
$labels['archived'] = 'Arquivada com sucesso';
$labels['archivefolder'] = 'Arquivo';
$labels['folders'] = 'Todas as pastas';

?>