<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Doubrovine S.                                                 |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Архивная Папка';
$labels['plugindescription'] = 'Перемещение сообщений в заранее определённую Архивную Папку.';
$labels['buttontitle'] = 'Переместить выбранное в архив';
$labels['archived'] = 'Перенесено в Архив';
$labels['archivefolder'] = 'Архив';
$labels['folders'] = 'Все папки';

?>