<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: ysliuthomas                                                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['buttontitle'] = '封存此信件';
$labels['archived'] = '成功封存';
$labels['archivefolder'] = '封存';
$labels['folders'] = '所有資料夾';

?>