<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/companyaddressbook_plus/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 05/15/2014 07:24:19
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Firemní adresář +';
$labels['plugindescription'] = 'Pomocní doplněk pro administrativní část doplňku "companyaddressbook".';

?>