<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/companyaddressbook_plus/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/17/2015 04:47:53
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Company AddressBooks +';
$labels['plugindescription'] = 'A helper plugin for the administrative section of \'companyaddressbook\' plugin.';

?>