<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/companyaddressbook_plus/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/17/2015 05:18:51
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Libreta de direcciones de Compañía +';
$labels['plugindescription'] = 'Un complemento auxiliar para la sección administrativa del complemento \'companyaddressbook\'.';

?>