<?php

/*
+-----------------------------------------------------------------------+
| language/ca_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Expandeix totes les carpetes';
$labels['collapseall'] = 'Contraure totes les carpetes';
$labels['pluginname'] = 'Expandeix/Contrau carpetes';
$labels['plugindescription'] = 'Afegeix un control per expandir o contraure totes les carpetes a la vegada';

?>