<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/10/2014 14:53:16
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Rozbalit všechny složky';
$labels['collapseall'] = 'Sbalit všechny složky';
$labels['pluginname'] = 'Rozbalit/sbalit složky';
$labels['plugindescription'] = 'Přidá ovládací prvek do voleb umístěných pod seznamem schránek, který umožní rozbalit/sbalit všechny složky najednou.';

?>