<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:03:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Alle Unterordner ausklappen';
$labels['collapseall'] = 'Alle Unterordner einklappen';
$labels['pluginname'] = 'Unterorder ein- und ausklappen';
$labels['plugindescription'] = 'Alle Unterorder mit einem Klick ein- und ausklappen.';

?>