<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/03/2012 06:17:54
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Expand All Folders';
$labels['collapseall'] = 'Collapse All Folders';
$labels['pluginname'] = 'Expand/Collapse Folders';
$labels['plugindescription'] = 'Add a control to expand/collapse all folders at once.';

?>