<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 06/16/2013 19:22:33
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Expandir carpetas';
$labels['collapseall'] = 'Contraer carpetas';
$labels['pluginname'] = 'Expandir/Contraer Carpetas';
$labels['plugindescription'] = 'Agregar un control en el contenedor de opciones de buzón para expandir / contraer todas las carpetas a la vez.';

?>