<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/03/2012 06:18:58
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Expandir carpetas';
$labels['collapseall'] = 'Colapsar carpetas';
$labels['pluginname'] = 'Expandir/Colapsar Carpetas';
$labels['plugindescription'] = 'Agregue un control para expandir / ocultar todas las carpetas a la vez.';

?>