<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 10/28/2014 14:36:42
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Laajenna kaikki kansiot';
$labels['collapseall'] = 'Sulje kaikki kansiot';
$labels['pluginname'] = 'Laajenna/Sulje kansiot';
$labels['plugindescription'] = 'Lisää säätö postilaatikon asetuksiin kansioiden laajentamiseen/sulkemiseen kerralla.';

?>