<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: hugues@mail4us.net - 03/31/2012 15:28:23
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Tout développer';
$labels['collapseall'] = 'Tout réduire';
$labels['pluginname'] = 'Étendre/Réduire les dossiers';
$labels['plugindescription'] = 'Ajoute un contrôle pour étendre/réduire tous les dossiers en même temps.';

?>