<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Emiel Wieldraaijer - 12/16/2012 13:33:48
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Open alle mappen';
$labels['collapseall'] = 'Sluit alle mappen';
$labels['pluginname'] = 'Mappen in- of uitvouwen';
$labels['plugindescription'] = 'Een fuctie toevoegen om alle mappen in een keer in- of uit te vouwen.';

?>