<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['expandall'] = 'Expandir todas as pastas';
$labels['collapseall'] = 'Contrair todas as pastas';
$labels['pluginname'] = 'Expandir/contrair pastas';
$labels['plugindescription'] = 'Adicionar um controle para expandir/contrair todas as pastas de uma vez.';

