<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Ling Fude - 03/19/2012 15:10:29
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Expandir todas as pastas';
$labels['collapseall'] = 'Recolher todas as pastas';
$labels['pluginname'] = 'Expandir/Recolher pastas';
$labels['plugindescription'] = 'Adicione um controle para expandir/recolher todas as pastas de uma só vez.';

?>