<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/pwstrength/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 08/22/2014 11:53:13
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Síla hesla';
$labels['plugindescription'] = 'Pomocný doplněk pro měření síly hesla.';
$labels['pwstrength'] = 'Síla hesla je %s%';
$labels['continue'] = 'Heslo je dost silné.';
$labels['passwordweak'] = 'Heslo je příliš slabé. Použijte prosím bezpečnější heslo. Kombinací malých a velkých písmen, symbolů, čísel a interpunkčních znamének vytvoříte bezpečné a velmi těžko odhadnutelné heslo.';

?>