<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/pwstrength/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 02:46:37
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Fortaleza de contraseña';
$labels['plugindescription'] = 'Complemento Auxiliar para medir la complejidad y fortaleza de la contraseña.';
$labels['pwstrength'] = 'Seguridad de contraseña %s%';
$labels['continue'] = 'La contraseña es lo suficientemente segura.';
$labels['passwordweak'] = 'La contraseña es demasiado débil. Por favor, use una contraseña segura. Una combinación de letras mayúsculas y minúsculas, símbolos, números y puntuaciones es altamente segura y extremadamente difícil de adivinar.';

?>