<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/pwstrength/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 01/22/2015 11:08:18
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Salasanan vahvuus';
$labels['plugindescription'] = 'Helper lisäosa joka tarkistaa salasanan vahvuuden.';
$labels['pwstrength'] = 'Salasanan vahvuus on %s%';
$labels['continue'] = 'Salasana on tarpeeksi vahva.';
$labels['passwordweak'] = 'Salasana on liian heikko. Ole hyvä ja käytä turvallista salasanaa. Yhdistelmä isoja ja pieniä kirjaimia, symboleita, numeroita ja välimerkkejä katsotaan erittäin turvalliseksi ja erittäin vaikeaksi arvata.';

?>