<?php

/*
+-----------------------------------------------------------------------+
| language/bg_BG/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['userinfo'] = 'Информация за потребителя';
$labels['imapserver'] = 'IMAP сървър';
$labels['smtpserver'] = 'SMTP сървър';
$labels['port'] = 'Порт';
$labels['created'] = 'Създаден';
$labels['lastlogin'] = 'Последно влизане';
$labels['defaultidentity'] = 'Самоличност по подразбиране';
$labels['dateformat'] = 'Формат на датата';
$labels['back'] = 'Назад';

?>