<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['userinfo'] = 'Informace o uživateli';
$labels['imapserver'] = 'Server IMAP';
$labels['smtpserver'] = 'SMTP server';
$labels['port'] = 'Port';
$labels['created'] = 'Vytvořen';
$labels['lastlogin'] = 'Poslední přihlášení';
$labels['defaultidentity'] = 'Výchozí profil';
$labels['dateformat'] = 'Formát data';
$labels['back'] = 'Zpět';

?>