<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/11/2014 07:48:28
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Informace o účtu';
$labels['plugindescription'] = 'Zobrazí základní informace o účtu, například IMAP, POP a SMTP protokoly, výchozí identity, uživatelské URL pro CalDAV a CardDAV a další podrobnosti.';
$labels['accountinformation'] = 'Detaily o účtu';
$labels['encryption'] = 'Šifrování';
$labels['port'] = 'Port';
$labels['auth'] = 'Autentizace';
$labels['yes'] = 'Ano';
$labels['no'] = 'Ne';
$labels['created'] = 'Vytvořen';
$labels['lastlogin'] = 'Poslední přihlášení';
$labels['defaultidentity'] = 'Výchozí profil';
$labels['back'] = 'Zpět';
$labels['userinfo'] = 'Informace o uživateli';
$labels['description'] = 'Získat detailní informace o vašem účtu.';
$labels['default'] = 'Výchozí';
$labels['clients'] = 'Doporučení klienti, kteří podporují %s protokol';
$labels['tutorial'] = 'návod';
$labels['copiedtoclipboard'] = 'Zkopírováno do schránky';
$labels['copytoclipboard'] = 'Zkopírovat do schránky';
$labels['calendars'] = 'Kalendáře';
$labels['addressbooks'] = 'Adresáře';
$labels['mailbox'] = 'Mailboxy';

?>