<?php

$labels = array();
$labels['userinfo'] = 'Bruger info';
$labels['imapserver'] = 'IMAP Server';
$labels['smtpserver'] = 'SMTP Server';
$labels['port'] = 'Port';
$labels['created'] = 'Oprettet';
$labels['lastlogin'] = 'Sidste login';
$labels['defaultidentity'] = 'Standard identitet';
$labels['dateformat'] = 'Dato format';
$labels['back'] = 'Tilbage';
$labels['description'] = 'Hent detaljerede informationer om din konto.';

?>