<?php

$labels = array();
$labels['pluginname'] = 'Benutzer Information';
$labels['plugindescription'] = 'Zeigt Ihren Benutzern Informationen zum IMAP-, SMTP-, CalDAV-, CardDAV-Servern sowie das letzte Anmeldedatum und die Standard-Identität an.';
$labels['imapserver'] = 'IMAP-Server';
$labels['smtpserver'] = 'SMTP-Server';
$labels['port'] = 'Port';
$labels['created'] = 'Erstellt';
$labels['lastlogin'] = 'Letzter Login';
$labels['defaultidentity'] = 'Standard-Identität';
$labels['back'] = 'Zurück';
$labels['userinfo'] = 'Benutzerinformationen';
$labels['description'] = 'Sehen Sie Informationen über Ihr Konto ein.';
$labels['default'] = 'Standard';
$labels['clients'] = 'Empfohlene Programme, die das %s-Protokoll unterstützen';
$labels['tutorial'] = 'Anleitung';

?>