<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:34:21
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['imapserver'] = 'IMAP Server';
$labels['smtpserver'] = 'SMTP Server';
$labels['port'] = 'Port';
$labels['created'] = 'Created';
$labels['lastlogin'] = 'Last Login';
$labels['defaultidentity'] = 'Default Identity';
$labels['back'] = 'Back';
$labels['userinfo'] = 'User Info';
$labels['description'] = 'Get detailed information about your Account.';

?>