<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 11/27/2012 05:24:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Account Information';
$labels['plugindescription'] = 'Displays basic account information such as IMAP & SMTP server details, default Identity, user’s CalDAV & CardDAV URLs and other details.';
$labels['accountinformation'] = 'Account information';
$labels['encryption'] = 'Encryption';
$labels['port'] = 'Port';
$labels['auth'] = 'Authenfication';
$labels['yes'] = 'Yes';
$labels['no'] = 'No';
$labels['created'] = 'Created';
$labels['lastlogin'] = 'Last Login';
$labels['defaultidentity'] = 'Default Identity';
$labels['back'] = 'Back';
$labels['userinfo'] = 'User Info';
$labels['description'] = 'Get detailed information about your Account.';
$labels['default'] = 'Default';
$labels['clients'] = 'Recommended clients which support %s protocol';
$labels['tutorial'] = 'Tutorial';

?>