<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 05/08/2013 03:47:20
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Account Information';
$labels['plugindescription'] = 'Displays basic account information such as IMAP, POP & SMTP server protocols, default Identity, user’s CalDAV & CardDAV URLs and other details.';
$labels['accountinformation'] = 'Account Details';
$labels['encryption'] = 'Encryption';
$labels['port'] = 'Port';
$labels['auth'] = 'Authentication';
$labels['yes'] = 'Yes';
$labels['no'] = 'No';
$labels['created'] = 'Created';
$labels['lastlogin'] = 'Last Login';
$labels['defaultidentity'] = 'Default Identity';
$labels['back'] = 'Back';
$labels['userinfo'] = 'User Info';
$labels['description'] = 'Get detailed information about your account.';
$labels['default'] = 'Default';
$labels['clients'] = 'Recommended clients which support %s protocol';
$labels['tutorial'] = 'Tutorial';
$labels['copiedtoclipboard'] = 'Copied to clipboard';
$labels['copytoclipboard'] = 'Copy to clipboard';
$labels['calendars'] = 'Calendars';
$labels['addressbooks'] = 'Addressbooks';
$labels['mailbox'] = 'Mailbox';

?>