<?php

$labels = array();
$labels['pluginname'] = 'Account Informations';
$labels['plugindescription'] = 'Displays basic account information such as IMAP & SMTP server details, default Identity, user’s CalDAV & CardDAV URLs and other details.';
$labels['imapserver'] = 'IMAP Server';
$labels['smtpserver'] = 'SMTP Server';
$labels['port'] = 'Port';
$labels['created'] = 'Created';
$labels['lastlogin'] = 'Last Login';
$labels['defaultidentity'] = 'Default Identity';
$labels['back'] = 'Back';
$labels['userinfo'] = 'User Info';
$labels['description'] = 'Get detailed information about your Account.';
$labels['default'] = 'Default';
$labels['clients'] = 'Recommended clients which support %s protocol';
$labels['tutorial'] = 'Tutorial';

?>