<?php

$labels = array();
$labels['userinfo'] = 'Información de usuario';
$labels['imapserver'] = 'Servidor IMAP';
$labels['smtpserver'] = 'Servidor SMTP';
$labels['port'] = 'Puerto';
$labels['created'] = 'Creado';
$labels['lastlogin'] = 'Último acceso';
$labels['defaultidentity'] = 'Identidad por omisión';
$labels['dateformat'] = 'Formato de fecha';
$labels['back'] = 'Atrás';
$labels['description'] = 'Obtén información detallada de tu Cuenta.';

?>