<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 12/11/2012 07:42:26
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Información de Cuenta';
$labels['plugindescription'] = 'Muestra información básica de la cuenta, como datos del servidor IMAP, POP y SMTP, Identidad predeterminada, las direcciones URL de CalDAV y CardDAV del usuario y otros detalles.';
$labels['accountinformation'] = 'Detalles de cuenta';
$labels['encryption'] = 'Encriptación';
$labels['port'] = 'Puerto';
$labels['auth'] = 'Autenticación';
$labels['yes'] = 'Si';
$labels['no'] = 'No';
$labels['created'] = 'Creado';
$labels['lastlogin'] = 'Último acceso';
$labels['defaultidentity'] = 'Identidad por omisión';
$labels['back'] = 'Atrás';
$labels['userinfo'] = 'Información de usuario';
$labels['description'] = 'Obtén información detallada de tu Cuenta.';
$labels['default'] = 'Predeterminado';
$labels['clients'] = 'Clientes recomendados que soportan protocolo %s';
$labels['tutorial'] = 'Tutorial';

?>