<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 10/08/2012 15:47:24
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['imapserver'] = 'Serveur IMAP';
$labels['smtpserver'] = 'Serveur SMTP';
$labels['port'] = 'Port';
$labels['created'] = 'Créé';
$labels['lastlogin'] = 'Dernière connexion';
$labels['defaultidentity'] = 'Identité par défaut';
$labels['back'] = 'Retour';
$labels['userinfo'] = 'Info utilistateur';
$labels['description'] = 'Affichez des informations détaillées de votre compte email';
$labels['default'] = 'Défaut';
$labels['clients'] = 'Clients recommandés qui supportent le protocole %s ';
$labels['tutorial'] = 'Tutoriel';

?>