<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 12/11/2012 12:01:33
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Information sur le compte email';
$labels['plugindescription'] = 'Afficher des informations de base sur la configuration IMAP, SMTP, POP3, identité du compte, CarDDav et autres détails';
$labels['accountinformation'] = 'Détails du compte';
$labels['encryption'] = 'Encryption';
$labels['port'] = 'Port';
$labels['auth'] = 'Authentification';
$labels['yes'] = 'Oui';
$labels['no'] = 'Non';
$labels['created'] = 'Créé';
$labels['lastlogin'] = 'Dernière connexion';
$labels['defaultidentity'] = 'Identité par défaut';
$labels['back'] = 'Retour';
$labels['userinfo'] = 'Info utilistateur';
$labels['description'] = 'Affichez des informations détaillées de votre compte email';
$labels['default'] = 'Défaut';
$labels['clients'] = 'Clients recommandés qui supportent le protocole %s ';
$labels['tutorial'] = 'Tutoriel';

?>