<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['userinfo'] = 'Informacje o użytkowniku';
$labels['imapserver'] = 'Serwer IMAP';
$labels['smtpserver'] = 'Serwer SMTP';
$labels['port'] = 'Port';
$labels['created'] = 'Utworzono';
$labels['lastlogin'] = 'Ostatnie logowanie';
$labels['defaultidentity'] = 'Domyślny identyfikator';
$labels['dateformat'] = 'Format daty';
$labels['back'] = 'Powrót';

?>
