<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Informcje o koncie';
$labels['plugindescription'] = 'Pokazuje podstawowe informacje o koncie i serwerze POP3/IMAP, tożsamości użytkownika, linki do serwerów CalDAV i CardDAV.';
$labels['accountinformation'] = 'Informacje o koncie';
$labels['encryption'] = 'Szyfrowanie';
$labels['port'] = 'Port';
$labels['auth'] = 'Autentykacja';
$labels['yes'] = 'Tak';
$labels['no'] = 'Nie';
$labels['created'] = 'Utworzono';
$labels['lastlogin'] = 'Ostatnie logowanie';
$labels['defaultidentity'] = 'Domyślny identyfikator';
$labels['back'] = 'Powrót';
$labels['userinfo'] = 'Informacje o użytkowniku';
$labels['description'] = 'Pobierz dokładne informacje o swoim koncie.';
$labels['default'] = 'Domyślne';
$labels['clients'] = 'Zalecany klient który wspiera %s protokoł';
$labels['tutorial'] = 'Samouczek';
$labels['copytoclipboard'] = 'Skopjuj do schowka: CRTL+C i Enter';
$labels['copytoclipboardtitle'] = 'Skopjuj do schowka';

?>