<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                              |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['imapserver'] = 'Servidor IMAP';
$labels['smtpserver'] = 'Servidor SMTP';
$labels['port'] = 'Porta';
$labels['created'] = 'Criado';
$labels['lastlogin'] = 'Última conexão';
$labels['defaultidentity'] = 'Identidade padrão';
$labels['back'] = 'Voltar';
$labels['userinfo'] = 'Informação do Usuário';
$labels['description'] = 'Buscar informações detalhadas sobre sua conta.';

