<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/moreuserinfo/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Ling Fude - 03/19/2012 15:16:11
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['imapserver'] = 'Servidor IMAP';
$labels['smtpserver'] = 'Servidor SMTP';
$labels['port'] = 'Porta';
$labels['created'] = 'Criado em';
$labels['lastlogin'] = 'Último acesso';
$labels['defaultidentity'] = 'Identidade pré-definida';
$labels['back'] = 'Voltar';
$labels['userinfo'] = 'Info. do utilizador';
$labels['description'] = 'Obtenha informações detalhadas da sua conta.';

?>