<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Udfold alle mapper';
$labels['collapseall'] = 'Luk alle mapper';
$labels['pluginname'] = 'Udfold/Luk mapper';
$labels['plugindescription'] = 'Tilføjer en kontrolmulighed under postkassens indstillingsmuligheder, der giver mulighed for at udfolde/lukke alle mapper på en gang.';

?>