<?php

/*
+-----------------------------------------------------------------------+
| language/el_GR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Ανάπτυξη όλων των Φακέλων';
$labels['collapseall'] = 'Κατάρρευση όλων των Φακέλων';
$labels['pluginname'] = 'Ανάπτυξη/Κατάρρευση Φακέλων';
$labels['plugindescription'] = 'Προσθήκη διαχείρισης στις επιλογές αλληλογραφίας για ανάπτυξη/κατάρρευση όλων των φακέλων μαζί.';

?>