<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:32:54
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Expand All Folders';
$labels['collapseall'] = 'Collapse All Folders';
$labels['pluginname'] = 'Expand/Collapse Folders';
$labels['plugindescription'] = 'Add a control to expand/collapse all folders at once.';

?>