<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/folderbuttons/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 06/16/2013 19:19:55
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['expandall'] = 'Expand All Folders';
$labels['collapseall'] = 'Collapse All Folders';
$labels['pluginname'] = 'Expand/Collapse Folders';
$labels['plugindescription'] = 'Add a control in the mailbox options container to expand/collapse all folders at once.';

?>