<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: www.aspHOSTpage.com                                           |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Minden mappát kibont';
$labels['collapseall'] = 'Minden mappát összecsuk';
$labels['pluginname'] = 'Mappák kibontása/összecsukása';
$labels['plugindescription'] = 'A vezérlő segítségével az összes mappa egyszerre kibontható illetve összecsukható.';

?>