<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Espandi tutte le Cartelle';
$labels['collapseall'] = 'Comprimi tutte le Cartelle';
$labels['pluginname'] = 'Espandi/Comprimi Cartelle';
$labels['plugindescription'] = 'Aggiunge un controllo per espandere/comprimere tutte le cartelle.';

?>