<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:           Doubrovine S.                                       |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Развернуть все папки';
$labels['collapseall'] = 'Свернуть все папки';
$labels['pluginname'] = 'Развернуть/Свернуть Папки';
$labels['plugindescription'] = 'Добавляет возможность Развернуть/Свернуть все папки за раз.';

?>