<?php

/*
+-----------------------------------------------------------------------+
| language/tr_TR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['expandall'] = 'Tüm Klasörleri Aç';
$labels['collapseall'] = 'Tüm Klasörleri Kapat';
$labels['pluginname'] = 'Klasörleri Aç/Kapat';
$labels['plugindescription'] = 'Tüm klasörleri tek seferde aç/kapat yapma imkani saglar.';

?>