<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/sabredav_framework/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2015, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 01/11/2015 18:18:17
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'SabreDAV Framework';
$labels['plugindescription'] = 'Helper plugin to distribute SabreDAV Framework customized for MyRoundcube plugins.';

?>