<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 08/13/2014 15:18:38
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Umožní spravovat vaše kontakty v CardDAV serverech.';
$labels['settings'] = 'Nastavení CardDAV';
$labels['sharing'] = 'Sdílení';
$labels['share'] = 'Sdílet';
$labels['shareinvitation'] = 'Poslat pozvánku';
$labels['send'] = 'Poslat';
$labels['cancel'] = 'Zrušit';
$labels['resource'] = 'Zdroj';
$labels['label'] = 'Popisek';
$labels['url'] = 'URL';
$labels['access'] = 'Přístup';
$labels['username'] = 'Uživatel';
$labels['tutorials'] = 'Návody';
$labels['checkresources'] = 'Kontrola zdrojů';
$labels['checkatleastoneresource'] = 'Zkontrolujte prosím alespoň jeden zdroj';
$labels['invitationsubject'] = '%s vám umožnil přístup k adresáři CardDAV';
$labels['confidentialcarddavaccess'] = 'Důvěrný přístup CardDAV';
$labels['copytoclipboard'] = 'Zkopírovat do schránky';
$labels['copiedtoclipboard'] = 'Zkopírováno do schránky';
$labels['sharehint'] = 'Poskytněte výše uvedené údaje (uživatelské jméno, heslo (Token) a adresy URL) ostatním, aby se mohli připojit k vašemu sdílenému adresáři. Tyto informace umožní přístup pro čtení i zápis. Změňte nebo odstraňte token pro zamezení přístupu.';
$labels['sharehint_readonly'] = 'Poskytněte výše uvedené údaje (uživatelské jméno, heslo (Token) a adresy URL) ostatním, aby se mohli připojit k vašemu sdílenému adresáři. Tyto informace umožní přístup pouze pro čtení. Změňte nebo odstraňte token pro zamezení přístupu.';
$labels['readwrite'] = 'čtení/zápis';
$labels['readonly'] = 'pouze čtení';
$labels['abooktoken'] = 'Token';
$labels['isenabled'] = 'je povolen';
$labels['isdisabled'] = 'je zakázán';
$labels['sync_short'] = 'Synchronizovat';
$labels['sync'] = 'Synchronizovat CardDAV';
$labels['add'] = 'Přidat';
$labels['server_url'] = 'URL CardDAV serveru ';
$labels['settings_label'] = 'Kategorie';
$labels['settings_read_only'] = 'Pouze čtení';
$labels['settings_curl_not_installed'] = 'Rozšíření PHP CURL není nainstalováno! Nainstalujte prosím CURL, abyste mohli používat CardDAV doplněk.';
$labels['addressbook_contacts'] = 'Kontakty CardDAV';
$labels['settings_empty_values'] = 'Vylpňte prosím všechny popisky a URL';
$labels['settings_saved'] = 'Nastavení CardDAV serveru a vCard uloženo';
$labels['settings_save_failed'] = 'Chyba při ukládání nastavení serveru CardDAV';
$labels['settings_delete_loading'] = 'Smazání nastavení serveru CardDAV a s tím souvisejících kontaktů';
$labels['settings_delete_warning'] = 'Opravdu chcete smazat tento adresář?';
$labels['settings_delete_contacts_warning'] = 'Opravdu chcete trvale odstranit všechny kontakty v tomto adresáři? Tuto akci nelze vzít zpět. Zvolte OK pro smazání adresáře a všech kontaktů v něm obsažených. Pokud zvolíte Zrušit, tak nedojde k odstranění kontaktů v tomto adresáři.';
$labels['settings_delete_contacts_warning_html'] = 'Opravdu chcete trvale odstranit všechny kontakty v tomto adresáři? Tuto akci nelze vzít zpět. Zvolte Ano pro smazání adresáře a všech kontaktů v něm obsažených. Pokud zvolíte Ne, tak nedojde k odstranění kontaktů v tomto adresáři.';
$labels['settings_deleted'] = 'Nastavení serveru CardDAV vymazáno';
$labels['settings_delete_failed'] = 'Nastavení serveru CardDAV se nezdařilo';
$labels['settings_no_connection'] = 'Nelze se připojit k serveru CardDAV';
$labels['settings_init_server'] = 'Ověřuji připojení k serveru CardDAV a importuji vizitky';
$labels['addressbook_synced'] = 'CardDAV kontakty synchronizovány';
$labels['addressbook_sync_failed'] = 'Nastala chyba při synchronizaci CardDAV kontaktů';
$labels['addressbook_sync_incomplete'] = 'Synchronizace kontaktů CardDAV je nekompletní';
$labels['addressbook_sync_loading'] = 'Synchronizuji CardDAV kontakty';
$labels['contact_moved_single'] = 'kontakt úspěšně přesunut';
$labels['contact_moved_multiple'] = 'kontakty úspěšně přesunuty';
$labels['autocomplete'] = 'Automatické doplnění';
$labels['automaticallycollected'] = 'Automaticky shromážděné';
$labels['automaticallycollected_local'] = 'Automaticky shromážděné (lokální)';
$labels['useautoabook'] = 'Použít automaticky vytvořený adresář';
$labels['useforcompletion'] = 'Použít automaticky shromážděné adresy pro automatické doplnění';
$labels['automatic_addressbook'] = 'Přidat automaticky shromážděné kontakty do ...';
$labels['toggle'] = 'přepínač';
$labels['protected'] = 'chráněný';
$labels['subscribe'] = 'přihlásit';
$labels['unsubscribe'] = 'odhlásit';
$labels['defaultaddressbook'] = 'Osobní kontakty';
$labels['Global'] = 'Globální (pouze pro čtení)';
$labels['Work'] = 'Pracovní';
$labels['Family'] = 'Rodinné';
$labels['Personal'] = 'Osobní';
$labels['Collected'] = 'Shromážděný';
$labels['local'] = 'lokální';
$labels['submenuprefix'] = '»';
$labels['blank'] = ' ';

?>